### ISSUE TITLE
Incorrect documentation for Minimizer.errorbars when scalar_minimize is used.

### ISSUE THREAD

**Issue by andyfaff** [lmfit/lmfit-py#168]
According to the documentation (http://lmfit.github.io/lmfit-py/fitting.html#goodness-of-fit-and-estimated-uncertainty-and-correlations) the Minimizer.errorbars and Minimizer.success attributes should be a boolean.  However, when I use method='nelder-mead' with the Minimizer.minimize method the errorbars and success attributes are None and None, instead of being True/False.

**Comment by newville** [comment]
The `errorbar` attribute now defaults to `False`, and is set to `True` only on successful estimate of the uncertainties.     At least it agrees withe the doc now.   I agree that it would be better to estimate uncertainties in more cases.
