### ISSUE TITLE
lmfit Model class cannot fit complex-valued data

### ISSUE THREAD

**Issue by nulinspiratie** [lmfit/lmfit-py#185]
When trying to fit a function to data using the Model class, lmfit gives an error if the values of the function and of the data is complex-valued. The error seems to occur when lmfit is trying to minimize the residuals, which are also complex-valued. The error given is:

`Result from function call is not a proper array of floats.`

Code that reproduces the error is the following:

    def line(x,a,b):
        return a + b * x + 1.j

    lineModel = lmfit.Model(line)

    params = lineModel.make_params()
    x = np.arange(100)
    y = np.random.randn(100)

    fit = lineModel.fit(data=y,params = params, x = x)

I realize a possibility is to seperate the real and imaginary part, , but I was wondering if there is any way to be able to use complex data with the Model class?

**Comment by newville** [comment]
Please use the mailing list for questions about usage, and Issues only for problems with the code/docs.  

The underlying optimization codes work only with double precision, real values.  Currently, Minimizer and Model both expect the same, and do not check for and auto-convert complex data.  This is easy enough to do yourself with

```python
    def realimag(array):
        return np.array([(x.real, x.imag) for x in array]).flatten()

    def line(x, a, b):
        return realimag(a + b*x + 1.j)
```

You'd need to use that `realimag()` on the `y` data too.   
Again, please use the mailing list for follow-up and related questions.
