### ISSUE TITLE
Check for None in __doc__ before changing it.

### ISSUE THREAD

**Issue by pbrod** [lmfit/lmfit-py#191]
Python code byte-compiled with -OO has doc-strings stripped out. 

This creates problems when compiling different packages which changes the doc-strings by doing something like this:
     __doc__ += "additional text"
(when the docstring is 'None', this will fail).

lmfit/models.py does this and thus creates problems when trying to bytecompile it with the -OO option using  cx_freeze/py2exe.

In order to fix this, I would propose to change all the lines in lmfit/models.py which say:
     __doc__ = XXXX.__doc__ + COMMON_DOC
with
    __doc__ = XXXX.__doc__ + COMMON_DOC if __doc__ else COMMON_DOC

See also:
http://bugs.python.org/issue23189#
http://stackoverflow.com/questions/22299532/unsupported-operand-types-for-nonetype-and-str-winappdbg-error-after-c

**Comment by danielballan** [comment]
That sounds fine. Thanks for pointing this out. Would you be able to write a PR?
