### ISSUE TITLE
Use install_requires in setup.py

### ISSUE THREAD

**Issue by tritemio** [lmfit/lmfit-py#194]
According to the [setuptools documentation](https://pythonhosted.org/setuptools/setuptools.html#new-and-changed-setup-keywords) there is no `requires` (that was in the old distutils sysntax) directive but the correct name is `install_requires`.

Lmfit wrongly uses `requires` in its setup.py:

https://github.com/lmfit/lmfit-py/blob/master/setup.py#L39

We should chage that to `install_requires`.

I think the reason why this was never noticed is that scipy and numpy are almost always already installed when installing lmfit.

**Comment by newville** [comment]
thanks, fixed!
