### ISSUE TITLE
Error when fitting multi-dimensional data by using Model.fit.

### ISSUE THREAD

**Issue by tom1nose** [lmfit/lmfit-py#205]
Model.fit cannot fit multi-dimensional data and I get an error message (error: Result from function call is not a proper array of floats).

As mentioned in [FAQ page](http://lmfit.github.io/lmfit-py/faq.html#how-can-i-fit-multi-dimensional-data), this is due to need for converting residual to a one dimensional array.
So I think `Model._residual` should call `numpy.ndarray.flatten()` before returning.
```
 class Model(object):
 ...
     def _residual(self, params, data, weights, **kwargs):
         "default residual:  (data-model)*weights"
         diff = self.eval(params, **kwargs) - data
         if weights is not None:
             diff *= weights
-        return np.asarray(diff)  # for compatibility with pandas.Series
+        return np.asarray(diff).flatten()
```

**Comment by newville** [comment]
@tom1nose  Thanks, that's a great suggestion.   Anyone see any downsides to doing this?  Perhaps the residual for the Minimizer class should do a similar flattening....

**Comment by andyfaff** [comment]
Would it be better to use `ravel`?  AFAICT a copy isn't always done of the array when you use this method.

**Comment by andyfaff** [comment]
In any case shouldn't the code be using `asfarray`, not asarray?  What happens if the residuals aren't float?  Wouldn't this lead to issues with numerical stability?

**Comment by tom1nose** [comment]
@newville Thanks for replying. Searching "_residual" on GItHub returns only `Model._residual` (sorry, I'm not familiar with GitHub and Git), therefore it seems that any subclasses derived from `Model` doesn't override `_residual`.

**Comment by Tillsten** [comment]
One thing: use `ravel`  instead of `flatten` to save one copy.

**Comment by tom1nose** [comment]
@andyfaff , @Tillsten 
As you say, `np.asarray(diff).ravel()` is faster (especially for large size data). I didn't even know `ndarray.ravel` well. Thanks!

**Comment by andyfaff** [comment]
#206 `ravel`s the output from `Minimizer._residual` and `Model._residual`. It also adds a test to ensure that multidimensional fitting works without flattening arrays.
