### ISSUE TITLE
Can't set 0 as upper boundary for parameters

### ISSUE THREAD

**Issue by carstenblt** [lmfit/lmfit-py#207]
Fitting a parameter with a negative value as lower boundary and 0 as the upper boundary fails because of the check if lower and upper boundaries are equal:

/usr/local/lib/python3.4/site-packages/lmfit/parameter.py in _getval(self)
    369         if self.max < self.min:
    370             self.max, self.min = self.min, self.max
--> 371         if abs((1.0*self.max - self.min)/max(self.max, self.min)) < 1.e-13:
    372             raise ValueError("Parameter '%s' has min == max" % self.name)
    373 

ZeroDivisionError: float division by zero

**Comment by newville** [comment]
@carstenblt -- ah sorry about that.  Should be an easy fix.
