### ISSUE TITLE
Question: the residual of best-fit  

### ISSUE THREAD

**Issue by isaxs** [lmfit/lmfit-py#211]
Dear Sir or Madam,
How can I get the residual of the best-fit? Currently, I have known that we can get all the results from res.residual if we use the codes below.
pars=g1r_mod.make_params()
#fit the curve
print g1.shape,s.shape
res=g1r_mod.fit(g1,pars,s=sv)
#print the fitting report
print(res.fit_report())
However, in the res.residual all the residuals are there. How can I get the best-fit one. Is it the last one? Thanks a lot.

**Comment by newville** [comment]
@isaxs  Please read http://lmfit.github.io/lmfit-py/support.html and use the mailing list for such questions of usage.   Github Issues are for issues with the library.

I'm not entirely sure what you're asking, but it appears you're unsure what is in the return value from your 'g1r_mod.fit()`.  See http://lmfit.github.io/lmfit-py/model.html#modelfit-attributes for a description of what is in that return value.
