### ISSUE TITLE
IPython widets FutureWarning

### ISSUE THREAD

**Issue by tritemio** [lmfit/lmfit-py#215]
In ipython 3, importing the widgets triggers a warning. lmfit detects the presence of the notebook and imports the widgets for its fancy fitting GUI.

However this results in a (relative obscure) warning every time lmfit is imported in a notebook (even if we do no intend to use the widgets), and even more annoying every time a python library imports lmfit.

     :0: FutureWarning: IPython widgets are experimental and may change in the future.

IMHO, there should be a way to import lmfit without widgets (thus avoiding the warning), especially for libraries that use `lmfit`. Would be OK to require a more convoluted import syntax in this case (and leave the default case as is).

**Comment by danielballan** [comment]
Seems like importing the notebook fitter (where widgets are used) should
require a specific separate import.

**Comment by newville** [comment]
@tritemio, @danielballan  +1 on reducing implicit imports of code that might not be used.  Probably just removing https://github.com/lmfit/lmfit-py/blob/master/lmfit/__init__.py#L49 would be enough.

**Comment by tritemio** [comment]
Agree.

**Comment by newville** [comment]
should be resolved wih #216
