### ISSUE TITLE
The expression to express the "less than or larger than"

### ISSUE THREAD

**Issue by isaxs** [lmfit/lmfit-py#218]
I also have the similar problem, but I don't know how to solve this problem?
http://www.tagwith.com/question_733690_defining-upper-bounds-of-one-parameter-in-terms-of-another-using-lmfit-python

Defining upper bounds of one parameter in terms of another using lmfit python
2014-09-17 14:13:04  source
Im trying to fit a model to my data using lmfit, where it is important to the problem that one parameter can never be larger then another. I've tried a couple of things, but none of them seem to work out for me. In lmfit, you can specify parameters as such:

params = Parameters()
params.add('x', value=0.5, min=0, max=1)
params.add('y', value=0.5, min=0, max=1)
I've tried using mathematical expressions to put bounds on the 'x' parameter in terms of the 'y' parameter. One thing that doesn't work is using the parameter in it's own expression, as such:

params['y'].expr='y>x'
as this results in infinite recursion problems. Another solution is to introduce a dummy parameter that reflects a difference between the parameters (as suggested at the mathematical constraints page of lmfit). That would look something like:

params = Parameters()
params.add('x', value=0.5, min=0.0, max=1.0, vary=True)
params.add('d', value=0.0, min=0.0, max=1.0)
params.add('y', value=0.7, min=0.0, max=1.0, expr='x+d')
Although this solution works, it gives me the problem that x will no longer vary and instead will get stuck on it's initial value (although I specifically tell it to vary). Additionally, I was wondering if there would be a simpeler way, as this method does add another parameter to the model, which reduces its AIC..

Help is greatly appreciated!

**Comment by newville** [comment]
I am somewhat unsure how many times I can repeat my plea to use the mailing list and not Github Issues for such questions.  In fact, @isaxs asked a question using Github Issues just two weeks ago, and I explicitly asked to address such questions to the mailing list.  The documentation page at http://lmfit.github.io/lmfit-py/support.html is pretty clear.
  
Can anyone offer any advice or guidance on such matters?  My temptation to simply close the issue, and to close any such non-Issue using Github Issues in the future.   I'd prefer to be helpful.

**Comment by newville** [comment]
ISAXS,

I'm replying to the mailing list.  In the future, use the mailing list, not
Github Issues.  Really.

On Wed, Mar 11, 2015 at 4:44 PM, PlasSAXS <notifications@github.com> wrote:

> I also have the similar problem,
>

You also have a problem similar to what?


> but I don't know how to solve this problem?
>
> http://www.tagwith.com/question_733690_defining-upper-bounds-of-one-parameter-in-terms-of-another-using-lmfit-python
>
>
Not only don't I follow such a site, I'd never heard of it before.  I also
don't answer questions on stackexchange or any other such sites.  If you
want help, ask here, on this mailing list.  If you find an actual problem
*WITH THE CODE*, use Github Issues.    If you are unsure, use the mailing
list.  Really.


> Defining upper bounds of one parameter in terms of another using lmfit
> python
> 2014-09-17 14:13:04 source
> Im trying to fit a model to my data using lmfit, where it is important to
> the problem that one parameter can never be larger then another. I've tried
> a couple of things, but none of them seem to work out for me. In lmfit, you
> can specify parameters as such:
>
> params = Parameters()
> params.add('x', value=0.5, min=0, max=1)
> params.add('y', value=0.5, min=0, max=1)
> I've tried using mathematical expressions to put bounds on the 'x'
> parameter in terms of the 'y' parameter. One thing that doesn't work is
> using the parameter in it's own expression, as such:
>
> params['y'].expr='y>x'
> as this results in infinite recursion problems.
>

That won't work.  It wouldn't work in Python either. "y>x" is boolean.  It
makes no sense.


> Another solution is to introduce a dummy parameter that reflects a
> difference between the parameters (as suggested at the mathematical
> constraints page of lmfit).
>

You mean "suggested in the actual documentation"?  Well, yeah that ought to
be considered reliable, at least in comparison to some crappy website
crawling the web to build ad-laden pages.

That would look something like:
>
> params = Parameters()
> params.add('x', value=0.5, min=0.0, max=1.0, vary=True)
> params.add('d', value=0.0, min=0.0, max=1.0)
> params.add('y', value=0.7, min=0.0, max=1.0, expr='x+d')
> Although this solution works, it gives me the problem that x will no
> longer vary and instead will get stuck on it's initial value (although I
> specifically tell it to vary).
>

This should work.  If it doesn't work for you, post a complete example. The
following works for me:

from numpy import linspace, random
from lmfit import Parameters, Parameter, Minimizer, report_fit
from lmfit.lineshapes import gaussian, lorentzian

def residual(pars, x, data):
    model =  gaussian(x,
                      pars['amp_g'].value,
                      pars['cen_g'].value,
                      pars['wid_g'].value)
    model += lorentzian(x,
                        pars['amp_l'].value,
                        pars['cen_l'].value,
                        pars['wid_l'].value)
    return (model - data)


n = 601
random.seed(0)
x = linspace(0, 20.0, n)

data = (gaussian(x,   21, 6.1, 1.2) +
        lorentzian(x, 10, 9.6, 1.3) +
        random.normal(scale=0.1,  size=n))

pfit = Parameters()
pfit.add(name='amp_g',  value=10)
pfit.add(name='amp_l',  value=10)
pfit.add(name='cen_g',  value=5)
pfit.add(name='peak_split',  value=2.5, min=0, max=5, vary=True)
pfit.add(name='cen_l',  expr='peak_split+cen_g')
pfit.add(name='wid_g',  value=1)
pfit.add(name='wid_l',  expr='wid_g')

myfit = Minimizer(residual, pfit, fcn_args=(x, data))
myfit.leastsq()

report_fit(myfit.params)


--Matt

PS: reply to the mailing list.  Really.

**Comment by newville** [comment]
not an actual issue.

**Comment by newville** [comment]
Thanks a lot. I will put the questions in the mailing list next time. I 
promise. I will open a new post to say my problem clearly.
