### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by rififi** [lmfit/lmfit-py#222]
Hi :)

I'm using lmfit to fit a "complex" model onto experimental data.

I define the parameters of the model like this:

    

    def model(t, y0, h, A1, x1, s1, A2, x2, s2, A3, x3, s3, A4, x4, s4):
    
            y = y0 + h * (
                          A1 * (0.5 + 0.5 * erf((t - x1) / (s1 * 2**0.5))) +
                          A2 * (0.5 + 0.5 * erf((t - x2) / (s2 * 2**0.5))) +
                          A3 * (0.5 + 0.5 * erf((t - x3) / (s3 * 2**0.5))) +
                          A4 * (0.5 + 0.5 * erf((t - x4) / (s4 * 2**0.5)))
                          )
            return y

    
    mod = Model(model)

    # sys.setrecursionlimit(150000)

    # Set the parameters, define their bounds and their relations
    mod.set_param_hint('y0', value=self.spin_y0.value())
    mod.set_param_hint('h', value=self.spin_h.value())

    mod.set_param_hint('A1', value=self.spin_A1.value(), min=0, max=1),
    mod.set_param_hint('x1', value=self.spin_x1.value(), min=0, max=self.x[-1])
    mod.set_param_hint('s1', value=self.spin_s1.value(), min=0)

    mod.set_param_hint('A2', value=self.spin_A2.value(), min=0, max=1),
    mod.set_param_hint('x2', value=self.spin_x2.value(), min=0, max=self.x[-1])
    mod.set_param_hint('s2', value=self.spin_s2.value(), min=0)

    mod.set_param_hint('A3', value=self.spin_A3.value(), min=0, max=1),
    mod.set_param_hint('x3', value=self.spin_x3.value(), min=0, max=self.x[-1])
    mod.set_param_hint('s3', value=self.spin_s3.value(), min=0)

    mod.set_param_hint('A4', value=self.spin_A4.value(), min=0, max=1),
    mod.set_param_hint('x4', value=self.spin_x4.value(), min=0, max=self.x[-1])
    mod.set_param_hint('s4', value=self.spin_s4.value(), min=0)

    mod.set_param_hint('A1', expr='1-A2-A3-A4')
    mod.set_param_hint('A2', expr='1-A1-A3-A4')
    mod.set_param_hint('A3', expr='1-A1-A2-A4')
    mod.set_param_hint('A4', expr='1-A1-A2-A3')

    mod.make_params()

    # Fit the data !
    result = mod.fit(self.y, t=self.x)

I use spinBoxes to get the values which will be used as initial values (my program is a GUI).

I have a problem with A1, A2, A3 and A4. They are dependent, and their sum must be equal to 1.

If I comment

    mod.set_param_hint('A1', expr='1-A2-A3-A4')
    mod.set_param_hint('A2', expr='1-A1-A3-A4')
    mod.set_param_hint('A3', expr='1-A1-A2-A4')
    mod.set_param_hint('A4', expr='1-A1-A2-A3

The parameters vary between 0 and 1 (I define this range when I define the parameters), but their sum is never equal to 1.

When these lines are not commented, I have the following exception:

    File "/usr/lib/python3.4/site-packages/lmfit/minimizer.py", line 255, in __update_paramval
        self.__update_paramval(dep)
      File "/usr/lib/python3.4/site-packages/lmfit/minimizer.py", line 250, in __update_paramval
        if getattr(par, 'expr', None) is not None:
    RuntimeError: maximum recursion depth exceeded

I don't really know what it means. I tried to increase the maximum recursion depth, but it changed nothing.

Do you have any idea about what is the problem ?

**Comment by newville** [comment]
Riffi,

Please use the mailing lists for such questions (see
http://lmfit.github.io/lmfit-py/support.html).  In fact, please make sure
to reply to the mailing list for follow up discussions.

On Fri, Mar 20, 2015 at 5:49 AM, rififi <notifications@github.com> wrote:

> Hi :)
>
> I'm using lmfit to fit a "complex" model onto experimental data.
>
> I define the parameters of the model like this:
>
> def model(t, y0, h, A1, x1, s1, A2, x2, s2, A3, x3, s3, A4, x4, s4):
>
>         y = y0 + h * (
>                       A1 * (0.5 + 0.5 * erf((t - x1) / (s1 * 2**0.5))) +
>                       A2 * (0.5 + 0.5 * erf((t - x2) / (s2 * 2**0.5))) +
>                       A3 * (0.5 + 0.5 * erf((t - x3) / (s3 * 2**0.5))) +
>                       A4 * (0.5 + 0.5 * erf((t - x4) / (s4 * 2**0.5)))
>                       )
>         return y
>
>
> mod = Model(model)
>
> # sys.setrecursionlimit(150000)
>
> # Set the parameters, define their bounds and their relations
> mod.set_param_hint('y0', value=self.spin_y0.value())
> mod.set_param_hint('h', value=self.spin_h.value())
>
> mod.set_param_hint('A1', value=self.spin_A1.value(), min=0, max=1),
> mod.set_param_hint('x1', value=self.spin_x1.value(), min=0, max=self.x[-1])
> mod.set_param_hint('s1', value=self.spin_s1.value(), min=0)
>
> mod.set_param_hint('A2', value=self.spin_A2.value(), min=0, max=1),
> mod.set_param_hint('x2', value=self.spin_x2.value(), min=0, max=self.x[-1])
> mod.set_param_hint('s2', value=self.spin_s2.value(), min=0)
>
> mod.set_param_hint('A3', value=self.spin_A3.value(), min=0, max=1),
> mod.set_param_hint('x3', value=self.spin_x3.value(), min=0, max=self.x[-1])
> mod.set_param_hint('s3', value=self.spin_s3.value(), min=0)
>
> mod.set_param_hint('A4', value=self.spin_A4.value(), min=0, max=1),
> mod.set_param_hint('x4', value=self.spin_x4.value(), min=0, max=self.x[-1])
> mod.set_param_hint('s4', value=self.spin_s4.value(), min=0)
>
> mod.set_param_hint('A1', expr='1-A2-A3-A4')
> mod.set_param_hint('A2', expr='1-A1-A3-A4')
> mod.set_param_hint('A3', expr='1-A1-A2-A4')
> mod.set_param_hint('A4', expr='1-A1-A2-A3')
>
> mod.make_params()
>
> # Fit the data !
> result = mod.fit(self.y, t=self.x)
>
> I use spinBoxes to get the values which will be used as initial values (my
> program is a GUI).
>
> I have a problem with A1, A2, A3 and A4. They are dependent, and their sum
> must be equal to 1.
>
> If I comment
>
> mod.set_param_hint('A1', expr='1-A2-A3-A4')
> mod.set_param_hint('A2', expr='1-A1-A3-A4')
> mod.set_param_hint('A3', expr='1-A1-A2-A4')
> mod.set_param_hint('A4', expr='1-A1-A2-A3
>
> The parameters vary between 0 and 1 (I define this range when I define the
> parameters), but their sum is never equal to 1.
>
> When these lines are not commented, I have the following exception:
>
> File "/usr/lib/python3.4/site-packages/lmfit/minimizer.py", line 255, in __update_paramval
>     self.__update_paramval(dep)
>   File "/usr/lib/python3.4/site-packages/lmfit/minimizer.py", line 250, in __update_paramval
>     if getattr(par, 'expr', None) is not None:
> RuntimeError: maximum recursion depth exceeded
>
> I don't really know what it means. I tried to increase the maximum
> recursion depth, but it changed nothing.
>
> Do you have any idea about what is the problem ?
>

You're telling the parameters to be inter-dependent, and it cannot figure
out what they evaluate too.   That is, for 'A1', you're telling it to
evaluate '1-A2-A3-A4'.  So, it needs to know the values of 'A2', 'A3', and
'A4'.   To get the value of 'A2', it sees that it needs to evaluate
'1-A1-A3-A4, and so needs the value for 'A1'.  This leads to recursion, and
the limit you see.  Fortunately, Python raises an exception about this.

If I understand correctly, you're trying to express  'allow A1, A2, A3, A4
to vary, keeping each between 0 and 1, and having them sum to 1'.     Aside
from the limited range, that is not 4 constraints (as you have) but 1.   So
you could just have 'A1', 'A2', and 'A3' varying (bounded) and set 'A4'  to
have an expr of '1-A1-A2-A3'.  I've done this before myself in a few cases,
and it works, at least in well-behaved cases.

But now that I write that I'm not sure it will be exactly perfect in all
cases.   That is, bounds placed on 'A4' will be respected, but might mean
that the sum is not obeyed.   That is, having A1=0.9, A2=0.1, A3=0.1, would
be allowed, but imply A4=0 -- the sum is not preserved.    I think I've
always *not* placed bounds on the equivalent of 'A4', but used it's value
as a sanity check.   Off the top of my head, I'm not sure this is complete
solvable (suggestions welcome!), but at least the fit will run and give you
results that you can then decide whether they are sensible.

--Matt

**Comment by newville** [comment]
You completely understood the problem.

You are right, I think the solution you suggested won't work everytime. 
Actually, A1, A2, A3 and A4 are the contributions to the signal of 4 
analyts (4 molecules). I *know* there are 4 analyts, so the sum *must* be 
obeyed.

A friend can fit the data with the Excel's solver, so I can't imagine there 
isn't a Python solution.

**Comment by newville** [comment]
On Fri, Mar 20, 2015 at 8:51 AM, jean-patrick francoia <
jeanpatrick.francoia@gmail.com> wrote:

> You completely understood the problem.
>
> You are right, I think the solution you suggested won't work everytime.
> Actually, A1, A2, A3 and A4 are the contributions to the signal of 4
> analyts (4 molecules). I *know* there are 4 analyts, so the sum *must* be
> obeyed.
>


Did you try it or are you worried about something that *might* be a problem?

If the bounds push the values toward a solution that doesn't obey the sum,
what do you do?   That is, which do you believe more: that the values
should be freely varying or that the sum should be 1?

If the sum==1 (to what precision?) is the paramount consideration, you can
also consider adding that as a condition on the residual.   That is,
consider "A1+A2+A3+A4" as a piece of data, with a model value of 1, and a
very, very small uncertainty and very large weighting.



>
> A friend can fit the data with the Excel's solver, so I can't imagine
> there isn't a Python solution.
>


Hmm, maybe.  If you have a better approach, I'd be happy to hear about it.

--Matt

**Comment by newville** [comment]
>
> Did you try it or are you worried about something that *might* be a 
> problem?
>

I tried, it happened.

If the bounds push the values toward a solution that doesn't obey the sum, 
> what do you do?   That is, which do you believe more: that the values 
> should be freely varying or that the sum should be 1?
>

I trust the sum. The signal I'm trying to fit comes from an experiment (a 
real one). Iknow what I have in my hands, in my solution. I know I have 4 
molecules, each one contributing to the signal. So each contribution ranges 
from 0 to 1, and all the contributions = 1. 

If the sum==1 (to what precision?) is the paramount consideration, you can 
> also consider adding that as a condition on the residual.   That is, 
> consider "A1+A2+A3+A4" as a piece of data, with a model value of 1, and a 
> very, very small uncertainty and very large weighting. 
>

I don't really understand what you mean. But I also more or less know the 
contribution of each molecule to the signal. I also have a very good idea 
of what the values of the parameters I should have at the end. Maybe you 
can clarify this question ?

**Comment by newville** [comment]
On Fri, Mar 20, 2015 at 12:08 PM, jean-patrick francoia <
jeanpatrick.francoia@gmail.com> wrote:

> Did you try it or are you worried about something that *might* be a
>> problem?
>>
>
> I tried, it happened.
>
> If the bounds push the values toward a solution that doesn't obey the sum,
>> what do you do?   That is, which do you believe more: that the values
>> should be freely varying or that the sum should be 1?
>>
>
> I trust the sum. The signal I'm trying to fit comes from an experiment (a
> real one). Iknow what I have in my hands, in my solution. I know I have 4
> molecules, each one contributing to the signal. So each contribution ranges
> from 0 to 1, and all the contributions = 1.
>

OK, but in the real experiment of trying to interpret the data with such a
model, that appears to have not worked, right?   So now what?  Blame the
mathematical algorithm?

One should always be cautious when using constraints or even bounds. With
these, you are requiring the fit to not go to some set of parameters that
it would otherwise want to go.  Obviously, some times you need these, and
they can be very useful in creating abstract models.  But,  if they are
restricting the model from going into some part of parameter space that it
really wants to explore, it's probably wise to try to figure out why that
is.

I don't know anything about what you're doing, but if your model and the
idea that A1, A2, A3, A4 summed to 1 and were all on [0, 1] was undeniably
correct, then you probably wouldn't need any bounds or the constraint sum
at all, right?    So, you might ask yourself why your data is telling you
something that does not agree with your prior assumptions.


> If the sum==1 (to what precision?) is the paramount consideration, you can
>> also consider adding that as a condition on the residual.   That is,
>> consider "A1+A2+A3+A4" as a piece of data, with a model value of 1, and a
>> very, very small uncertainty and very large weighting.
>>
>
> I don't really understand what you mean. But I also more or less know the
> contribution of each molecule to the signal. I also have a very good idea
> of what the values of the parameters I should have at the end. Maybe you
> can clarify this question ?
>

The typical way of thinking about any curve-fitting problem is that you
have N observations and a parametrized model for these.  You're trying to
find a set of parameters that minimizes the difference between model and
data, possibly weighted by some factor.  So your objective function would be

    def obj(params, data, x, weights):
        model = my_model_function(params, x=x)
        return (data-model)*weights

To expand on this, you could consider your values for A1, A2, A3, A4 as
*data* (measured in a sense by the data and model) for which you have a
"model" (== 1.0).  Then, you could append a term of "A1+A2+A3+A4  - 1.0" to
the residual function, as with

    def obj(params, data, x, weights, sum_weight):
        model = my_model_function(params, x=x)
        resid = (data-model)
        restraint = (params['A1'].value + params['A2'].value +
                          params['A3'].value + params['A4'].value) - 1.0
        return np.concatenate((resid*weights, restraint*sum_weight))

Now, you are treating the sum of A1, A2, A3, A4 as an observation that you
model.  You have to choose a relative weighting, but the benefit is that
you get to choose a relative weighting for how much you believe what your
data (and model) tells you about the values of A1, A2, A3, and A4, and what
your prior knowledge about their sum.   You might think this additional
weight complicates the problem, but in a sense it actually clarifies what
the problem really is -- how much do you believe your data compared to how
much do you believe the constraint.

Of course, this approach is not always necessary, but it's sometimes quite
useful.

Hope that helps,

--Matt

**Comment by Tillsten** [comment]
I would use a solver which is implict designed to support such contraints.
One could try to build their own objective function to simulate that, but to
get that and right and stable is not easy task.

**Comment by newville** [comment]
On Fri, Mar 20, 2015 at 4:48 PM, Till Stensitzki <notifications@github.com>
wrote:

> I would use a solver which is implict designed to support such contraints.
> One could try to build their own objective function to simulate that, but
> to
> get that and right and stable is not easy task.
>


Can you recommend a good one?  Should we try to include such a solver in
lmfit?

--Matt Newville

**Comment by newville** [comment]
conversation moved to mailing list.
