### ISSUE TITLE
Citing lmfit

### ISSUE THREAD

**Issue by yoavram** [lmfit/lmfit-py#225]
Is there a way to cite lmfit in an academic manuscript, other than to just link to the webpage?

**Comment by yoavram** [comment]
Found it - [![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.11813.svg)](http://dx.doi.org/10.5281/zenodo.11813)

**Comment by yoavram** [comment]
I'm reopening - I suggest that info on how to cite lmfit will appear either on the webpage or as `lmfit.__citation__` or `lmfit.citation()`.

**Comment by newville** [comment]
@yoavram   Please use the lmfit mailing list for questions and reserve Github Issues only for actual issues.  I've made this plea repeatedly, and it is explicitly stated in the documentation at
    http://lmfit.github.io/lmfit-py/support.html

I'm -1 on a ``lmfit.__citation__`` or ``lmfit.citation()`` --- who would think to look there?  I would be OK with adding the DOI link to ``lmfiit.__doc__``.  

As for adding it to "the webpage", it *is* on the Github project page as a "DOI badge".  Perhaps that's not sufficient?  Perhaps you meant in the on-line documentation?  That would be OK with me, but it seems ironic as you apparently didn't read this documentation yourself.  Anyway, a PR for that would be helpful.

**Comment by yoavram** [comment]
Sorry, you are right. I found the badge and missed the instructions on the support (was looking F r citation and info..). Closing.
