### ISSUE TITLE
NIST test failure 

### ISSUE THREAD

**Issue by sciunto** [lmfit/lmfit-py#23]
Hi,

I ran the NIST test embedded within the project. I was surprised that some of them fail. For instance Gauss3 with start2 or Lanczos\* with start1.

To investigate a bit what's happening, I checked if it is an upstream issue or not. 
Thus, I reused some functions implemented here (for NIST) and I applied them on leastsq() provided by scipy.optimize, the same which is called by lmfit.
It appears that all tests succeed (ie, I have fairly good results) for all tests with start2 and more than lmfit for start1.

You can see in this pastebin the results with leastsq. (Optimized vs certified parameters and the highest relative error).
http://pastebin.com/NNrj82q6 (start1)
http://pastebin.com/7HmjB5Ju (start2)
The output is very basic but enough for the purpose I guess.

For the moment, I have no idea on what's going wrong in lmfit. I'm not familiar enough with the minimizer code.

**Comment by newville** [comment]
Closing again... I don't think we're going to do better than we are doing on these.
