### ISSUE TITLE
Accessing Model names from CompositeModel

### ISSUE THREAD

**Issue by cachitas** [lmfit/lmfit-py#231]
Say I have a CompositeModel defined like

```
g1 = GaussianModel(name='g1', prefix='g1_')
g2 = GaussianModel(name='g2', prefix='g2_')

model = g1 + g2
```

Here, `model.name` returns an empty string as expected because I did not set a name for it.
But I want to access submodel's names `g1` and `g2`. What is the correct way to achieve this?

**Note:**
Ok so while I was writting this, I found the attribute `CompositeModel.components` which returns a list of the models used, from where I can extract the names I want. This solves my problem. Remains to ask only if this is the intended way to do it?
Also, I decided to open the issue anyway because I did not find this anywhere in the documentation.

**Comment by tritemio** [comment]
In principle the `name` property defined in `Model` should be inherited by `CompositeModel`, so you should always get a default name for a composite model, if not it may be a bug. Which version of lmfit are you using?

Regarding the accessing `components`, yes this is the public property meant to be used to access the list of sub-models.

**Comment by newville** [comment]
@cachitas  did you read the Guidelines?  I am surprised one could read those and still use 
Github issues to ask this question.    

Also, just to be clear, I dispute your claim that this is not discussed in the documentation.   I would answer the question if it were sent to the mailing list, but am closing this issue.

**Comment by danielballan** [comment]
@tritemio @cachitas I actually like that CompositeModels should have no name by default. The `components` is a clear way to access the relevant information, and CompositeModels should be given their own name explicitly by the user, if desired.

**Comment by newville** [comment]
On Fri, May 22, 2015 at 1:07 PM, Dan Allan <notifications@github.com> wrote:

> @tritemio <https://github.com/tritemio> @cachitas
> <https://github.com/cachitas> I actually like that CompositeModels should
> have no name by default. The components is a clear way to access the
> relevant information, and CompositeModels should be given their own name
> explicitly by the user, if desired.
>
Just to set the record straight: CompositModels do have a non-blank name by
default.   The original report is simply incorrect or out of date.  With
version 0.8.3 and later:

    >>> import lmfit
    >>> from lmfit.models import GaussianModel
    >>> g1 = GaussianModel(name='g1', prefix='g1_')
    >>> g2 = GaussianModel(name='g2', prefix='g2_')
    >>> model = g1 + g2
    >>> model.name
    "(Model(g1, prefix='g1_') + Model(g2, prefix='g2_'))"

I agree that it is useful to be able to rename a model, but a default name
is given.

Also, FWIW, CompositeModel.components gives a simple list of components.
But, now that operators other than addition of components are supported,
CompositeModel.left, CompositeModel.right, and CompositeModel.op give a
more precise description of the composite model.

**Comment by cachitas** [comment]
@newville 
First of all, I think it was not necessary to be that rude, but probably you have issues with having Issues here... even the beforehand solved.

Secondly, I came from the docs [here](http://lmfit.github.io/lmfit-py/model.html?highlight=compositemodel#model.CompositeModel) and I could not find any reference to a `components` attribute. Can you point it to me? 

And yes, I did not read the README (if that's what you mean by Guidelines. Where is that section named Guidelines anyway?) where you mention we should head to the Google group to ask questions. I was in the docs. If I don't find something there, I don't expect to find it in the README.

Anyway, my apologies for opening an Issue.
