### ISSUE TITLE
Illegal boundary values

### ISSUE THREAD

**Issue by dayglopirate** [lmfit/lmfit-py#235]
In parameter.py [0.8.3] there is a check for zero-range parameter boundaries (min==max).  The function is 

[371] if abs((1.0*self.max - self.min)/max(self.max, self.min)) < 1.e-13: , 

which crashes if the maximum boundary is zero.  Ranges like [-x,0] are blocked by a zero division error.

**Comment by newville** [comment]
@dayglopirate I believe this is fixed in the current master branch, as of 3a0eca974549495299d14f2bce3aecdb5edfe8fe.  See
https://github.com/lmfit/lmfit-py/blob/master/lmfit/parameter.py#L457

**Comment by dayglopirate** [comment]
great, fixed
