### ISSUE TITLE
Maybe something in Parameters update_constraint is broken

### ISSUE THREAD

**Issue by MerlinSmiles** [lmfit/lmfit-py#237]
I don't really understand this error, and it is a bit hard to reproduce.

The error I get is:
```
/Users/Merlin/git/lmfit-py/lmfit/parameter.py in _update_param(name)
    107             if par._expr is not None:
    108                 par.expr = par._expr
--> 109             if par._expr_ast is not None:
    110                 for dep in par._expr_deps:
    111                     if dep in self.keys():

AttributeError: 'Parameter' object has no attribute '_expr_ast'
```
I get this error when I use the Ipython notebook and the embedded widgets, if I run this:
```
%matplotlib inline
import numpy as np
import lmfit
from lmfit.ui import Fitter
data = np.array([1,2,3,4,5,4,3,2])
x = np.arange(len(data))/2.0

Fitter( x=x, data = data)
```
and in the widget disable a 'vary' checkbox, then this error occurs when hitting the fit button.

I can make it disappear by adding
```
if not hasattr(par, '_expr_ast'):
    par._expr_ast = None
```
on line 104 in parameter.py

**Comment by danielballan** [comment]
@newville Is it OK if we add ``self._expr_ast = None`` to the ``__init__`` method of ``Parameter``? That seems like the right place to "fix" this.

**Comment by MerlinSmiles** [comment]
@danielballan this is already there.

**Comment by danielballan** [comment]
Huh. Then this bug is confusing.

**Comment by newville** [comment]
Yeah, that seems weird. @MerlinSmiles could you try printing out what the type for the 'par' variable is there.  I suspect something other than a Parameter might being passed in, somehow.   Like, it might be None here, as there are no actual parameters defined.    I also wonder if this might be related to the picklability problem we had a few months ago.  But probably having no parameters is the cause.... if that is the case, the message should definitely better!

**Comment by tacaswell** [comment]
pickling smells right.  I did a bit of skimming to find where you could be creating instances with out going through `__init__` and pickle does that.

**Comment by MerlinSmiles** [comment]
@newville Sure I can, I print ```par```, and ```par._expr_ast``` for the example above
```
par <Parameter 'decay', 1, bounds=[-inf:inf]>
par._expr_ast None
par <Parameter 'decay', 1, bounds=[-inf:inf]>
par._expr_ast None
par <Parameter 'amplitude', 1, bounds=[-inf:inf]>
par._expr_ast None
par <Parameter 'decay', -10.425156100771209, bounds=[-inf:inf]>
par._expr_ast None
par <Parameter 'amplitude', 1, bounds=[-inf:inf]>
par._expr_ast None
par <Parameter 'decay', -10.425156100771209, bounds=[-inf:inf]>
par._expr_ast None
par <Parameter 'amplitude', value=2.5261016450017846 (fixed), bounds=[-inf:inf]>
```
after some iterations it has lost its attribute: ```AttributeError: 'Parameter' object has no attribute '_expr_ast'```

**Comment by newville** [comment]
@tacaswell @MerlinSmiles if pickling is indeed the problem, it may be sufficient to add
```python:
        self._expr_ast = None
        self._expr_eval = None
``` 
to Parameter.__setstate__().   It's a guess that it might solve the immediate problem. But it may also defer other problems that actually use constraints....  

It would be nice to figure out what IPython is doing when communicating from its Notebook to engine so we can better test these things.  I'm afraid I don't know these details.  Then again, I was surprised by the last IPython-only "bug" (really, ZeroMQ's bug-- we were willing to sacrifice unneeded flexibility to match their broken communication layer).  But if IPython is using pickle to transfer objects between notebook and server process, we can't be the only ones running into such problems.

**Comment by MerlinSmiles** [comment]
@newville That is interesting, I have no understanding of the Pickling and especially not how IPython notebook works with that. Also I cant find the .setstate() you are mentioning to test your guess.
```
    def __setstate__(self, state):
        """set state for pickle"""
        (self.name, self.value, self.vary, self.expr, self.min,
         self.max, self.stderr, self.correl, self.init_value) = state
        self._init_bounds()
```
?
But I agree with you, that if this is an IPython problem it should be solved there.

**Comment by newville** [comment]
@MerlinSmiles sorry -- was typing on a small device, and forgot all the Markdown rendering.  I did mean  `Parameter.__setstate__()`,  which might need to be approximately

```python
    def __setstate__(self, state):
        """set state for pickle"""
        (self.name, self.value, self.vary, self.expr, self.min,
         self.max, self.stderr, self.correl, self.init_value) = state
        self._expr_ast = None
        self._expr_eval = None
        self._expr_deps = []
        self._init_bounds()
```

but it still seems really strange, because the error you got was essentially saying that `par` does not have a `_expr_ast`, but it **did** have a `_expr` and an `_expr_eval`.   I don't really understand how that is possible....

**Comment by MerlinSmiles** [comment]
@newville That indeed fixes the problem.

To me it seemed that par forgot its ```_expr_ast``` after the second iteration...

**Comment by newville** [comment]
addressed,
