### ISSUE TITLE
Model.fit throwing an error when trying to use weights in fitting

### ISSUE THREAD

**Issue by HamishBrownPFR** [lmfit/lmfit-py#238]
Sorry if you are not expecting random strangers to log issues but I am stuck and beyond the extend of the doco and my debugging skills.

I am trying to use lmfit to fit a sigmoid function to a data set and weight the fits toward the upper boundary of the data.  However, I am getting an error when I include weights in the fit expression.  I have checked that the weights object I am providing is in the same format and is the same dimensions and the x and y objects that I am fitting to and can't solve this one.

I have set up a note book with an example showing the error I am getting (https://github.com/PlantandFoodResearch/MGM-file-generation/blob/master/SparseMatrixYields/Weighting%20error.ipynb) 

The data pickles I am using are:
https://github.com/PlantandFoodResearch/MGM-file-generation/blob/master/SparseMatrixYields/Xdata.pkl
and
https://github.com/PlantandFoodResearch/MGM-file-generation/blob/master/SparseMatrixYields/Ydata.pkl

**Comment by tacaswell** [comment]
@HamishBrownPFR It is best to paste the trace backs directly into the issue (as that link gets a 404).

It is also best to post minimal examples to demonstrate your problem.  pkl files are huge security holes and most people will not open pickles from untrusted sources.

**Comment by HamishBrownPFR** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b886f84b9fcf> in <module>()
     18 
     19 #Recrank fitting with weighting toward upper threshold
---> 20 yUpperFit = mod.fit(y, params, x=x, weights = Weightings)
     21 yplotUpper = mod.eval(yUpperFit.params,x=xplot)
     22 

C:\Anaconda\lib\site-packages\lmfit\model.pyc in fit(self, data, params, weights, method, iter_cb, scale_covar, verbose, fit_kws, **kwargs)
    499         output = ModelFit(self, params, method=method, iter_cb=iter_cb,
    500                           scale_covar=scale_covar, fcn_kws=kwargs, **fit_kws)
--> 501         output.fit(data=data, weights=weights)
    502         output.components = self.components
    503         return output

C:\Anaconda\lib\site-packages\lmfit\model.pyc in fit(self, data, params, weights, method, **kwargs)
    704         self.init_fit    = self.model.eval(params=self.init_params, **self.userkws)
    705 
--> 706         self.minimize(method=self.method)
    707         self.best_fit = self.model.eval(params=self.params, **self.userkws)
    708         self.best_values = self.model._make_all_args(self.params)

C:\Anaconda\lib\site-packages\lmfit\minimizer.pyc in minimize(self, method)
    755             function = self.lbfgsb
    756 
--> 757         return function(**kwargs)
    758 
    759 

C:\Anaconda\lib\site-packages\lmfit\minimizer.pyc in leastsq(self, **kws)
    604         orig_warn_settings = np.geterr()
    605         np.seterr(all='ignore')
--> 606         lsout = scipy_leastsq(self.__residual, self.vars, **lskws)
    607         _best, _cov, infodict, errmsg, ier = lsout
    608 

C:\Anaconda\lib\site-packages\scipy\optimize\minpack.pyc in leastsq(func, x0, args, Dfun, full_output, col_deriv, ftol, xtol, gtol, maxfev, epsfcn, factor, diag)
    369     if not isinstance(args, tuple):
    370         args = (args,)
--> 371     shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
    372     m = shape[0]
    373     if n > m:

C:\Anaconda\lib\site-packages\scipy\optimize\minpack.pyc in _check_func(checker, argname, thefunc, x0, args, numinputs, output_shape)
     18 def _check_func(checker, argname, thefunc, x0, args, numinputs,
     19                 output_shape=None):
---> 20     res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
     21     if (output_shape is not None) and (shape(res) != output_shape):
     22         if (output_shape[0] != 1):

C:\Anaconda\lib\site-packages\lmfit\minimizer.pyc in __residual(self, fvars)
    286 
    287         self.update_constraints()
--> 288         out = self.userfcn(self.params, *self.userargs, **self.userkws)
    289         if callable(self.iter_cb):
    290             self.iter_cb(self.params, self.nfev, out,

C:\Anaconda\lib\site-packages\lmfit\model.pyc in _residual(self, params, data, weights, **kwargs)
    314         diff = self.eval(params, **kwargs) - data
    315         if weights is not None:
--> 316             diff *= weights
    317         return np.asarray(diff)  # for compatibility with pandas.Series
    318 

C:\Anaconda\lib\site-packages\pandas\core\ops.pyc in f(self, other)
    183             # this makes sure that we are aligned like the input
    184             # we are updating inplace so we want to ignore is_copy
--> 185             self._update_inplace(result.reindex_like(self,copy=False)._data,
    186                                  verify_is_copy=False)
    187 

C:\Anaconda\lib\site-packages\pandas\core\generic.pyc in reindex_like(self, other, method, copy, limit)
   1530         """
   1531         d = other._construct_axes_dict(method=method, copy=copy, limit=limit)
-> 1532         return self.reindex(**d)
   1533 
   1534     def drop(self, labels, axis=0, level=None, inplace=False, **kwargs):

C:\Anaconda\lib\site-packages\pandas\core\series.pyc in reindex(self, index, **kwargs)
   2147     @Appender(generic._shared_docs['reindex'] % _shared_doc_kwargs)
   2148     def reindex(self, index=None, **kwargs):
-> 2149         return super(Series, self).reindex(index=index, **kwargs)
   2150 
   2151     def reindex_axis(self, labels, axis=0, **kwargs):

C:\Anaconda\lib\site-packages\pandas\core\generic.pyc in reindex(self, *args, **kwargs)
   1729         # perform the reindex on the axes
   1730         return self._reindex_axes(axes, level, limit,
-> 1731                                   method, fill_value, copy).__finalize__(self)
   1732 
   1733     def _reindex_axes(self, axes, level, limit, method, fill_value, copy):

C:\Anaconda\lib\site-packages\pandas\core\generic.pyc in _reindex_axes(self, axes, level, limit, method, fill_value, copy)
   1747                 {axis: [new_index, indexer]}, method=method,
   1748                 fill_value=fill_value, limit=limit, copy=copy,
-> 1749                 allow_dups=False)
   1750 
   1751         return obj

C:\Anaconda\lib\site-packages\pandas\core\generic.pyc in _reindex_with_indexers(self, reindexers, method, fill_value, limit, copy, allow_dups)
   1832                                                 fill_value=fill_value,
   1833                                                 allow_dups=allow_dups,
-> 1834                                                 copy=copy)
   1835 
   1836         if copy and new_data is self._data:

C:\Anaconda\lib\site-packages\pandas\core\internals.pyc in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy)
   3148         if (not allow_dups and not self.axes[axis].is_unique
   3149             and len(indexer)):
-> 3150             raise ValueError("cannot reindex from a duplicate axis")
   3151 
   3152         if axis >= self.ndim:

ValueError: cannot reindex from a duplicate axis

**Comment by HamishBrownPFR** [comment]
I will alter the example to read data from csv files

**Comment by HamishBrownPFR** [comment]
I have updated the example:
https://github.com/PlantandFoodResearch/MGM-file-generation/blob/master/SparseMatrixYields/Weighting%20error.ipynb

To get it data from csv files:
https://github.com/PlantandFoodResearch/MGM-file-generation/blob/master/SparseMatrixYields/Xdata.csv

and
https://github.com/PlantandFoodResearch/MGM-file-generation/blob/master/SparseMatrixYields/Ydata.csv

**Comment by HamishBrownPFR** [comment]
The interesting thing is it now works.  It must be something in the way the structure of the data coming in

**Comment by newville** [comment]
@HamishBrownPFR   Sorry for the trouble.   Generally, using the mailing list is the preferred starting point for discussions that are not obviously bugs.  

I could not open any of the links you gave -- all returned 404.   Like @tacaswell says, short, complete examples are best.

From the traceback you gave, it appears that both the data and the weights are Pandas Series.  We intend to support Pandas data structures, but it may be that we've missed somewhere.    For example, the place in lmfit that raises the exception inside Pandas is 

```python
# C:\Anaconda\lib\site-packages\lmfit\model.pyc in _residual(self, params, data, weights, *kwargs)
diff = self.eval(params, *kwargs) - data
if weights is not None:
    diff *= weights
return np.asarray(diff) # for compatibility with pandas.Series 
```

which suggests that there might be a problem multiplying "diff" and "weights" if they are Series, (as the code is assuming numpy arrays).   It might be that we need to do (around line 315  of model.py):

```python
diff = self.eval(params, *kwargs) - np.asarray(data)
if weights is not None:
    diff *= np.asarray(weights)
return diff
```

to best support weights and data that are from Pandas.    That is, explicitly coerce `data` and `weights` to numpy arrays.  You could try that and see if it avoids the problem.   I suppose coercing the result of `eval()` might be needed to, in case someone writes a model that returns a Series.

I'm no expert in Pandas, but maybe we need more tests using it.

**Comment by HamishBrownPFR** [comment]
Sorry, I had the examples in a private repo.  I have moved them to a public one now.

https://github.com/PlantandFoodResearch/StonySoilLysimeters/tree/master/CurveError

**Comment by HamishBrownPFR** [comment]
Thanks newville.

You are correct if I convert the panda to an array using np.asarray it works

**Comment by newville** [comment]
@HamishBrownPFR   Now I'm confused.  What is failing for you?   Your code works for me.

I verified that the data types in `Model._residual()` for both `data` and `weights` are panda.Series, and that the calculated `diff` is also a panda.Series.

The current code for `Model._residual()` (see https://github.com/lmfit/lmfit-py/blob/master/lmfit/model.py#L370) is 

```python
    def _residual(self, params, data, weights, **kwargs):
        "default residual:  (data-model)*weights"
        diff = self.eval(params, **kwargs) - data
        if weights is not None:
            diff *= weights
        return np.asarray(diff).ravel()  # for compatibility with pandas.Series
```

that is, a `.ravel()` was added recently to better support mult-dimensional data.  But even if I remove that, your example still works (not surprising, the data is 1-dimensional).   

As a separate point, I don't think your method for weighting is statistically valid. You're doing an unweighted fit, then a subsequent fit using only those points that gave a misfit > 0.01 (so excluding all points with negative residual and all points near the original best-fit).   It definitely skews your second fit.   To me it shows that the weighting does work,  but the results are probably not meaningful. 

Anyway, I can't verify that anything is broken, and can verify that passing pandas.Series in to model fits works.

**Comment by HamishBrownPFR** [comment]
The test in https://github.com/PlantandFoodResearch/StonySoilLysimeters/blob/master/CurveError/Weighting%20error.ipynb
was working when you tried it because it was reading the data in using the pandas read_csv method.  This seamed to fix the problem.

When the data was read in using the pandas read_pickle method the error occured but there was a security concern with pandas so I changed it and this inadvertently fixed the problem.   

I have changed the above example back to reading pandas now if you wish to reproduce the error I was getting.  by converting the data from a panda array to a np array ans suggested (the bottom cell of the example) the problem is resolved.

I know the weighting is not statistically valid, I just wanted a simple example that should show a nice difference.

**Comment by newville** [comment]
@HamishBrownPFR   Um, you mean the example code you posted worked earlier worked for you?  Sorry, I thought you trying to illustrate a problem.

Without having tried your new example, are you certain that reading from CSV and PKL give identical data for your `x` and `y`?    Since pandas.Series can work with lmfit when read from CSV, I'm inclined to believe the problem is with the data in pickle files.   Are pandas.Series even pickle-able?  I would not be surprised if they weren't.    I'm inclined to believe that no changes are needed to lmfit.

**Comment by HamishBrownPFR** [comment]
Series can be pickled.  Have a look at the test.

The first cell reads the data (series from pickle) and fits a function to it which works.  

The second cell calculates some weightings (from the series that were read in from pickles and worked in the first cell) and fails when these are used in the fit.

The third cell converts the weightings series to an array (using np.asarray() as you suggested) and works when the model is fitted.

**Comment by newville** [comment]
@HamishBrownPFR  What I'm suggesting is that the problem is with the un-Pickled pandas.Series.   The code in lmfit where the problem is being seen is:

```python
    diff *= weights 
```

But we know this works fine when `diff` and `weights` being numpy arrays, and also works at least sometimes when `diff` and `weights` are pandas.Series.    When `diff` and `weights` are derived from a mixture of new and un-pickled pandas.Series, it doesn't work.  The error message is actually from pandas, about re-indexing at the request to do augmented assignment.   I'll go out on a limb and make a couple of guesses.

Guess 1:  If you change  `Model._residual` to read
```python
    diff = diff*weights   # was diff *= weights
```
that the fit with weightings and unpickled Series will then work.  That is, we probably could try to work around the problem.   But this would mean the problem really is not in lmfit.

Guess 2:   That you would see the same `ValueError: cannot reindex from a duplicate axis` exception from pandas if you do a `a *= b` without lmfit involved at all, such as:

```python
import numpy as np
import pandas as pd

Y = pd.read_csv('Ydata.csv', header=None)
y1 = Y.ix[:,1].copy()
w1 = pd.Series(np.arange(len(y1)))

# this will almost certainly work
y1 *= w1

# now try that with an unpickled series
y2 = pd.read_pickle('Ydata.pkl')
w2 = pd.Series(np.arange(len(y2)))

# this may fail
y2 *= w2
```

That is, I suspect the problem is really with pandas. Or well, it's probably really with Pickle, which is terribly fragile, and probably means that a "pickle/unpickle"d panda.Series is subtly different from a pandas.Series.
