### ISSUE TITLE
iter_cb should be able to stop minimization / fit

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#241]
The use of iter_cb should be changed to allow the callback function to return (say) `False` to mean "stop fitting".   This would allow complex models and GUIs to easily break out of a fit, without the user diving deep into the code or modifying the objective function.

**Comment by andyfaff** [comment]
I have a PR that's currently stalled on scipy that would stop all the
minimizers when the callback function returns False. It might be worth
pursuing this further.

**Comment by andyfaff** [comment]
The PR I refer to is:
https://github.com/scipy/scipy/pull/4384

**Comment by newville** [comment]
@andyfaff  Thanks.  The off-line conversation that I had today that prompted this really suggests that iter_cb in lmfit should support "abort".   That's not to say there shouldn't be a similar mechanism in scipy.optimize.   The iter_cb for lmfit is going to be different from one for scipy (if for no other reason than be being handed Parameters instead of an array of variables).  

For clarity (and I think it agreement with your PR),  I think the "abort now" signal really belongs in iter_cb and not in the objective function.  As an example, lmfit composite models don't really have an objective function the user has access too, and yet the user may want to abort a fit based on parameter values, number of iterations, etc. 

I do agree with your PR that iter_cb returning `True` should be the signal to abort, not `False`, and  not a user-raised exception.   The default return value is `None`, which is not `True`, but shouldn't cause an abort.   But also, I don't think exceptions make particularly good signals from user to library (rather, their intended to work the other way).   The minimizer already has all the state info it needs (it gave it all to the iter_cb after all!), it just needs a response of "abort" or "continue".   Making the user raise some special purpose exception is too much, I think.

I suppose one could imagine using yield and StopIteration, viewing the iteration as a generator function, but that seems a little too weird for scientific users (including myelf)!

**Comment by tacaswell** [comment]
I like the idea of viewing iteration as a generator, but I have been declared an outlier before.

attn @danielballan I think this is relevant for your version of adaptive scan.

**Comment by newville** [comment]
@tacaswell I think generators and yield would be an interesting way to write a pure-python optimization routine, but that's a little out-of-scope for lmfit.   Anyway, expecting the user to raise an exception or StopIteration to halt a fit seems a little weird to me.

**Comment by danielballan** [comment]
I agree with @newville that there should be a user-facing way to abort fitting that does not involve the user manually raising StopIteration. But at a lower level, I'd like to see where using generators for iteration would lead. Maybe it would lead out of scope for lmfit as a scipy.optimize wrapper, but it would be interesting to take a closer look down that path.

**Comment by tacaswell** [comment]
Sorry I was not clear. Fully agree it is out of the (near term?) scope of lmfit, but that it would be an interesting rabbit hole to explore.
