### ISSUE TITLE
compatibility issue with Ipython4

### ISSUE THREAD

**Issue by stonebig** [lmfit/lmfit-py#246]
hi,

I get this error experementing with Ipython4:
````
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64_build0\python-3.4.3.amd64\lib\site-packages\IPython\html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
````

````python3
python-3.4.3.amd64\lib\site-packages\lmfit\ui\ipy_fitter.py in <module>()
     21 else:
     22     # as of IPython 3.x:
---> 23     from IPython.html.widgets import Dropdown
     24     from IPython.html.widgets import Button
     25     from IPython.html.widgets import Box

ImportError: No module named 'widgets'
````

**Comment by danielballan** [comment]
Yep! Widgets were moved to a separate package, ipywidgets. Will try to get around to fix this soon, but a PR would be welcome.

**Comment by stonebig** [comment]
in process, I forgot to install this package too.

**Comment by stonebig** [comment]
it would be nice to have an intermediate release with the Ipython4 fix.

**Comment by danielballan** [comment]
@newville?

**Comment by newville** [comment]
@danielballan, all:   The many changes over the summer and especially #230 probably require a release of 0.9.0, as the API for `minimize()` changed.   That is, scripts that work in 0.8.3 will not with master.   And I don't mean "some scripts, but not others" -- *all* scripts will be slightly broken.  The fixes are easy and the design is for the good, but it probably requires a version boost and clear documentation.   I've been trying to catch up all the outstanding PRs.  I'm not sure if #226 might be ready to be included in that -- it seems stalled. 
 
The summer has been unusually busy for me, and I'm heading to conference overseas soon and need to focus any surplus attention to that.    The earliest I can hope to do anything with lmfit is in the first week of September, and I would expect "late September" to be a reasonable estimate.  If anyone wants to help out to make that quicker, that would be greatly appreciated.

**Comment by danielballan** [comment]
I think late September is fine. Let's not break anything in haste.

As for IPython 4.0, I think their intention was not to break old APIs. The missing widgets import may be an oversight that they could correct in 4.0.1 in short order. I'll open an issue over there.

**Comment by newville** [comment]
@danielballan  For the IPython 4 vs 3, would it be reasonable to try the imports and print a message of "you need to install the ipywidgets package"?

**Comment by danielballan** [comment]
It looks like IPython already does this. Not sure how the reported error message was created.

**Comment by stonebig** [comment]
![lmfit_msg](https://cloud.githubusercontent.com/assets/4312421/9290515/ddf220f8-4396-11e5-940c-5c979a52e9fd.GIF)

**Comment by danielballan** [comment]
But that's a warning, not like the error reported at the top. Anyway, looks like NotebookFitter is compatible with IPython 4, modulo this admittedly annoying warning message.

**Comment by stonebig** [comment]
yes, I just get it for every package using Ipython. So it's annoyance * 10, until each one releases a simple maintenance fix

**Comment by danielballan** [comment]
A fair complaint. You might appreciate [this workaround](http://stackoverflow.com/questions/9031783/hide-all-warnings-in-ipython), though of course use it at your own risk. :- )
