### ISSUE TITLE
numpy upgrade (1.9.2) broke lmfit import

### ISSUE THREAD

**Issue by sealauren** [lmfit/lmfit-py#248]
I upgraded numpy to version 1.9.2, and suddenly code that has worked for over a year doesn't work anymore.  Using Anaconda dist. of python, Python version 2.7.10.
My input:
---> 11 from lmfit import minimize, Parameters, Parameter, report_fit

Error message:
/Users/lweiss/anaconda/lib/python2.7/site-packages/lmfit/__init__.py in <module>()
     47 from .uncertainties import ufloat, correlated_values
     48 
---> 49 from .ui import Fitter
     50 
     51 ## versioneer code

/Users/lweiss/anaconda/lib/python2.7/site-packages/lmfit/ui/__init__.py in <module>()
     35 
     36 if has_ipython:
---> 37     from .ipy_fitter import NotebookFitter
     38     Fitter = NotebookFitter

/Users/lweiss/anaconda/lib/python2.7/site-packages/lmfit/ui/ipy_fitter.py in <module>()
     21 else:
     22     # as of IPython 3.x:
---> 23     from IPython.html.widgets import Dropdown
     24     from IPython.html.widgets import Button
     25     from IPython.html.widgets import Box

ImportError: cannot import name Dropdown

**Comment by tacaswell** [comment]
I suspect you also updated IPython?

**Comment by newville** [comment]
@sealauren  this is not a problem with numpy, but see #246.   Basically, IPython (very reasonably) decided to break itself, which you can see from the error messages.  Actually, it (IPython) is even worse than that as they believe that an easily suppressed warning message issued once is sufficient explanation of their self-inflicted breakage.   OK, it's all reasonable from their POV, but it is most definitely not a problem in lmfit (except to the extent that we try to support other libraries that are willing and eager to break stuff).

Nevertheless, if you install ipywidgets, things will start working again.

**Comment by danielballan** [comment]
I tripped over one of these too a couple days ago. I thought we had sufficiently insulated ourselves from IPython breakages -- obviously not.

**Comment by sealauren** [comment]
Thank you! ipywidgets installed, problem fixed.
