### ISSUE TITLE
Equation mistake in Documentation- SkewedGaussianModel

### ISSUE THREAD

**Issue by chrisfrohmaier** [lmfit/lmfit-py#252]
Hi,
In the documentation there is a typo in the SkewedGaussianModel:
http://lmfit.github.io/lmfit-py/builtin_models.html#models.SkewedGaussianModel

The argument for the error function should be sqrt(2) in the denominator *not* sqrt(2*pi)
I have checked the code in the file `lmfit/lineshapes.py` and the typo isn't there.

Cheers,
Chris

**Comment by newville** [comment]
@chrisfrohmaier  You are absolutely right -- Thanks!  Fixed in github docs.
