### ISSUE TITLE
tests does not work when run out of the sources tree

### ISSUE THREAD

**Issue by picca** [lmfit/lmfit-py#260]
Before this it was working with 0.8.3

with the reorganisation of the NISt directory it doesn not work anymore.

This is a problem for the pacakging (Debian, Ubuntu...)

I: pybuild base:170: cd /<<BUILDDIR>>/lmfit-py-0.9.1+dfsg/.pybuild/pythonX.Y_2.7/build && python2.7 -m nose
.EEEEEEEEEEEEEEEEEEEEEEEEEEE.............S....S........................................................................................
======================================================================
ERROR: test_NIST_Strd.test_Bennett5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/<<BUILDDIR>>/lmfit-py-0.9.1+dfsg/.pybuild/pythonX.Y_2.7/build/tests/test_NIST_Strd.py", line 186, in test_Bennett5
    return RunNIST_Model('Bennett5')
  File "/<<BUILDDIR>>/lmfit-py-0.9.1+dfsg/.pybuild/pythonX.Y_2.7/build/tests/test_NIST_Strd.py", line 179, in RunNIST_Model
    out1 = NIST_Dataset(model, start='start1', plot=False, verbose=False)
  File "/<<BUILDDIR>>/lmfit-py-0.9.1+dfsg/.pybuild/pythonX.Y_2.7/build/tests/test_NIST_Strd.py", line 77, in NIST_Dataset
    NISTdata = ReadNistData(DataSet)
  File "/<<BUILDDIR>>/lmfit-py-0.9.1+dfsg/.pybuild/pythonX.Y_2.7/build/tests/NISTModels.py", line 147, in ReadNistData
    finp = open(os.path.join(NIST_DIR, "%s.dat" % dataset), 'r')
IOError: [Errno 2] No such file or directory: '/<<BUILDDIR>>/lmfit-py-0.9.1+dfsg/.pybuild/pythonX.Y_2.7/build/tests/../NIST_STRD/Bennett5.dat'

**Comment by newville** [comment]
@picca the folder with the NIST StRD examples was moved from `tests/NIST_STRD` to `NIST_STRD` between these releases.  The code in `tests/NISTModels.py` reads the files from this new folder location (that is, from `../NIST_STRD`).  

Of course, running `python -m nose` or `nosetests` from the toplevel folder or the `tests` folder runs all these tests just fine.

I don't know what `.pybuild` is or anything about how debian packages are built or tested.    But `.pybuild/....` appears to *not* be the top of the source tree.   Perhaps some build script needs updating?

**Comment by picca** [comment]
In fact I downloaded lmfit-py from pypi and it does not contain the NIST_STRD directory.
so it is not possible to run the tests with nose.

pybuild is the software which compiles the python modules on Debian.

**Comment by newville** [comment]
On Oct 10, 2015 1:42 AM, "picca" <notifications@github.com> wrote:
>
> In fact I downloaded lmfit-py from pypi and it does not contain the
NIST_STRD directory.
> so it is not possible to run the tests with nose.
>

Oh, OK, we'll fix that for 0. 9.2 which is probably around a week away.

**Comment by newville** [comment]
this is now fix in the master repo
