### ISSUE TITLE
Bug when model prefix is changed.

### ISSUE THREAD

**Issue by andyfaff** [lmfit/lmfit-py#262]
When making changes to `Model.make_params` I came across the following bug. It's based on `test_change_prefix` in `test_model.py`. It seems that when the prefix is changed the hints aren't updated to account for this.

    >>> from lmfit.models import GaussianModel
    >>> mod = GaussianModel(prefix='b')
    >>> mod.prefix = 'c'
    >>> params = mod.make_params()
    >>> names = params.keys()
    >>> all_begin_with_c = all([n.startswith('c') for n in names])
    >>> all_begin_with_c
    True
    >>> print(params)

    NameError
       <_ast.Module object at 0x108ecfc88>
                  ^^^
    name 'bsigma' is not defined
    ---------------------------------------------------------------------------
    NameError                                 Traceback (most recent call last)
    <ipython-input-4-73ac4b936803> in <module>()
    ----> 1 print(params)

    /Users/anz/miniconda3/envs/dev3/lib/python3.4/reprlib.py in wrapper(self)
         22             repr_running.add(key)
         23             try:
    ---> 24                 result = user_function(self)
         25             finally:
         26                 repr_running.discard(key)

    /Users/anz/miniconda3/envs/dev3/lib/python3.4/collections/__init__.py in __repr__(self)
        200         if not self:
        201             return '%s()' % (self.__class__.__name__,)
    --> 202         return '%s(%r)' % (self.__class__.__name__, list(self.items()))
        203 
        204     def __reduce__(self):

    /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/lmfit/parameter.py in __repr__(self)
        374         if self.name is not None:
        375             s.append("'%s'" % self.name)
    --> 376         sval = repr(self._getval())
        377         if not self.vary and self._expr is None:
        378             sval = "value=%s (fixed)" % (sval)

    /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/lmfit/parameter.py in _getval(self)
        452         if self._expr_ast is not None and self._expr_eval is not None:
        453             self._val = self._expr_eval(self._expr_ast)
    --> 454             check_ast_errors(self._expr_eval)
        455 
        456         if self.min is None:

    /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/lmfit/parameter.py in check_ast_errors(expr_eval)
         19     """check for errors derived from asteval"""
         20     if len(expr_eval.error) > 0:
    ---> 21         expr_eval.raise_exception(None)
         22 
         23 class Parameters(OrderedDict):

    /Users/anz/miniconda3/envs/dev3/lib/python3.4/site-packages/lmfit/asteval.py in raise_exception(self, node, exc, msg, expr, lineno)
        144             except:
        145                 exc = RuntimeError
    --> 146         raise exc(self.error_msg)
        147 
        148 

    NameError: name 'bsigma' is not defined in expr='<_ast.Module object at 0x108ecfc88>'

**Comment by newville** [comment]
@andyfaff I think the test in `test_change_prefix` must not have been good enough.  Actually, as I look at the code, allowing changing the prefix this way:
```python
>>> mod = GaussianModel(prefix='b')
>>> mod.prefix = 'c'
```
looks challenging to get right, and might be a not-quite-small change.     

I'm not sure the real use-case of being able to change a prefix after a model is defined, but  I could be persuaded that supporting this is the right thing to do. 

It would simpler to not allow setting `model.prefix` in this way at all (and so changing the test to check that it raises `AttributeError`).    Would that be acceptable?

**Comment by andyfaff** [comment]
Presumably if the prefix is changed then all the relevant entries in the
asteval.symtable need to be updated, as well as all the `Parameter.expr `.
Could this be done when each parameter name is changed?
Unfortunately I'm only really familiar with minimizer.py and parameter.py,
so I don't know the in's and out's of how model.py works. Presumably the
ability to change prefix is there for a reason?  The lack of noise about
any problems could mean that people either don't change prefix, or they
don't use that constraint?

Unfortunately because I don't know (or use, yet) the `Model` code, I don't
know what's going to be acceptable to the community.  As a stopgap perhaps
the test could be modified to be a knownfail which would indicate to devs
that something needs to be fixed. Would @danballan be the best person to
investigate further?

**Comment by tritemio** [comment]
I think it is reasonable to assume that the prefix can only be set at creation time, and make `mod.prefix` a read-only attribute as @newville suggested.

**Comment by tritemio** [comment]
@andyfaff @newville Looking at the code I realize that the `prefix` setter is used by the `copy()` method. And, indeed, also `copy()` is broken when called with a model with expression constrains (such as the built-in `GaussianModel`) and passing a `prefix` argument.

This actually reminds me of  a legit use case which I personally use: creating a template model with custom constrains, then instantiating multiple copies of the model each with different prefixes. For example you may want to create a custom "peak" model with several constrains and then create a composite model by summing *n* of those peaks.

**Comment by newville** [comment]
@tritemio @andyfaff   Good point that `Model.copy()` is also not going to work.  Actually, it's interesting that `Model.copy` isn't documented.....  do we need this?   
Basically, I think that re-assigning a prefix and expecting constraints to work is going to be very difficult.  Is there a use-case for this?  

> This actually reminds me of a legit use case which I personally use: creating a template model
> with custom constrains, then instantiating multiple copies of the model each with different prefixes.
> For example you may want to create a custom "peak" model with several constrains and then 
> create a composite model by summing n of those peaks.

Well, but don't you assign a prefix on creating the instance of the peak model?  Do you have to assign to `peak.prefix` after creating the peak?    

The essential issue is that built-in constraint expressions (such as "fwhm=2*sigma" for a LorentzianModel(), has to become "l1_fwhm=2*l1_sigma" on 
```python
    peak1 = LorentzianModel(prefix='l1_')
```
but now if you do
```python 
   peak1.prefix='l2_'
```

The expression '2*l1_sigma'  would need to be replaced.   And, well, that re-assignment of the prefix and the expectation that constraint expressions will automatically get updated opens up boxes full cans full of worms.    Like, what if you had another peak `peak2` that had it's `sigma` constrained to be equal to `l1_sigma`.  What if that 2nd peak was named `l2_`?   So, supporting re-assignment of prefixes is definitely Real Work (tm), and invites confusion.

So: why does one need to assign prefixes to Models after they have been created?

**Comment by danielballan** [comment]
+1 for keeping it simply and making prefix immutable

**Comment by tritemio** [comment]
@newville I don't want to be able to change prefix. My use case only involves `copy`. First I create a template model:

```
peak = lm.Model(func)
peak.set_param_hint('center', value=0, min=-1, max=2)
peak.set_param_hint('sigma', value=0.1, min=0.02, max=0.2)
peak.set_param_hint('skewness', value=0, min=-1, max=1)

peak1 = peak.copy(prefix='p1_')
peak2 = peak.copy(prefix='p3_')
peak3 = peak.copy(prefix='p3_')

model = peak1 + peak2 + peak3
```

Do you see my point? I don't want to repeat the constraints.

Maybe we can find a way to have `copy` work (recreating a new model via `__init__`?).

Alternatively I can create a custom model (not tested):

```
class Peak(Model):
    def __init__(self, *args, **kwargs):
        super(Peak, self).__init__(func, *args, **kwargs)
        self.set_param_hint('center', value=0, min=-1, max=2)
        self.set_param_hint('sigma', value=0.1, min=0.02, max=0.2)
        self.set_param_hint('skewness', value=0, min=-1, max=1)

peak1 = Peak(prefix='p1_')
peak2 = Peak(prefix='p3_')
peak3 = Peak(prefix='p3_')

model = peak1 + peak2 + peak3
```

I think the first pattern works better in an interactive session. The second works better for a custom model provided by a library.

**Comment by newville** [comment]
Maybe we should have some way of copying parameter hints from one model to another?

**Comment by tritemio** [comment]
The `copy()` method should do that. I don't see the point of an additional method.

**Comment by newville** [comment]
@tritemio  The `copy()` method does more than just copy the parameter hints from one model to another, it makes a `deepcopy` of the Model and then assigns a new prefix to that copy of another model in a way that is fragile and will fail for at least some cases.

Unless I misunderstand, what you want to do is copy hints from one model to another.   And you want that to be convenient from an interactive session (so, little typing, not creating a class).   You're not really making a compelling case for `Model.copy()`, but a case for "make it easy to copy parameter hints from one model to another".   

If we had a way to copy parameter hints, we could do away with the `copy()` method altogether.   That is part of the goal here -- `copy()` is not documented anyway and fails in important cases.   So, along with making `prefix` immutable, getting rid of `copy()` would simplify several things.

**Comment by tritemio** [comment]
@newville, how would you rewrite the example when `copy` is gone?

```
peak = lm.Model(func)
peak.set_param_hint('center', value=0, min=-1, max=2)
peak.set_param_hint('sigma', value=0.1, min=0.02, max=0.2)
peak.set_param_hint('skewness', value=0, min=-1, max=1)

peak1 = peak.copy(prefix='p1_')
peak2 = peak.copy(prefix='p3_')
peak3 = peak.copy(prefix='p3_')

model = peak1 + peak2 + peak3
```

Instead of using `deepcopy`, `model.copy` can be implemented as constructor for `Model` objects using parameters in self.

**Comment by newville** [comment]
addressed (I think...) in 208871db96689c911e00b9d59dace2de68df3220
