### ISSUE TITLE
confidence interval calculation for weighted data

### ISSUE THREAD

**Issue by tdincer** [lmfit/lmfit-py#276]
out = model.fit(datay, params, weights=we, x=datax)

the line above does not calculate confidence intervals. when the above line is run without weights, the confidence intervals are calculated. how is it possible to calculate confidence intervals when the weights are used?

**Comment by newville** [comment]
@tdincer Short answer: it does. Long answer: Please re-read Contributing.md, use the mailing list, and provide a complete example.
