### ISSUE TITLE
Inconsistency between platforms

### ISSUE THREAD

**Issue by tanderson11** [lmfit/lmfit-py#277]
I was working with the `lmfit` and using the `minimize` function and ran into the following peculiar behaviour.

    from lmfit import minimize, Parameters, Parameter, report_fit
    result = minimize(function, params, args = (x, y))
    report_fit(result.params)
    report_fit(params)

On my installation of `python 2.7.10` (Ubuntu 15.10) with `numpy==1.8.2` and `scipy==0.14.1`, the first `report_fit` worked as expected whereas the second `report_fit` returned the inital values seeded to the parameters.

On another installation of Python (Mac OS X - not sure the exact specifications) both `report_fit` commands produced the same output. 

I may have missed something silly, but thought it was worth reporting.

**Comment by newville** [comment]
@tanderson11 this is almost certainly due to different versions of lmfit, with your Ubuntu 15.10 / Python 2.7.10 system using lmfit version 0.9.0 or later, and the other using 0.8.3 or earlier.  

See http://lmfit.github.io/lmfit-py/whatsnew.html#whatsnew-090-label

**Comment by tanderson11** [comment]
Okay, thank you. I will be in touch with the other user.
