### ISSUE TITLE
random sampling within bounds to get initial good guess

### ISSUE THREAD

**Issue by rbf22** [lmfit/lmfit-py#283]
Hi,

I use the lmfit code quite a bit. I often wish there was a way to sample randomly select values from within the bounds for each parameter and then calculate the fit score for these, then return the best random parameters in the model object. It would be great if this could be added in some form as it would be a very good way to get initial guesses for parameters. Is there a way to do this in the current code?

Thanks for all the great work,

Bryn

**Comment by newville** [comment]
@rbf22 See also #55 for a wish to do the same thing, but over a uniform grid, not randomly sample.
I agree -- these would be great additions.   

This doesn't seem that challenging to implement to me, and would make a great contribution.  PRs welcome!

**Comment by andyfaff** [comment]
There is currently a way (I think) to do the random sampling, but not the uniform sampling. The initialisation for for `scipy.optimize.differential_evolution` uses either random sampling or latin-hypersquare sampling. If the this function is given `maxiter=0` then the fittest member of the differential evolution population is still identified.  The default of the `differential_evolution` code is then to polish that result using LBFGSB.
It should be possible to set `maxiter=0` from `lmfit.Minimizer.minimize`. However, there have to be lower and upper bounds for all the parameters.

**Comment by newville** [comment]
I think that the `brute` method addresses this.
