### ISSUE TITLE
how do I suppress the print of “Adding parameter” in lmfit

### ISSUE THREAD

**Issue by orena1** [lmfit/lmfit-py#288]
How do I suppress the printing of "Adding parameter" in the following code
```
In [7]: from numpy import sqrt, pi, exp, linspace 
In [8]: import numpy as np    
In [9]: def gaussian(x, amp, cen, wid):
   ...:        return amp * exp(-(x-cen)**2 /wid)
   ...: x = linspace(-10,10)
   ...: y = gaussian(x, 2.33, 0.21, 1.51) + np.random.normal(0, 0.2, len(x))
   ...: 

In [10]: from lmfit import Model
In [11]: gmod = Model(gaussian)
In [12]: result = gmod.fit(y, x=x, amp=5, cen=5, wid=1)#<-- here!!
 - Adding parameter "amp"
 - Adding parameter "cen"
 - Adding parameter "wid"
```
I also wrote a question in stackoverflow but did not received an answer
http://stackoverflow.com/questions/34488763/how-do-i-suppress-the-print-of-adding-parameter-in-lmfit?noredirect=1#comment56719846_34488763

**Comment by newville** [comment]
@orena1   I think you shouldn't see those messages in the latest version, but doing 

`fit(..., verbose=False)` 

should suppress them in older versions.

Please read https://github.com/lmfit/lmfit-py/blob/master/Contributing.md  (as you were instructed to do when posting this Issue but apparently did not notice) and use the mailing list for future questions.   

I sometimes look at stackoverflow.com, but I don't subscribe to it.  We have a dedicated support forum as a mailing list.
