### ISSUE TITLE
Data type problem in version 0.9.2

### ISSUE THREAD

**Issue by idelw** [lmfit/lmfit-py#289]
In version 0.9.2, the fitting routine fixes some of my parameters to integer values, even tough I define them with float() in fit_params.add 

The literally identical script runs fine in version 0.8.3, so I am wondering whether there is a bug or something about data types changed in the new version.

Thanks.

**Comment by newville** [comment]
@idelw That seems strange to me, and the latest version certainly passes all its tests, and definitely is not coercing parameter values to be integers for any case I've seen.

Of course, we could give a much more useful response if you posted an example.  Also,
please read https://github.com/lmfit/lmfit-py/blob/master/Contributing.md and use the mailing list for questions about lmfit.
