### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by rayosborn** [lmfit/lmfit-py#291]
We embedded lmfit into the NeXpy GUI (http://nexpy.github.io/nexpy/), with some refactoring to allow us to assign parameters to function objects, allowing for example multiple Gaussians, etc. I gather that has now been added to v0.9, but I haven't had time to look into that yet. However, I am trying to make sure that NeXpy is compatible with v0.9.3, by taking fitted parameters from the new MinimizerResult object. However, I now find that the result.params object always contains the initial parameters, i.e., not fit has been done. I am hoping someone can tell me what other changes might be causing this, because v0.8.3 still works. 

The relevant NeXpy code is (mostly within a class, which isn't shown):

    from lmfit import minimize, Parameters, __version__

    def residuals(self, parameters):
        if self.e is not None:
             return (self.y - self.get_model()) / self.e
        else:
            return self.y - self.get_model()

    def fit_data(self):
        """Run a scipy leastsq regression"""
        self.parameters = Parameters()
        for f in self.functions:
            for p in f.parameters:
                p.original_name = p.name
                self.parameters[f.name+p.name] = p
                if p.value is None:
                    p.value = 1.0
        self.result = minimize(self.residuals, self.parameters)
        for f in self.functions:
            for p in f.parameters:
                if __version__ > '0.8.3':
                    p.init_value = p.value
                    p.value = self.result.params[p.name].value
                p.name = p.original_name

Do I need to do add any extra parameters to the minimize function? I have tried running through the process in a debugger, but I couldn't see why it wasn't doing any minimizing.

**Comment by rayosborn** [comment]
I think I've fixed this. My code had assumed that the self.parameters dictionary always contained the original Parameter objects, whose values are no longer changed by the minimize function. I have to explicitly copy the parameters over:

    def residuals(self, parameters):
        if __version__ > '0.8.3':
            for parameter in parameters:
                self.parameters[parameter].value = parameters[parameter].value
        if self.e is not None:
             return (self.y - self.get_model()) / self.e
        else:
            return self.y - self.get_model()

    def fit_data(self):
        """Run a scipy leastsq regression"""
        self.parameters = Parameters()
        for f in self.functions:
            for p in f.parameters:
                p.original_name = p.name
                self.parameters[f.name+p.name] = p
                if p.value is None:
                    p.value = 1.0
        self.result = minimize(self.residuals, self.parameters)
        if __version__ > '0.8.3':
            for parameter in self.parameters:
                self.parameters[parameter].value = self.result.params[parameter].value
        for f in self.functions:
            for p in f.parameters:
                p.name = p.original_name

I'll leave the issue open until tomorrow evening in case anyone else wants to comment, before closing it.

**Comment by newville** [comment]
@rayosborn  Hi Ray,  Yes this was a deliberate change for 0.9, though we knew it break backward compatibility and cause confusion.  

Basically, with the old way, the Parameters passed to minimize() were mutated, so that the user would have to keep a copy of the original values between successive fits.

In 0.9 and later, the Parameters passed in to minimize() are left unchanged, and the refined parameters are returned in the Result (result.params).   This makes it easier to do and compare successive fits, say with changes in bounds.

**Comment by rayosborn** [comment]
It's always hazardous incorporating other code into your own project, but this was not too hard to fix.

**Comment by newville** [comment]
@rayosborn  Yes, very sorry we broke the API on this.

**Comment by rayosborn** [comment]
No need to apologize. Open source projects have to evolve, and lmfit has been a very useful component in NeXpy.
