### ISSUE TITLE
scalar_minimize cannot handle 1 variable

### ISSUE THREAD

**Issue by woutergins** [lmfit/lmfit-py#292]
Using the scalar_minimization methods when there is only one variable leads to unexpected behaviour. At some point, in `self.__residual` the passed `fvars` changes from a `(1,)` numpy array to a `()` array, raising an error when trying to iterate over this.
A temporary fix is including `fvars = np.atleast_1d(fvars)` before the for-loop, but this might be a monkey patch, I did not follow the path the fvars takes to see where it might go wrong.

**Comment by newville** [comment]
should be addressed with a8cbeb5978de84332bb92dd5f446e494c023f272
