### ISSUE TITLE
Built-in model - how to limit number of function calls?

### ISSUE THREAD

**Issue by benshep** [lmfit/lmfit-py#299]
I'm trying to fit a function to a Gaussian. This works fine for valid data (with about 20 function calls, and much faster than scipy.optimize.curve_fit), but for invalid data it returns garbage after 8000 calls. This is slowing down my data processing massively. How can I pass a "maximum_function_evaluations" parameter to the model? I couldn't see anything in the docs. (I've tried adding a callback function and returning True to abort the fit, but this seems to have no effect.)

I _think_ I am using version 0.9.2, but it may be 0.8.3.

**Comment by newville** [comment]
@benshep You read Contributing.md, right?    It says to read this right there at the top when you create a new issue.    Read the docs, use the mailing list.
