### ISSUE TITLE
conf_interval fails when fit was done with bounded/linked parameters.

### ISSUE THREAD

**Issue by wakass** [lmfit/lmfit-py#308]
## Submitting an Issue
#
# 0. If you have not submitted an issue to LMFIT before, you
#    *MUST* read
#    https://github.com/lmfit/lmfit-py/blob/master/.github/Contributing.md
#    Do *NOT* submit an Issue without reading this. Use the Mailing list
#    https://groups.google.com/group/lmfit-py for questions about LMFIT.
#
# 1. Include an example that shows the Issue or explain why you did not.
#    It is OK to use gist or give a link to examples or data.
#    It is OK to use or point to Jupyter notebooks.

The following script:
import numpy as np
from numpy import sqrt,pi,exp,arange
import matplotlib.pyplot as plt
import lmfit as lm

def gaussian(x, amp, cen, wid):
    "1-d gaussian: gaussian(x, amp, cen, wid)"
    return (amp/(sqrt(2*pi)*wid)) * exp(-(x-cen)**2 /(2*wid**2))

def n_gaussians(x,pars,n_peaks=1):
    total = 0.
    for i in np.arange(n_peaks)+1:
        a = pars['amp_%d'%i].value
        w = pars['wid_%d'%i].value
        c = pars['cen_%d'%i].value
        total = total + gaussian(x,a,c,w)
    return total

def resid(pars,x, data=None,eps=None,model=n_gaussians,**kwargs):    
    model = model(x,pars,**kwargs)

    if data is None:
        resid = model
    else:
        resid = model - data 
    return resid

y = np.load('linecut.dat.npy')*1e4
x = np.linspace(0,3.,y.shape[0])

n_peaks = 4

p= lm.Parameters()
p.add_many( ('amp_1',  4.0, True,0.5, 6.,None),
            ('cen_1', 0.7, True, 0, .85,  None),
            ('wid_1', 0.11875854684504183, False, None, None,  None),

            ('amp_2',  None, False, None, None,'amp_1'),
            ('cen_2', .9, True, .85, 1.4,  None),
            ('wid_2', None, False, None, None,  'wid_1'),

            ('amp_3',  4.0, True,0.5, 6.,None),
            ('cen_3', 1.1, True, .95, 1.5,  None),
            ('wid_3', 0.24352453256655024 , True, 0.1, .3,  None),

            ('amp_4',  None,False,None,None,'amp_3'),
            ('cen_4', 1.7, True, 1.6, 2.5,  None),
            ('wid_4', 0.24352453256655024 , True, 0.1, .3,  None),
           )

model = n_gaussians
gmod = lm.Minimizer(resid, p, fcn_args=(x,), fcn_kws={'data':y,'model':model,'n_peaks':n_peaks} )
gmod.prepare_fit()
init = resid(p,x,n_peaks=n_peaks)
result  = gmod.minimize(method='nelder')
result  = gmod.minimize(method='leastsq',params=result.params)

try:
    ci =  lm.conf_interval(gmod,result)
    lm.printfuncs.report_ci(ci)
except Exception as e:
    print e
print lm.fit_report(result)

plt.figure()
plt.plot(x, y,      'bo')
plt.plot(x, init,   'k--')
plt.plot(x, resid(result.params,x,n_peaks=n_peaks), 'r-')

colors=['r','g','b','k']
for n,i in enumerate(arange(n_peaks)+1):
    vals = result.params.valuesdict()
    a   = vals['amp_%d'%i]
    wid = vals['wid_%d'%i]
    c   = vals['cen_%d'%i]

    plt.plot(x, gaussian(x,
                        p['amp_%d'%i].value,
                        p['cen_%d'%i].value,
                        p['wid_%d'%i].value),
                        'k--')
    plt.plot(x,gaussian(x,a,c,wid),colors[n]+'-',linewidth=5)
plt.show()

fails when conf_interval is called with "AttributeError: 'float' object has no attribute 'copy'" Likely to do with fitting to a model using bounded/linked parameters.
File linecut.dat.npy, used in the example, can be found [here](https://drive.google.com/open?id=0B-eFQ1Fesl5TZXFPZmp0aDBpT3c
)

### full traceback ####

AttributeError                            Traceback (most recent call last)
<ipython-input-2-2fd095edcd5a> in <module>()
     96 
     97 # try:
---> 98 ci =  lm.conf_interval(gmod,result)
     99 lm.printfuncs.report_ci(ci)
    100 # except Exception as e:

/usr/local/lib/python2.7/site-packages/lmfit/confidence.pyc in conf_interval(minimizer, result, p_names, sigmas, trace, maxiter, verbose, prob_func)
    124     ci = ConfidenceInterval(minimizer, result, p_names, prob_func, sigmas,
    125                             trace, verbose, maxiter)
--> 126     output = ci.calc_all_ci()
    127     if trace:
    128         return output, ci.trace_dict

/usr/local/lib/python2.7/site-packages/lmfit/confidence.pyc in calc_all_ci(self)
    200         for p in self.p_names:
    201             out[p] = (self.calc_ci(p, -1)[::-1] +
--> 202                       [(0., self.params[p].value)] +
    203                       self.calc_ci(p, 1))
    204         if self.trace:

/usr/local/lib/python2.7/site-packages/lmfit/confidence.pyc in calc_ci(self, para, direction)
    225         para.vary = False
    226         limit, max_prob = self.find_limit(para, direction)
--> 227         start_val = para.value.copy()
    228         a_limit = start_val.copy()
    229         ret = []

AttributeError: 'float' object has no attribute 'copy'

**Comment by newville** [comment]
@wakass Thanks -- I can also see the template need some formatting work!  

I think changing to 
```Python
 # start_val = para.value.copy()
 # a_limit = start_val.copy()
 start_val = float(para.value)
 a_limit = start_val
```
should work.

**Comment by wakass** [comment]
Cool! At least this seems to resolve the error for me. I would like to note though, that the calculation time was excessively long (at least 10-20 minutes). I do not know if it has anything to do with my particular model, or if this expected for bounded problem. I seem to recall some fitting situations where the ci calculation was way faster..
