### ISSUE TITLE
formatting of issue template is too ugly

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#309]
###  Submitting an Issue:.

If you have not submitted an issue to LMFIT before, you *MUST* read https://github.com/lmfit/lmfit-py/blob/master/.github/Contributing.md   Do *NOT* submit an Issue without reading this. Use the Mailing list  https://groups.google.com/group/lmfit-py for questions about LMFIT.

### Include an example that shows the Issue or explain why you did not.  

It is OK to use gist or give a link to examples or data. It is OK to use or point to Jupyter notebooks.

**Comment by Tillsten** [comment]
True dat.

**Comment by newville** [comment]
fixed, or at least better.
