### ISSUE TITLE
Undefined name 'long' in parameter.py

### ISSUE THREAD

**Issue by tritemio** [lmfit/lmfit-py#319]
It may be a false positive, but my linter signals an error about using `long()` which is undefined on python3 in:

https://github.com/lmfit/lmfit-py/blob/0.9.3rc2/lmfit/parameter.py#L680

**Comment by newville** [comment]
@tritemio Good point.  I wonder if there is something in `six` to handle this.... I didn't see it immediately.

**Comment by tritemio** [comment]
Using the future package (which we already use) we could do:

```
# Python 2 and 3
from builtins import int
bigint = int(1)
```

http://python-future.org/compatible_idioms.html?highlight=long#long-integers

**Comment by andyfaff** [comment]
six is vendored in scipy, so we know it's going to be installed.

**Comment by tritemio** [comment]
Right, but future is already a dependence and results in more pythonic (i.e. python-3-like) code.

**Comment by newville** [comment]
@tritemio using `builtins.int` looks like a good solution.  Are you willing to make a PR?

**Comment by tritemio** [comment]
@newville I can make a PR. I don't know what is the `__long__` method used for? Apparently is never called because we never had a problem so far.

**Comment by newville** [comment]
@tritemio Yeah, we could just remove this method.

**Comment by newville** [comment]
completed
