### ISSUE TITLE
Parameter could / should have __array__() method

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#323]
The discussions of #319, #321, #322 reminded me of the original motivation for `Parameter.__float__()`, which is that
```python
>>> p  = Parameter('x', 3.9)
>>> float(p)
3.9
>>> p + 1
4.9
```

but unfortunately,  
```python
>>> import numpy as np
>>> np.linspace(-1, 1, 101)*p
```
is an "object array", and so essentially useless.

**But**:  I believe that if `Parameter` has an `__array__()` method, simply

```python 
    def __array__(self):
         return np.array(float(self._getval()))
```

Then this will work to give a proper ndarray.  

That would mean that all the examples and uses would be able to drop the explicit access of the `.value` attribute, so that 
```python
def fcn2min(params, x, data):
    """ model decaying sine wave, subtract data"""
    amp = params['amp'].value
    shift = params['shift'].value
    omega = params['omega'].value
    decay = params['decay'].value

    model = amp * np.sin(x * omega + shift) * np.exp(-x*x*decay)
    return model - data
```
could become (for example)

```python
def fcn2min(params, x, data):
    """ model decaying sine wave, subtract data"""
    shift = params['shift'] 
    omega = params['omega'] 
    decay = params['decay']

    model = params['amp'] * np.sin(x * omega + shift) * np.exp(-x*x*decay)
    return model - data
```

which seems much nicer to me...  I have not tested this in any detail.  Any objections to pursuing this idea?

**Comment by tritemio** [comment]
+1

**Comment by andyfaff** [comment]
Can one do this for `Parameters` objects? e.g. instead of

    params = np.array([parameters[param].value for param in parameters],
float)

could you do (or something like it):

    params = np.array(parameters)

**Comment by newville** [comment]
@andyfaff  I'm not 100% sure, but I think this might be possible.  Of course, that removes the dictionary-ness, but sometimes that's OK.

**Comment by andyfaff** [comment]
>
> The dict-ness is still there if you want it, but it might  be a clean way
to extract all the numerical parameter values into an array.
The array form is very useful as well, a lot of peoples cost functions
would have originally been programmed in this way becasue that's the form
that the scipy minimizers accept.

**Comment by newville** [comment]
@andyfaff  Yeah, I understand, though (perhaps unsurprisingly) I think it would be better if the scipy minimizers had a better data structure for parameter values than a simple array -- the order actually has no inherent meaning.

Then again, it's only a one-liner, so I think there is no reason to not add this (assuming it can be done for an OrderedDict).

**Comment by newville** [comment]
closing
