### ISSUE TITLE
maxfev and maxiter should be supported for all methods, and uniformly

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#332]
Currently, one can set `maxfev` for the leastsq method with

``` python
result = minimize(fcn2min, params, args=(x, data), maxfev=20)
```

but when using a scalar minimizer, one has to do

``` python
mini = Minimizer(fcn2min, params, fcn_args=(x, data))
result = mini.scalar_minimize(method='Nelder-Mead', options={'maxiter': 150})
```

which is inconsistent and should be made more consistent. 

My preference would be to support either `maxfev` or `maxiter` as equivalent, and support this for all methods in `minimize()`.

I believe there may be similar issues with `tol` and `xtol` (which most scalar minimizers support).

**Comment by tritemio** [comment]
+1

**Comment by newville** [comment]
@uvainio Please do not hijack github Issues with questions about lmfit.   We have a mailing list for support and use github Issues for actual issues with the code and docs.   This is described many places in the docs and github pages.

It is possible to specify `maxfev` for Model.fit, as with
```
my_model.fit(ydata, params, xdata=x, fit_kws={'maxfev': 200})
```

**Comment by uvainio** [comment]
Hi Matt,

Many thanks for the very informative answer, and sorry for misusing guthub. Again one step closer to learning how to use it correclty!

**Comment by luriomer** [comment]
Are there any news about this issue? I highly support this, since I have wrappers around LMFIT and this can easily simplify things.

**Comment by newville** [comment]
@luriomer  I guess this sort of got lost.  Just to be clear, the inconsistency is in `scipy`, and the question here is how much we try to "smooth out" the inconsistencies and poor API choices in scipy versus being a "thin wrapper".   <insert rant about scipy.optimize inconsistencies and poor API here>.

Anyway, I  guess I would suggest we standardize on "maxfev" as "maximum number of function evaluations", partly because that is easy to count and partly because "iteration" is not a well-defined (or consistently defined) concept.

PR welcome for that....

**Comment by luriomer** [comment]
Yes, I understand. I have to do it on my end anyway so I hope I'll have also time to file a PR soon.

Best

**Comment by luriomer** [comment]
Correct me if I'm wrong, but this issue is a bit bigger than `maxfev` vs. `maxiter`. As I understand, `Minimizer.minimize(method="leastsq",params=...)` and `Minimizer.leastsq(params=...)` do the same thing, which makes it hard to correctly wrap all of the desired parameters in a consistent way. 
For more complicated minimizers, like `basinhoppping`, we have more complicated kws structure, because `scipy.optimize` requires something like `{"minimizer_kwargs":{"method":"L-BFGS-B","args":(maxfev,...)}}`. Maybe we should try to smooth this wrapping as well?

**Comment by newville** [comment]
@luriomer   Yeah,  trying to smooth out those messy wrappings would be my preference too.  I think we would probably want to do something like adding a `max_evaluations` argument to the `lmfit` methods that then writes to `maxfev/maxiter`  as appropriate (and then not requiring the user to use `minimizer_kwargs`). 

A slightly more involved (but probably better) approach would be to take the value the user passes into the `lmfit` function as `max_evaluations`, and send 2x that value to the underlying methods `maxfev/maxiter` argument and then explicitly count the number of function evaluations in `Minimizer._resid()`, signaling an abort when that exceeds `max_evaluations`.   We're already signaling aborts there for other reasons....

This would help limit the need for the user to directly access the underlying `scipy.optimize` routines: when the user needs `minimizer_kwargs`, we're doing something wrong ;).

Yes, this could be some work.  I think `max_evaluations` would be the most-used of these options, followed by some way of saying "fitting tolerance".

Does that seem reasonable (and maybe more manageable) to you?

**Comment by luriomer** [comment]
@newville Yes, it sounds great. Although it might be good to allow easy access to `minimizer_kwargs` as well, if needed. For example, I wanted to test the performance of different algorithms when used as local minimizers for `basinhopping`. My minimized function needed a lot of iterations since its sensitivity to some of the variable parameters is low. I wanted to specify `maxfev`/`maxiter`/`ftol` to not wait too much time for just comparing between several options.

I do think that we first need to look for kinds of inconsistencies, to avoid doing this integration multiple times. Is there someting else inconsistent between LMFIT and scipy.optimize, besides `minimizer_kwargs`?

**Comment by luriomer** [comment]
@newville Well, yes and no. In usual cases you are correct, those three control parameters are enough. But I can think of special cases when more control is needed. I return to the example I presented before: if you are trying to **globally** fit a very low-sloped function (i.e relatively low sensitivity to some or all of the parameters) then you might also need to control the `tolerance`/`ftol`/`gtol` or whatever of each **local** optimization, or else you might get into a situation where each local optimization runs forever.

**Comment by newville** [comment]
@luriomer Sorry, maybe I don't understand.  "Yes and no" to what?  

Yep, the user may want to specify a fitting tolerance.  I think that's what we both said.   Is there a difference in tolerance for global and local optimizers?

**Comment by luriomer** [comment]
@newville  "Yes and no" referred to whether `max_evaluations` is sufficient for controlling a global optimizer, by predefining  `C`\cdot`max_evaluations` to be passed to the local optimizer, where C is some constant. I'd think that the manner of sufficiency will be highly dependent on how your minimized function behaves, doesn't it?
Maybe we can let the user control `C`, and assign a default value of 2 to it or something. Does that seem reasonable to you?

**Comment by luriomer** [comment]
Anyway, it's important to emphasize that even without regarding this issue, we should have only one way of calling a fit. I don't see much point of having both `Minimizer.minimize(method=X)` and `Minimizer.X` with `X` being `least`,`brute`,`scalar_minimize` or whatever. For me, the _fitting_ section in the docs is quite confusing due to this redundancy.

**Comment by newville** [comment]
@luriomer You mean to say that "c" should be different from 1 for a global optimizer?  Um, why?  If the user sets `max_evaluations` wouldn't that mean "don't do any more function evaluations"?

Yeah, if one is using one of the global optimizers, they're probably going to need a lot of function evaluations.

**Comment by newville** [comment]
@lumiomer
> Anyway, it's important to emphasize that even without regarding this issue, we should have only one way of calling a fit. I don't see much point of having both Minimizer.minimize(method=X) and Minimizer.X with X being least,brute,scalar_minimize or whatever. For me, the fitting section in the docs is quite confusing due to this redundancy.

Really?  Is it the redundancy itself that is confusing you?   Why do you think there should be only one way of calling a fit?  We deliberately have multiple approaches to fitting, including a Model class that takes up a large fraction of the code, doc, examples, and bandwidth.   We're not going to change that. 

Lots of people will use the `Model` class.  Many people will be able to use `minimize()` without creating their own instance of `Minimizer`.  I'm pretty sure we're going to keep that.

**Comment by luriomer** [comment]
@newville 

> You mean to say that "c" should be different from 1 for a global optimizer? Um, why? If the user sets max_evaluations wouldn't that mean "don't do any more function evaluations"?

I am not referring to just `max_evaluations`, but also on how it is divided between the local and global minimizers. Earlier, you said that `c=2` is a good candidate:

> A slightly more involved (but probably better) approach would be to take the value the user passes into the lmfit function as max_evaluations, and send 2x that value to the underlying methods maxfev/maxiter argument and then explicitly count the number of function evaluations in Minimizer._resid(), signaling an abort when that exceeds max_evaluations. We're already signaling aborts there for other reasons....

You can have the exact same number of `max_evaluations` with different values for `c`, producing in general very different results. For `max_evaluations=5` you can have one global step with 5 local evaluations or vica-verse, which is of course two completely different scenarios.
If you let the user access `c` (with a default value of let's say 2) then it's possible to control the behaviour of both minimizers. All I'm saying is that the best value for `c` can be problem-related and it's good to have external access to it, if needed.

>  We deliberately have multiple approaches to fitting, including a Model class that takes up a large fraction of the code, doc, examples, and bandwidth.

I think that the `Model` class is a very good 2nd-level wrapper because it allows you to avoid defining the cost function all over again when using common ones. For this reason, I don't think it is redundant. On the other hand, having both `Minimizer.minimize(method)` and `Minimizer.method` is a redundancy because they both do the same thing with the same amount of effort from the user, with very little syntax difference. Anyway, this is nothing but my personal opinion.

**Comment by newville** [comment]
> @newville <https://github.com/newville>
>
> You mean to say that "c" should be different from 1 for a global
> optimizer? Um, why? If the user sets max_evaluations wouldn't that mean
> "don't do any more function evaluations"?
>
> I am not referring to just max_evaluations, but also on how it is divided
> between the local and global minimizers. Earlier, you said that c=2 is a
> good candidate:
>
> A slightly more involved (but probably better) approach would be to take
> the value the user passes into the lmfit function as max_evaluations, and
> send 2x that value to the underlying methods maxfev/maxiter argument and
> then explicitly count the number of function evaluations in
> Minimizer._resid(), signaling an abort when that exceeds max_evaluations.
> We're already signaling aborts there for other reasons....
>
>
I meant to send a value of `maxfev` or maxiter` to the corresponding
scipy.optimize method that is much higher than the actual value the user
wants so that those methods will NOT raise a "too many evaluations" error.
And then, handle the counting (we already do) and checking of how many
function evaluations there have been in `Minimizer.__resid()`, aborting the
fit if the user-supplied value is exceeded.  "2x" is an easy way to do that.

You can have the exact same number of max_evaluations with different values
> for c, producing in general very different results. For max_evaluations=5
> you can have one global step with 5 local evaluations or vica-verse, which
> is of course two completely different scenarios.
> If you let the user access c (with a default value of let's say 2) then
> it's possible to control the behaviour of both minimizers. All I'm saying
> is that the best value for c can be problem-related and it's good to have
> external access to it, if needed.
>

If the optimizer is going to use multiprocessing, the user should know that
and if they set `max_evaluations`, they should take that into account.
That is "number of evaluation" *is* the proper quantity for the user to
care about, and better than "evaluations per worker" or "evaluations per
process" or however else the method is going to farm out work.  And, yes,
handling those cases will be work.

We deliberately have multiple approaches to fitting, including a Model
> class that takes up a large fraction of the code, doc, examples, and
> bandwidth.
>
> I think that the Model class is a very good 2nd-level wrapper because it
> allows you to avoid defining the cost function all over again when using
> common ones. For this reason, I don't think it is redundant. On the other
> hand, having both Minimizer.minimize(method) and Minimizer.method is a
> redundancy because they both do the same thing with the same amount of
> effort from the user, with very little syntax difference. Anyway, this is
> nothing but my personal opinion.
>

In case your unaware (sorry, but it's hard for me to tell), the minimize()
function is a thin wrapper function around the `Minimizer` class that is in
total, without docstrings:

    def minimize(fcn, params, method='leastsq', args=None, kws=None,
iter_cb=None,
                 scale_covar=True, nan_policy='raise', reduce_fcn=None,
                 calc_covar=True, **fit_kws):
        fitter = Minimizer(fcn, params, fcn_args=args, fcn_kws=kws,
                           iter_cb=iter_cb, scale_covar=scale_covar,
                           nan_policy=nan_policy, reduce_fcn=reduce_fcn,
                           calc_covar=calc_covar, **fit_kws)
        return fitter.minimize(method=method)

There are definitely cases where the user may need the `Minimizer`
instance, but there are many cases where they do not.  Within the scipy
world, there is a general preference for procedural interfaces (plain
functions over having the user create instances of classes that will be
used exactly once).  Note that code where a user does create a class
instance (`lmfit.Model`, much of scikit-learn)  usually means using that
instance a few times.

We won't be removing this simple, working, documented, and long-standing
function any time soon.

**Comment by luriomer** [comment]
@newville Okay, in this case I accept all of the above.

**Comment by newville** [comment]
should now be fixed in master
