### ISSUE TITLE
Evaluating a model at a scalar value raises error

### ISSUE THREAD

**Issue by gitj** [lmfit/lmfit-py#333]
Trying to execute lmfit.model.Model.eval(x=100.,....) runs into a problem at this line:
https://github.com/lmfit/lmfit-py/blob/master/lmfit/model.py#L412

`    # Handle special case of constant result and one
     # independent variable (of any dimension).
     if np.ndim(result) == 0 and len(self.independent_vars) == 1:
          result = np.tile(result, kwargs[self.independent_vars[0]].shape)`

Since kwargs[self.independent_vars[0]] is a scalar, it has no .shape attribute. There needs to be a check for this case.

**Comment by newville** [comment]
OK, fixed with #342
