### ISSUE TITLE
Deprecating python 2.6?

### ISSUE THREAD

**Issue by ericdill** [lmfit/lmfit-py#334]
Python 2.6 is no longer part of the automated test suite in lmfit.  It seems to still sort of be supported since `ordereddict` is being vendored which is only needed for python 2.6.  Are there plans to officially remove py26 support from lmfit at any point?

**Comment by newville** [comment]
@ericdill I don't have a strong preference.  I think there aren't many folks who need to use Py26.   If "OrderedDict" is the only known thing that wouldn;t work on Py26, I don't see the harm in keeping it.  I suspect that more incompatibilities may creep in, if they haven't already. 

I think a deprecation warning in the next version saying that support will be dropped in the following version would be OK.   Do you agree?

**Comment by ericdill** [comment]
> I think a deprecation warning in the next version saying that support will be dropped in the following version would be OK.

That seems quite reasonable.  Another good reason to drop python 2.6 is that you can only use dict comprehensions with py2.7+

**Comment by newville** [comment]
closing
