### ISSUE TITLE
Allow user to pass x-axis and y-axis plot labels in ModelResult.plot

### ISSUE THREAD

**Issue by ampolloreno** [lmfit/lmfit-py#339]
I would like to be able to pass in optional parameters xlabel and ylabel to ModelResult.plot and them appear on the plot, as expressed below:

from lmfit import model
import numpy as np

def gaussian(x, amp, cen, wid):
    return amp * np.exp(-(x-cen)**2 /wid)

gmod = model.Model(gaussian)
params = gmod.make_params(cen=5, amp=200, wid=1)
x = np.linspace(0, 10, 201)
y = gmod.eval(x=x, amp=10, cen=6.2, wid=0.75)
result = gmod.fit(y, x=x, amp=5, cen=5, wid=1)
result.plot(xlabel="Frequency(Hz)", ylabel = "Amplitude")
plt.show()

**Comment by newville** [comment]
I think this can be closed.  Please let me know if not.
