### ISSUE TITLE
use napoleon-style docstrings uniformly, use autodoc tools in documentation

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#354]
We should move to using autodoc tools and napoleon-style docstrings uniformly.

**Comment by andyfaff** [comment]
What are napoleon-style docstrings?

**Comment by tritemio** [comment]
I also like the napoleon docstring style and use it in my projects. However for lmfit, I think it is more appropriate to stick with the numpy style. Most of the docstring are already in this style anyway.

We also have to decide on a package-level syntax for the `currentmodule` directive. Normally I use the directive as:

```
..currentmodule:: lmfit.minimizer
```

and create a link to a function using:

```
:func:`minimize`
```

If we change the directive to 

```
..currentmodule:: minimizer
```

the link is not created anymore and I don't know if there is an alternative syntax that works in this case.

@andyfaff mentioned that the former syntax result in intersphinx links as:

```
lmfit::lmfit.minimize
```

while with the latter, the links would become a shorter version:

```
lmfit::minimize
```

**Comment by newville** [comment]
@andyfaff https://sphinxcontrib-napoleon.readthedocs.io/en/latest/   These are much better to read as plain text and much easier to write.   

Personally, I don't see a lot of value in following numpy's convention. The docstrings should be as clear and complete as possible, should be readable as plain text, and work well with sphinx's autodoc.    I think the napoleon style wins for this.   Fortunately, changing numpy doc style to napoleon is mostly removing no-longer-needed markup.

The main issue I have with `currrentmodule` is that for me (using sphinx 1.4.1) it does not fully work.  Using (in paramters.rst):

``` 
.. currentmodule:: parameter
```

fails due to relative imports:

```
/Users/Newville/Codes/lmfit-py/doc/parameters.rst:177: WARNING: autodoc: failed to import method u'Parameters.pretty_print' from module u'parameter'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/Newville/anaconda/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/ext/autodoc.py", line 507, in import_object
    __import__(self.modname)
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 13, in <module>
    from . import uncertainties
ValueError: Attempted relative import in non-package
```

Perhaps this is sphinx 1.4.1 ?  OTOH, using the full name everywhere:
 
```
.. currentmodule:: lmfit.parameter
.. currentmodule:: lmfit.minimizer
```

works fine, and references can still be created with `:meth:leastsq`, etc.

I don't see much info on what `currentmodule` is supposed to do for intersphinx, and do not know what the keys in `objects.inv` should be.

Should *all* instances of  `.. module:: foo` be replaced with `.. currentmodule: foo`?    That would be fine with me.

**Comment by andyfaff** [comment]
I think the documentation should be made as simple as possible for lmfit maintenance/development, but also consistent.  autodoc is a good way of achieving this, I'm a fan of the docstring generating the documentation.

Here's what is contained in the `objects.inv` file from http://lmfit.github.io/lmfit-py for the `'py:classes'` key:

- models.QuadraticModel
- models.GaussianModel
- models.BreitWignerModel
- models.StudentsTModel
- models.VoigtModel
- models.LinearModel
- models.ExpressionModel
- model.CompositeModel
- models.ExponentialGaussianModel
- model.ModelResult
- models.MoffatModel
- models.Pearson7Model
- Minimizer.Minimizer
- models.ConstantModel
- models.LognormalModel
- models.PolynomialModel
- models.PowerLawModel
- models.RectangleModel
- MinimizerResult
- lmfit.parameter.Parameters
- models.ExponentialModel
- models.LorentzianModel
- models.ParabolicModel
- Parameter
- models.PseudoVoigtModel
- models.SkewedGaussianModel
- model.Model
- models.StepModel
- models.DonaichModel
- models.DampedOcsillatorModel

You can see that you all the models are prefixed by the `models` module name. However, `Parameter` and MinimizerResult are not prefixed by their module names. Then you have `lmfit.parameter.Parameters`, which as well as being prefixed by its module name is also prefixed by the name of the package. Finally the `Minimizer.Minimizer` class is prefixed by a wrongly capitalized module name - it should be `minimizer` not `Minimizer`.

All I'm suggesting is that whatever we decide to do in the lmfit documentation the objects.inv should be consistent:

lmfit.<modulename>.Class
-or-
<modulename>.Class

The same request goes for all the functions, but I haven't been through them.

**Comment by newville** [comment]
@andyfaff  I agree.   I raised this issue with the hope of making more of the docs generated from docstrings,  and more easily maintained.   I think napoleon docstrings will help that.   It also seems like the docs need a bit of attention and improvement (perhaps a bit more of a tutorial / simple user interface?).   But, we don't have to rush this decision:  this doc overhaul is aiming for 0.9.5, not 0.9.4.

Any objections to standardizing on `.. currentmodule: lmfit.Thing`?

**Comment by tritemio** [comment]
+1

**Comment by tritemio** [comment]
I think we should use `.. module::` in the doc page where there is the full documentation for a module.

In other doc pages, where is convenient to reference classes/functions of one module, we can use `.. currentmodule::`. In both cases, the objects.inv is generated using the full path (starting with `lmfit....`).

The wrong entries in objects.inv are due to errors in the manual (non-autodoc) documentation of classes or functions.

**Comment by newville** [comment]
@tritemio 

> I think we should use .. module:: in the doc page where there is the full 
> documentation for a module.

Out of curiosity, what is the advantage (or even difference) of using `module` over `currentmodule` at the top of an RST file?   I'm sort of unsure that `currentmodule` really does. 

>  The wrong entries in objects.inv are due to errors in the manual (non-autodoc) 
> documentation of classes or functions. 

Ah, what are those errors?  Actually, for that matter what are the "wrong entries"?  I guess I don't really understand why `models.StepModel` is wrong and `lmfit.models.StepModel` right.   It suggests that sphinx (or is just intersphinx?) makes some assumptions about how to import things.  If so, that would seem easy to break.

**Comment by tritemio** [comment]
@newville, is just that for API docs it seems natural to use the full name of each function/class. By "wrong" I was referring to the capitalization error.

My understanding is that `.. module :: A`, semantically indicates that the following section is the documentation for module A and it adds an entry to the index. Whereas `.. currentmodule :: A` is optionally used as a shortcut when the next section has links to some objects in module `A` (no index entry is added). In both cases, after the directive, you can link to a function in `A` using 

```
:func:`name`
```

without the `A.` (or `A.B.C` for a deeply nested module), but the API doc will have the full name (i.e. the objects.inv will have objects starting from the package name).

**Comment by tritemio** [comment]
Relevant docs for module and currentmodule directives:

http://www.sphinx-doc.org/en/stable/domains.html#the-python-domain

**Comment by newville** [comment]
On Jul 20, 2016 2:58 AM, "Antonino Ingargiola" <notifications@github.com>
wrote:
>
> Relevant docs for module and currentmodule directives:
>
> http://www.sphinx-doc.org/en/stable/domains.html#the-python-domain
>

Thanks... It's starting to come to me.  It sort of looks like we should be
using `module` and fully qualified names in most places. Is that your
understanding?

**Comment by tritemio** [comment]
@newville, yes it is. Also, using `module` (or `currentmodule`) the links to the API docs can be short but the target of the link will always be the full name.

**Comment by tacaswell** [comment]
I am :-1: on switch to google-style docstrings from numpy style docstrings.  

The rest of the scientific eco system uses nump-style (numpy, scipy, mpl, pandas, skimage, everything we are doing at BNL).  Any aesthetic benefit of the google style (which is subjective) is over whelmed by the cognitive load of seeing differently formatted docs across different projects.

**Comment by newville** [comment]
@tacaswell  I don't really buy the consistency argument.  It would have been used to argue for sticking with Fortran77 and troff, because all serious scientific work is in Fortran77 and man pages with tables and well typeset formulas are obviously the best way to document.  

I'd say we use the best tools available.    "Easily used by many developers" is a part of "best", but I'm not sure that "consistency with Project X"  is (especially several of the projects you mention).    Sphinx and RST are fine, but far from perfect.  Pydoc was OK.  In some ways, troff was and latex is better, and it's really kind of sad that we're using the RST and numpydoc strings at all.    But, there are real benefits to Sphinx and having doc strings that automatically get rendered to user- and API-docs.  There are also downsides, including the illusion that docstrings are complete documentation.

But, OK, several people were under-enthused by the napoleon docstrings.  We can use numpy docstrings until it becomes obvious that those are no longer "good" (probably once some other scipy-related project switches to napoleon).
