### ISSUE TITLE
add two model which contains same parameters

### ISSUE THREAD

**Issue by whitenights1** [lmfit/lmfit-py#356]
I'm trying to fit a data which composite of several peak in the shape of gaussian distribution. I use the feature of  Model in lmfit to create a Model for each of peak( I used the Gaussian function edited by myself, not the built one in lmfit). The I try to make a composite of them all. Because the width of those Gaussian peak are the same, so when I want the same parameter in each of Model. When I add two Model, the lmfit told me   ' Two models have parameters named 'a'. Use distinct names.'. Is there any solution to this problem? I know I can put a constraint on the parameters. But is there any other way since the number of peaks is large.

**Comment by newville** [comment]
NOT AN ISSUE. 
Suspiciously inactive user account fails to read or comprehend the VERY clear instructions for getting help, posts spam issue for so-called problem that can be addressed easily by reading documentation and examples.

User deserves no help. 

If re-opened or replied to, this will be reported as abuse.
