### ISSUE TITLE
inconsistencies in setting sigma for conf_interval() and eval_uncertainty()

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#368]
In working on #367,  I wanted to allow a `sigma` option to `ModelResult.eval_uncertainty()`.
Ideally, this should match the meaning in `conf_interval()`.   But, in `conf_interval()`, the default argument is `sigmas=(0.674, 0.95, 0.997)`.   

This leads to a couple questions:

1.  Shouldn't these be `(0.6827,  0.9545,  0.9973)`?  That is, erf(i/sqrt(2)) for i = 1, 2, 3?
2. I think the values there are really the *confidence levels*, not sigma.  And, well, they're harder to remember than "1, 2, 3".....  Should these default values for sigma just be `(1, 2, 3)`?

Consistency and backward compatibility are important, for sure, but so is simplicity and correctness.    

Any thoughts on how to deal with this?

**Comment by Tillsten** [comment]
Sadly i don't remember if this was just a brain-fart of me or had a reason. Properly former. I think this should count as a bug and be corrected. For the second point i disagree: if someone want e.g. quartiles one would first to have them calculated as a function of sigmas.

**Comment by newville** [comment]
@Tillsten   Thanks,  I think at the least we change the default values.

I'm not sure I understand the second point.  Maybe I just don't speak Statistics well enough.  You mean, like setting `sigmas=(0.25, 0.75)` ? 

Having to specify the probabilities instead of "n"*sigma seems OK,  but I think 1-, 2-, 3-sigma are probably easier for everyone to remember than .68, .95, .97.    Like, it seems that it took awhile before anyone noticed the default values were different than what was documented as the default values.

Either way, we can document what the default values mean.

**Comment by newville** [comment]
@Tillsten a possible compromise?:   At #368 I changes the default values in conf_intervals() (and the tests for it) to use the standard 68-95-99 values.  I also added to it, and to `ModelResult.eval_uncertainty()` a check on the value of `sigma` so that if `sigma >=1` it is   treated as an `n-sigma` value, and converted to a probability.  That is, saying

     `sigma=(1, 2, 3)`

will be the same as saying::

    `sigma=(0.6827, 0.9545, 0.9973)`

Is that reasonable?

**Comment by Tillsten** [comment]
Would be workable, but i in retrospect my keyword naming was quite bad, maybe changing it to  more correct word would be nice too.

**Comment by newville** [comment]
@Tillsten OK, l'll change the call signatures and docs to document this as "1, 2, 3" etc by default, but for backward compatibility support values < 1 as meaning "probability", and add a note about that to the docstrings.

**Comment by newville** [comment]
Fixed with #367
