### ISSUE TITLE
No uncertainty reported when using 'least_squares'

### ISSUE THREAD

**Issue by tritemio** [lmfit/lmfit-py#369]
I noticed that when using the new `least_squares` method to fit a model the uncertainties are not reported by ModelResult.fit_report().

I'll send an example when I find the time.

**Comment by newville** [comment]
@tritemio   Yes, you are correct, uncertainties are not calculated with `least_squares`.   The  `OptimizeResult` does not include the covariance matrix.  I believe this could be constructed from the returned jacobian, but I haven't tried that.     That might be a very nice addition!
 
I have to admit that I find `least_squares` odd and seems to try to do too many things (at least in comparison to the other solvers in scipy.optimize).  It has many options with confusing inter-dependencies that really suggests to me that it should have been part of a more comprehensive suite of minimization routines in scipy.optimize, with more uniform interfaces.   But it just kind of makes it more complicated.  Another weirdness is that it's great that one can specify a `loss` option, but if one chooses anything other than the default, then `least_squares` is actually **NOT** a least squares solution.

It may be that I don't understand it well, or that it is really aimed at a solution to a different kind of optimization problem (large sparse matrices) that are very different from the ones I encounter.

**Comment by Tillsten** [comment]
It is quite easily added, i didn't due to lack of time. IIRC inv(J*J.T) gives the covariance. With that one can reuse the code for leastsq.

**Comment by newville** [comment]
@Tillsten That's true, and I think it should be easier without the need to transform the Jacobian back to  "user coordinates" or worry about the pivoting of variables.  Strange that it's not included in the `OptimizeResult` from `least_squares` then.

**Comment by tritemio** [comment]
Looks like a feature can be pushed upstream to scipy.

**Comment by newville** [comment]
@tritemio @Tillsten Trying to push upstream is a fine idea.  But also: if it's not too hard to do, we could just do it here, possibly faster, and possibly easier to compare with other results.   It might be more convincing to push upstream once t is shown to be working.

**Comment by tritemio** [comment]
@newville, agree.

**Comment by ButcherAC** [comment]
Hello, not sure this is related, but a call of 
Parameters['c'].set(max = out_exp.params['c'].value)
to limit the maximum value of a fit from a previous fit eliminates the reporting of errors. Fit results with the line above:
[[Variables]]
    a:   0.12080440 +/- 0        (0.00%) (init= 0.09026197)
    b:   0.00099233 +/- 0        (0.00%) (init= 0.0008019634)
    c:  -1.5963e-07 +/- 0        (0.00%) (init=-1.59629e-07)
    d:   114.224907 +/- 0        (0.00%) (init= 0.2)
Without:
[[Variables]]
    a:   0.10665665 +/- 0.002756 (2.58%) (init= 0.09026197)
    b:   0.00085328 +/- 2.12e-05 (2.49%) (init= 0.0008019634)
    c:  -0.00160982 +/- 0.000229 (14.25%) (init=-1.064194e-07)
    d:   123.352234 +/- 1.375701 (1.12%) (init= 0.2)
The out_exp.params['c'].value type is np.float64. Not sure what is going wrong?

**Comment by ButcherAC** [comment]
Just an update here, it seems that setting only the maximum produces this error, setting both min and max solves the problem.

**Comment by newville** [comment]
@ButcherAC Why are you commenting on this closed issue?  Is this related to the Issue of uncertainties not being calculated when using `method='least_squares'`?   

If you are not sure if it is related, you should use the mailing list.
