### ISSUE TITLE
result.message in minimizer.py

### ISSUE THREAD

**Issue by colgan** [lmfit/lmfit-py#378]
Hi,
by using result.message I always got the message: 'Tolerance seems to be too small.', so I decided to have a look at it. The code snipped in your file which generates the variable result.message is:

        result.ier = ier
        result.lmdif_message = errmsg
        result.message = 'Fit succeeded.'
        result.success = ier in [1, 2, 3, 4]
        if result.aborted:
            result.message = 'Fit aborted by user callback.'
            result.success = False
        elif ier == 0:
            result.message = 'Invalid Input Parameters.'
        elif ier == 5:
            result.message = self._err_maxfev % lskws['maxfev']
        else:
            result.message = 'Tolerance seems to be too small.'

In my opinion this is never leading to result.message being: 'Fit succeeded.'
I think the snipped should look something like this:

        result.ier = ier
        result.lmdif_message = errmsg
        result.success = ier in [1, 2, 3, 4]
        if result.aborted:
            result.message = 'Fit aborted by user callback.'
            result.success = False
        elif ier == 0:
            result.message = 'Invalid Input Parameters.'
        elif ier == 5:
            result.message = self.err_maxfev % lskws['maxfev']
        elif result.success:
            result.message = 'Fit succeeded.'
        else:
            result.message = 'Tolerance seems to be too small.'

Kind regards
Colgan

**Comment by newville** [comment]
@colgan  Thanks -- you're right that the messages are not accurately reflecting the value of `ier` from MINPACK.  In fact "success" is not correct either.  It should be:

0.  improper input parameters (more variables than data points, tolerance < 0.0, or no data)
1.  fit successful
2.  fit successful
3.  fit successful
4.  one or more variable did not affect the fit
5.  too many iterations
6.  tolerance too small.
7.  tolerance too small.

That is `result.success` should be `ier in (1, 2, 3)`.  

If you're willing to make a PR for this, that would be great.

**Comment by colgan** [comment]
Done.
Kind regards
Colgan
