### ISSUE TITLE
Inverse Step function (erfc)

### ISSUE THREAD

**Issue by gyger** [lmfit/lmfit-py#382]
It would be nice if the build-in models also contain an inverse Step function (e.g. based on erfc(x) = 1- erf(x)).
Would this be an accepted Pull-request?

Cheers

**Comment by newville** [comment]
@gyger  I think that would be fine.

**Comment by reneeotten** [comment]
@gyger are you still interested in (working on) this?

**Comment by gyger** [comment]
Hey sorry for the late response. 
I never came around creating a pull request from my code. I missed that, I am sorry. 
If somebody else wants to do this as a small fix, very fine for me. 
Otherwise it can also be closed and reopened if somebody finds this annoying again.

**Comment by newville** [comment]
@gyger no problem!   @reneeotten I'd vote to close this.

**Comment by gyger** [comment]
Sorry for opening this again, because I needed it again. I extended the lineshape.step function with the following additional shapes.
- inverf or erfc
- invlogistic
- invatan or invarctan
- invlinear

Is this an accepted way?

**Comment by newville** [comment]
@gyger well, I guess we can conclude that this is not really urgent ;)

I'm not necessarily opposed to adding more options or lineshapes, but I am sort of reluctant to have many variations on the same lineshapes.   Wouldn't it be true that these would give the same result:

     model1 = StepModel(form='erf', prefix='step_') + ConstantModel()
     model1 = StepModel(form='erfc', prefix='step_') + ConstantModel()

with a change in the sign of `step1_amplitude` and a change in the value of the constant offset?  I think that would apply to the other `inv` forms too, no?

Anyway, that is not a strong opinion against this, maybe more like a "-0.01".    If it seems useeful to others, I would be OK with including it.  I would prefer one spelling variant each.

**Comment by gyger** [comment]
I fully agree it is a solution to use a negative amplitude plus offset or also Constant model - StepModel works. 
But most of the time I combine the function with some other functions lets say an exponential rise to turn it of at some point, because the device fails and it just looks nice if every part of the model can somehow be attributed to parts of the line shape.

I agree it is also some kind of feature creep, as there are already ways to do this. One more way I was thinking of would be to use the rectangular window model with the on-part far away outside the range.

**Comment by newville** [comment]
@gyger I think I don't understand the "But..." part there.  Does it not work to ConstantModel + StepModel whether the step goes up or down?

**Comment by gyger** [comment]
Yes it works. Just when printing the models, to show what was fitted e.g. in the summary of the fit, it clutters the string a little bit more. 
So really no functional argument there.
