### ISSUE TITLE
set function of Parameter class inadvertently affects min/max settings

### ISSUE THREAD

**Issue by reneeotten** [lmfit/lmfit-py#389]
I think there is an issue with the set function. Consider the following code: `par = lmfit.Parameter('a', value=10, min=0, max=20)` , which will give: `<Parameter 'a', 10, bounds=[0:20]>`

now suppose you want to change the value to 15 and do so by: `par.set(value=15)`
this will now give: `<Parameter 'a', 15, bounds=[-inf:inf]>`, instead of the expected output `<Parameter 'a', 15, bounds=[0:20]>`. From the code, it looks like the problem is that the `set` function uses `None` for all the attributes that are not given explicitly and using `None` for min/max will result in `-inf / inf`. I don't think that this is intended and is also not consistent with the description in the manual (p. 16), where it states that to lift a lower boundary one should do `p1.set(min=-np.inf)` instead of p1.set(min=None).

I came across this issue when adding `brute_step` to the parameter class in my branch. This parameter should either have a value or be set to `None`. However, if it was initialized with a value [e.g., `par = lmfit.Parameter('a', value=10, min=0, max=20, brute_step=0.5)`] it should not be set to `None` when the user decides to do `par.set(value=15)`.

I haven't thought deeply about the best way to change this (at least if we agree that this is a bug), but it would be great to make the function behave as described in the manual: 
> You can use this to update some Parameter attribute without affecting others.

**Comment by newville** [comment]
@reneeotten Thanks -- I think this should be solvable by comparing the passed-in values for `min` and `max to `None` before setting the values.

**Comment by andyfaff** [comment]
I'm not a fan of adding the brute_step parameter to the Parameter class.
Such a step attribute doesn't really belong to that kind of object, whereas
e.g. a parameter value does.

Passing an array_like object, or dict, when calling the brute search is an
alternative. E.g. {"a": 10} would divide the range for the 'a' parameter
into 10. However that seems a little messy as well.

**Comment by newville** [comment]
@andyfaff  that seems like a comment for #383 in general, not this issue about `Parameter.set()`.
I thought the idea of each parameter having a `brute_step` attribute was kind of a nice way to do it, and avoid all these ugly dictionaries with required keys or ordered lists, etc.   That is, you sort of do want to say "parameter a should take 5 steps, parameter b should take 3 steps".


For this issue, I believe that `Parameter.set()` might become (modulo whether `brute_step` is included):

```python

    def set(self, value=None, vary=None, min=None, max=None, expr=None):
        """
        Set or update Parameter attributes.

        Parameters
        ----------
        value : float, optional
            Numerical Parameter value.
        vary : bool, optional
            Whether the Parameter is fixed during a fit.
        min : float, optional
            Lower bound for value. To remove a lower bound you must use -np.inf
        max : float, optional
            Upper bound for value. To remove an upper bound you must use np.inf
        expr : str, optional
            Mathematical expression used to constrain the value during the fit.
            To remove a constraint you must supply an empty string.
        """

        self.__set_expression(expr)
        if value is not None:
            self._val = value
        if vary is not None:
            self.vary = vary
            
        if min is not None:
            self.min = min
        if max is not None:
            self.max = max
            
        if self.min is None:
            self.min = -inf
        if self.max is None:
            self.max = inf

```

That is, the issue here was that `max` had a default value of `inf` and one had to pass in existing bounds for them to not be clobbered by `Parameter.set()`.

**Comment by reneeotten** [comment]
@newville thanks, that indeed almost fixes the issue! It still exists for the `expr`, when let's say you have an expression and decide to change for the bounds.

From the example in the manual:
```
p = lmfit.Parameters()
p.add_many(('amp1', 10, True, None, None, None),
           ('cen1',   1.2,  True,  0.5,  2.0,  None),
           ('wid1',   0.8,  True,  0.1, None,  None),
           ('amp2',   7.5,  True, None, None,  None),
           ('cen2',   1.9,  True,  1.0,  3.0,  None),
           ('wid2',  None, False, None, None, '2*wid1/3'))
```
and then doing `p['wid2'].set(min=0)` will reset the `expr` for `wid2` to `None`.

So I guess making one more change in the `set` function, in addition to the ones above, will fix all of these:
```self.__set_expression(expr)```
to 
```
if expr is not None:
    self.__set_expression(expr)
```

Let's continue the discussion on `brute_step` in the PR - I'll look at it and comment there later tonight or tomorrow.

**Comment by newville** [comment]
@reneeotten  Again, good point -- I completely agree.  Everything in `set()' should be conditional.
