### ISSUE TITLE
Model.fit_report() does not display fit statistics

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#407]
`Model.fit_report()` reports the values for the parameters, but does not display the general statistics from the fit.

There is a simple fix:  https://github.com/lmfit/lmfit-py/blob/master/lmfit/model.py#L1148 should be changed from 
```
    report = fit_report(self.params, modelpars=modelpars,
```

to 
```
    report = fit_report(self, modelpars=modelpars,
```

but we should add a test for this too, so that there is no regression.

**Comment by reneeotten** [comment]
this issue (introduced in 726ba171) was fixed by @newville in #408 and can be closed.
