### ISSUE TITLE
'ModelResult' object has no attribute 'eval_confidence_band'

### ISSUE THREAD

**Issue by timsainb** [lmfit/lmfit-py#422]
The function eval_confidence_band does not appear to be in the code, although it is referenced in the documentation:

`dely = out.eval_confidence_band(x=x)`

**Comment by newville** [comment]
@timsainb Good catch.  The doc should be updated to be `dely = out.eval_uncertainty(x=x)`

**Comment by newville** [comment]
fixed in 8cad3ee5e31a7e953a2470a04cafaab0fb6f5b0c
