### ISSUE TITLE
PsuedoVoigt model parameter 'fraction'

### ISSUE THREAD

**Issue by sjlimmer** [lmfit/lmfit-py#425]
Occasionally when I fit peaks with a PseudoVoigt model the returned value for the parameter 'fraction' is outside the range 0-1. If I'm understanding correctly, this value controls the relative weight of the Gaussian and Lorentzian components. So it should be 0 ≤ fraction ≤ 1 as per https://en.wikipedia.org/wiki/Voigt_profile#Pseudo-Voigt_approximation.

I can impose the bounds on 'fraction' with 

    pv_peak = PseudoVoigtModel(prefix='PV_')
    params = pv_peak.make_params(i)
    params['fraction'].min = 0
    params['fraction'].max = 1

But this should probably be the default behavior.

**Comment by newville** [comment]
@sjlimmer thanks, and I agree this should be fixed.  Please let me know if you'd like to make a PR. We're always eager to have contributions from newcomers,  and I think this would be an easy one to do.

**Comment by sjlimmer** [comment]
@newville Sure, I'd be willing to give it a shot.
