### ISSUE TITLE
ModelResult.plot() functions should be able to turn off showing initial fit

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#426]
ModelResult.plot*() functions should have an option to turn off displaying the initial fit.

See discussion at 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lmfit-py/ZG4prIG-th4/Xhv5iiOQAwAJ

**Comment by reneeotten** [comment]
I think the easiest way to do this is to use the `initfmt` parameter and pass `None` if you don't want to show the initial plot. That would only require the addition of ```if initfmt:``` before the ```ax.plot()``` statement in the ```plot_fit``` function (and some updates to docstring/documentation).  I can do that - what do you think?

**Comment by newville** [comment]
@reneeotten that could be OK, but maybe a "with_init=True/False" would be clearer / simpler.  Not a strong preference on that.  I think that showing the initial function is probably better off by default -- it's often distracting.
