### ISSUE TITLE
Minor correction to the docs

### ISSUE THREAD

**Issue by jmborr** [lmfit/lmfit-py#432]
In [model.rst](https://github.com/lmfit/lmfit-py/blob/master/doc/model.rst)

Line 136
```>>> result = gmod.fit(y, params)```
should be
```>>> result = gmod.fit(y, x=x, params)```

Similarly, line 140
```>>> result = gmod.fit(y, cen=6.5, amp=100, wid=2.0)```
should be
```>>> result = gmod.fit(y, x=x, cen=6.5, amp=100, wid=2.0)```

Line 309
```>>> for pname, par in decay_model.params.items():```
excepts:
```AttributeError: 'Model' object has no attribute 'params'```

**Comment by newville** [comment]
@jmborr thanks -- I agree.  If you willing to make a PR, that would be great. Otherwise, let us know and someone will do this....

**Comment by jmborr** [comment]
OK, I'll start with the PR

**Comment by reneeotten** [comment]
@newville this issue can be closed ; it was merged in #438
