### ISSUE TITLE
Module initialization very slow

### ISSUE THREAD

**Issue by astromancer** [lmfit/lmfit-py#450]
I'm consistently experiencing very slow initialization times for lmfit which is slowing down my application. 

`%time import lmfit`
CPU times: user 17.9 s, sys: 1.04 s, total: 18.9 s
Wall time: 18.5 s

Nearly 20s to import the library seems unreasonable.  Is there any way to speed this up?

**Comment by newville** [comment]
@astromancer please indicate which version of lmfit, python, OS, etc.

I agree that 20 sec is too long, but it might not be exactly our fault ;).  Lmfit is actually a pretty small package, but it does import several other packages, some optionally.  You might try something like this to check import times::

```python
import sys
import time
import platform

import_times = []
t0 = time.time()

for modname in ('numpy', 'scipy', 'scipy.optimize', 'scipy.stats', 'pandas',
                'matplotlib', 'lmfit'):
    tb4 = time.time()
    mod = __import__(modname)
    import_times.append((modname,
                         getattr(mod, '__version__', '?'),
                         time.time() - tb4))

import_times.append(('Total time', '', time.time() - t0))
print("Python: ", sys.version)
print("Platform: ", platform.platform())
for mod, vers, imptime in import_times:
    print("%s %s:  %.3f" % (mod, vers, imptime))

```

With this, I currently get:

```
Python:  3.6.3 |Anaconda custom (64-bit)| (default, Nov  3 2017, 12:34:11) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Platform:  Darwin-17.2.0-x86_64-i386-64bit
numpy 1.13.3:  0.096
scipy 1.0.0:  0.004
scipy.optimize 1.0.0:  0.072
scipy.stats 1.0.0:  0.138
pandas 0.21.0:  0.189
matplotlib 2.1.0:  0.031
lmfit 0.9.7+161.g40d307f:  0.226
Total time :  0.755
```

Timing with `time.time` can be inaccurate, so you might want to run that a few times.  For me, the above are "typical", and not "best out of ten".

**Comment by astromancer** [comment]
@newville Thanks for the timing code. I "typically" get:
```
Python:  3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406]
Platform:  Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
numpy 1.15.0.dev0+d233e1f:  0.327
scipy 1.1.0.dev0+676da8f:  0.013
scipy.optimize 1.1.0.dev0+676da8f:  0.246
scipy.stats 1.1.0.dev0+676da8f:  0.574
pandas 0.18.1:  1.942
matplotlib 2.1.0+864.g813d84299.dirty:  0.000
lmfit 0.9.7+165.gfc5e38d:  15.958
Total time :  19.059
```
 I'll have a go at profiling the code to see what is taking all that time.

**Comment by newville** [comment]
@astromancer  Yeah, that seems way too slow.   But I can't reproduce it.  On a Linux host with Anaconda Python 3.6.3 or 3.5.4 environments, I get total import times of 0.6 seconds or less.   FWIW, import times are comparable (slightly faster, actually) with Python 2.7.

I might suggest trying separate imports of `emcee`, but for me that seems to be very fast...  I don't know what is left!

**Comment by astromancer** [comment]
@newville OK, I've been playing around with python's builtin profiler and managed to track down the long running calls with this:
```
import cProfile as profile
import pstats

if __name__ == '__main__':
    filename = 'lmfit-import-stats.pro'
    profile.run('import lmfit', filename)

    # Read stats file
    stats = pstats.Stats(filename)
    # Clean up filenames for the report
    stats.strip_dirs()
    # Sort the statistics by the cumulative time spent in the function
    stats.sort_stats('cumulative')
    stats.print_stats(30)
```

The results are here: [lmfit-import-profile.txt](https://github.com/lmfit/lmfit-py/files/1574608/lmfit-import-profile.txt).  It seems like the culprit is `matplotlib.afm` which creates a font list each time the library is imported.  That lead me to [this](https://stackoverflow.com/questions/26421364/extremely-slow-import-of-matplotlib-afm) SO solution.  

The timing results after deleting the matplotlib font cache:
```
Python:  3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406]
Platform:  Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
numpy 1.15.0.dev0+d233e1f:  0.294
scipy 1.1.0.dev0+676da8f:  0.013
scipy.optimize 1.1.0.dev0+676da8f:  0.241
scipy.stats 1.1.0.dev0+676da8f:  0.523
pandas 0.18.1:  1.700
matplotlib 2.1.0+864.g813d84299.dirty:  0.000
lmfit 0.9.7+165.gfc5e38d:  1.101
Total time :  3.872
```
Much better!!
Thanks for your help in tracking this down!

**Comment by newville** [comment]
@astromancer Wow.  To be clear, was the solution simply deleting files in `.matplotlib` or was there something in `.cache/matplotlib`.   Maybe raise that as a matplotlib issue?  

Anyway, glad it is working better now!

**Comment by astromancer** [comment]
I deleted everything in `~/.cache/matplotlib`. After that the first import was still slow as the font cache was being built with the new matplotlib version. Thereafter subsequent imports where quick.  :+1: :smiley:
