### ISSUE TITLE
The height parameter is not always correctly calculated for built-in models

### ISSUE THREAD

**Issue by jancura** [lmfit/lmfit-py#453]
I use several simple combined models as follows, e.g.:
`model1 = ConstantModel() + GaussianModel()`
`model2 = ConstantModel() + LorentzianModel()`  
`model3 = ConstantModel() + VoigtModel()`

All of those models have different formula for their peak (height). However, when I print the report_fit() then I see the following results reported:

- model1: 
`fwhm:        13.2094965 +/- 0.130300 (0.99%)  == '2.3548200*sigma'`
`height:      1044.38281 +/- 8.897788 (0.85%)  == '0.3989423*amplitude/max(1.e-15, sigma)'`

- model2: 
`fwhm:        11.3496155 +/- 0.099964 (0.88%)  == '2.0000000*sigma'`
 `height:      1129.79057 +/- 6.936242 (0.61%)  == '0.3183099*amplitude/max(1.e-15, sigma)'`

- model3: 
`fwhm:       12.4410177 +/- 0.106204 (0.85%)  == '3.6013100*sigma'`
`height:      2071.88188 +/- 13.48051 (0.65%)  == '0.3989423*amplitude/max(1.e-15, sigma)'`

These are the results fitted to the same data. As one can observe the formula for calculating heights is always the same, while it is obvious that those models should have different height calculation results. This is proven by just evaluating the models at their centers (of the peak) as follows:

- model1:
`>> r.components[1].func(r.best_values['center'], r.best_values['amplitude'], r.best_values['center'], r.best_values['sigma'])`
`>> 1044.3827591283216`
- model2:
`>>  r.components[1].func(r.best_values['center'], r.best_values['amplitude'], r.best_values['center'], r.best_values['sigma'])`
`1129.7905268359323`

- model3: 
`>> r.components[1].func(r.best_values['center'], r.best_values['amplitude'], r.best_values['center'], r.best_values['sigma'])`
`>> 1083.9185964268597`

The results do not match heights reported by fit_result. Also, the heights do not include the component form the constant model, as that is non-zero:

- model1
`>> r.best_values['c']`
`2674.4083589341017`

- model2
`>> r.best_values['c']`
`>> 2670.14664322767`

- model3
`>> r.best_values['c']` 
`>> 2671.8599398697625`

**Comment by newville** [comment]
@jancura Did you read and understand https://github.com/lmfit/lmfit-py/blob/master/.github/ISSUE_TEMPLATE.md?  Why did you not post this to the google group?

> These are the results fitted to the same data. As one can observe the formula for calculating 
> heights is always the same, while it is obvious that those models should have different height 
> calculation results.

Wrong.  Look again, the formulas are different.

> The results do not match heights reported by fit_result

They look like they match to me, except for the `VoigtModel`, where you forgot to pas the `gamma` parameter.

> Also, the heights do not include the component form the constant model, 

Of course not.  The height of the peak models does not include contributions from other models.

**Comment by reneeotten** [comment]
@jancura I agree with @newville  that this would have been a better question to start on the mailinglist. However, I would like to add that the equation for the height of the ``VoigtModel`` in the presented example is indeed incorrect (Gaussian/Lorentzian heights are correct). There have been several updates to the calculation of FWHM and height for built-in models by @openafox recently, which are all merged in the ``master`` branch, but are not available in the latest released version. You could try and install the unreleased/development version following the instructions provided [here](http://lmfit.github.io/lmfit-py/installation.html) and give it another try and see how that looks!

On the second point, I agree with @newville that the height of the peak model should not include the contribution of other components. In, your case you should be able to just add the value of the ``ConstantModel`` and the height of the peakmodel. You should probably also pass the ``gamma`` value to the ``VoigtModel`` as Matt pointed out, and I think doing this and using the latest version + adding the components together, should do the trick. If not, please post the data/code to the mailinglist and we can take another look.

**Comment by newville** [comment]
@reneeotten @jancura  Thanks Renee.  I did assume that someone posting an Issue would be using the github master branch and would have searched for similar Issues and found #448....
