### ISSUE TITLE
Merely importing lmfit breaks parallel code elsewhere

### ISSUE THREAD

**Issue by ezwelty** [lmfit/lmfit-py#463]
Merely importing lmfit (0.9.8) with `import lmfit` breaks the use of parallel code on my system (Mac OSX 10.11.6, Python 2.7.13 / 3.5.0). I've tested this with both `multiprocessing` and `sharedmem` (see minimal scripts below). 

The issue seems to arise specifically for functions that evoke multithreading within their respective package (e.g. `numpy.matmul()`, `cv2.SIFT.detectAndCompute()`). If I make the matrix in the scripts below much smaller (e.g. change `5000` to `5`), avoiding internal multithreading, the scripts work. Yes, running these functions in parallel over multiple processes is still much faster.

I tried importing all the outside dependencies of `lmfit`, and that did not break the scripts, so I have good reason to believe that code within `lmfit` is causing the break.

## with `sharedmem`

```python
import numpy as np
import sharedmem
import lmfit

def parallel_matmul(x):
    R = np.random.randn(3, 3)
    return np.matmul(R, x)

with sharedmem.MapReduce() as pool:
    results = pool.map(parallel_matmul,
        [np.random.randn(3, 5000) for i in range(2)])
```

> sharedmem.sharedmem.SlaveException: slave process 1 killed by signal 11

## with `multiprocessing`

```python
import numpy as np
import multiprocessing
import lmfit

def parallel_matmul(x):
    R = np.random.randn(3, 3)
    return np.matmul(R, x)

pool = multiprocessing.Pool(4)
results = pool.map(parallel_matmul, [np.random.randn(3, 5000) for i in range(2)])
```

> *Code never exits and Python has to be restarted*

**Comment by newville** [comment]
@ezwelty Hm, that is weird.  I'm not sure what is causing that.   I'm not familiar with `sharedmem`, but the `multiprocessing` script works for me on a couple different systems, including MacOS with Python 2.7 and 3.6 (both from anaconda).    

For sure, `lmfit` imports a lot of other packages besides numpy, including much of scipy. Some of these imports might be avoidable (say, `pandas`) but others (`scipy.optimize`) are definitely needed.

For me (Anaconda Python 3.6, MacOS), doing this:

```python
import sys
import numpy as np
import multiprocessing
np_modules = list(sys.modules.keys())

import lmfit

lmfit_imports = []
for m in sys.modules:
    if m not in np_modules:
        lmfit_imports.append(m)
print(len(lmfit_imports), len(sys.modules))
```

prints `619 856`.  That is, `import lmfit` brought in 600+ other modules.

I'm not saying that this is not a problem with `lmfit`, but I don't know why it would break `multiprocessing`.  It *might* actually be with some other package that lmfit imports.    I would suggest trying the following imports in place of `import lmfit` in case they also show the same problem for you:

  *  `from scipy.optimize import minimize`
  *  `import scipy.stats`
  *  `import scipy.special`
  *  `from pandas import DataFrame, Series`
  *  `import dill`

There might be other imports to test too, but these are the most suspicious to me.  Hopefully this will help identify the problem...

**Comment by ezwelty** [comment]
@newville Weird indeed.

I copied over *all* the external import statements from the lmfit source code, and the culprit was a surprise:

```python
from matplotlib import pyplot as plt
```

Swimming further upstream, deep within `matplotlib`, brings up this line from [matplotlib.backends.tkagg](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/tkagg.py):

```import
from six.moves import tkinter as Tk
# aka import Tkinter
```

I'll check with the core Python team. Sorry for the bother!

**Comment by newville** [comment]
@ezwelty Wow, that is sort of surprising.  Is that with Apple's system python or some other version?

**Comment by ezwelty** [comment]
@newville Now tested on Python versions 2.7.13, 2.7.14, 3.5.0, and 3.6.4. All were installed with pyenv (https://github.com/pyenv/pyenv). `import _tkinter` is the end of the line in Python, so it looks like an issue with the connection between Python and Tcl/Tk?

Posted at https://bugs.python.org/issue33111

**Comment by newville** [comment]
@ezwelty Sorry, I'm still not sure which Python you are using.  Apple, Anaconda, Homebrew, Macports?  They probably all make different assumptions about Tcl/Tk.

**Comment by ezwelty** [comment]
@newville I am using Python built directly from the source (with the mighty help from pyenv's python-build: https://github.com/pyenv/pyenv/tree/master/plugins/python-build). For example, for version 3.6.4: https://www.python.org/ftp/python/3.6.4/

**Comment by newville** [comment]
@ezwelty Uh, OK.  Maybe you're not quite understanding the point I'm trying to make.  You are seeing problems with Python's import of `_tkinter`, so  how was that Python and that Tk extension built?  
`pyenv` is for managing Python environments; it does not require building Python from source yourself.

You built your own version of Python.  OK, how did you build the `_tkinter` extension? Sorry, but this seems completely self-inflicted to me.

For sure this has nothing to do with `lmfit`.
