### ISSUE TITLE
passing keyword parameters from .fit() the underlying scipy minimizer is broken

### ISSUE THREAD

**Issue by greyltc** [lmfit/lmfit-py#464]
I've set up my model (`cellModel`) and parameters (`cellParams`) with guesses (with no bounds) properly.
Fitting works fine with the default method by doing this:
```
fitResult = cellModel.fit(II,cellParams, V=VV)
```
Now I'd like to compare my above fit result to that produced by using the Nelder-Mead method with its `xatol=4e-4` ([see Nelder-Mead scipy doc](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-neldermead.html))

So I do:
```
fitResult = cellModel.fit(II,cellParams, V=VV, model='nelder', fit_kws={'xatol':4e-4})
```
but that fails with the following error
```
Traceback (most recent call last):
  Debug Probe, prompt 70, line 1
    # needed for waiting for initial setup
  File "/usr/lib/python3.6/site-packages/lmfit/model.py", line 873, in fit
    output.fit(data=data, weights=weights)
  File "/usr/lib/python3.6/site-packages/lmfit/model.py", line 1217, in fit
    _ret = self.minimize(method=self.method)
  File "/usr/lib/python3.6/site-packages/lmfit/minimizer.py", line 1638, in minimize
    return function(**kwargs)
  File "/usr/lib/python3.6/site-packages/lmfit/minimizer.py", line 770, in scalar_minimize
    ret = scipy_minimize(self.penalty, variables, **fmin_kws)
builtins.TypeError: minimize() got an unexpected keyword argument 'xatol'
```
This is with the 0.9.9 release.

**Comment by reneeotten** [comment]
hi Grey, 


these tolerance keywords are unfortunately not very consistent between the different optimizers… However, if you look at the optimize.minimize documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) you’ll see that the argument there is called “tol”, and that is what you want to use here as well.

Within the scipy.optimize code, you can check the source, it will use this “tol” variables to use for the individual optimizers. For example, for Nelder-Mead it does:
# set default tolerances
if tol is not None:
options = dict(options)
if meth == 'nelder-mead':
options.setdefault('xatol', tol)
options.setdefault('fatol', tol)

I think using “tol” should solve your problem, so give that a try first.

**Comment by greyltc** [comment]
Ah ha! Thanks @reneeotten, you've enlightened me!

To pass keyword parameters down from .fit() to the underlying scipy minimize method, one must go through `scipy.minimize`'s `options` key word argument like this:

```
fitResult = cellModel.fit(II,cellParams, V=VV, method='nelder',fit_kws={'options':{'xatol':4e-4}})
```
Tricky!
Closing.

**Comment by newville** [comment]
@reneeotten  thanks for answering this. I would have closed this without a response. 

@greyltc in the future, please read and respect the instructions for how to get help.
