### ISSUE TITLE
Can't pickle Parameters class

### ISSUE THREAD

**Issue by AstroMike** [lmfit/lmfit-py#47]
Thanks for your work on lmfit.

It would be handy to be able to pickle the Parameters class, as a way of saving the fits. 

However when I try to do so, I get an error, apparently because the Parameter contains lambda functions, which are apparently un-pickleable.

The issue is similar to what is reported here:

http://stackoverflow.com/questions/14779803/how-to-place-several-tabs-into-separate-processes

Is there any easy way around this?

**Comment by newville** [comment]
I think this is addressed.
