### ISSUE TITLE
Composite models parameter nameclash

### ISSUE THREAD

**Issue by achennu** [lmfit/lmfit-py#488]
Firstly, thanks for a great package and superb documentation.

I am trying to build a composite model, and noticed that there seems to be a namespace problem in the parameters that are built. Briefly, I try to create a multi-peak model, say of two Gaussians and add them together for a composite model.

```python
from lmfit.models import GaussianModel

def make_multipeak_model(prefix, centers=(20, 60)):

    composite = None

    for i, cen in enumerate(centers, start=1):
        peak = GaussianModel(prefix=f'p{i}')
        peak.set_param_hint('center', min=cen-5, max=cen+5)

        if composite is None:
            composite = peak
        else:
            composite = composite + peak

    # composite has components p1, p2, p3...
    composite.prefix = prefix
    # add a prefix "c1" to the composite, should make it c1p1, c1p2, c1p3, ...
    print(composite)
    print(composite.make_params().keys())

    return composite


candidate1 = make_multipeak_model('c1')
candidate2 = make_multipeak_model('c2')

# uncomment this line causes the NameError
#full_model = candidate1 + candidate2

```
What I expect is that the parameters of candidate1 are:  `['c1p1sigma', 'c1p1fwhm', 'c1p1height', 'c1p1center', 'c1p2sigma', 'c1p2fwhm', 'c1p2height', 'c1p2center']`.
But instead the parameters are:
`['p1sigma', 'p1center', 'p1amplitude', 'p2sigma', 'p2center', 'p2amplitude', 'c1p1sigma', 'c1p1fwhm', 'c1p1height', 'c1p1center', 'c1p2sigma', 'c1p2fwhm', 'c1p2height', 'c1p2center']`

So it seems that when the composite model is built, somehow the prefix set by `composite.prefix = prefix` works, but retains parameter names of the components. As a result, it is not possible to do `full_model = candidate1 + candidate2`, as it leads to a nameclash.

Now, one easy resolution for my use-case is to just add the composite prefix to the peak prefix while building the GaussianModel. That works, but from looking at the parameter keys of the composite model it seems like there is a duplication of parameters -- and smells of a bug. 

Here's my system information:
```
Python: 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0]
lmfit: 0.9.11, scipy: 1.1.0, numpy: 1.14.5, asteval: 0.9.12, uncertainties: 3.0.2, six: 1.11.0
```

**Comment by achennu** [comment]
Having looked through the code, I suspect that the issue  is in the `_parse_params` of the composite model?

https://github.com/lmfit/lmfit-py/blob/6c87262fcfd3c361b197c6769852f76366113246/lmfit/model.py#L964-L977

**Comment by newville** [comment]
@achennu I am most confused by how is it possible that you read all the instructions and still asked a question using Github Issues instead of using the mailing list. 

I think the short answer (as, again this is a question that should be on the mailing list) is "resetting the prefix of a model after it is created is likely to cause problems.  Don't do that".

**Comment by achennu** [comment]
Hi @newville , I'm also confused by why you're so so heavy-handed in your reply, for what is clearly a failing in the software. 

To be clear: I did not have a "how to do this?" questions. It *is* a bug. Ghost parameters are created, with and without a prefix. This is clearly demonstrated in my example.  Your "short answer" is also not reflected in the documentation, nor in the docstring of the `prefix` property. So the logical step would be to either change the documentation, the docstrings or fix the logic of the prefix parameter.

The illogical step is to browbeat submissions. It's a pity the quality of the source code does not show up in the quality of this repo's management.

Good luck
