### ISSUE TITLE
Allow precision in report

### ISSUE THREAD

**Issue by nmearl** [lmfit/lmfit-py#50]
It's not apparently obvious if this exists, but in several cases the report lists parameters as 0.000000 because they are so small. Should there be a way to feed a precision value, or have the output be in scientific format?

**Comment by tritemio** [comment]
An alternative is using the `Parameters.pretty_print` method which allows to specify precision (i.e. number of digits) and format (i.e. scientific, floating point, etc).

The default format `g` (standard python numeric format, mutated from C printf) is floating point for numbers that can be represented with few digits and exponential notation for larger (or smaller) numbers.

For example, you can specify to always use the scientific (i.e. exponential) notation passing 

```
params.pretty_print(fmt='e')
```

Also the `precision` argument dictates the number of printed digits.

 See `Parameters.pretty_print` docs [here](http://lmfit.github.io/lmfit-py/parameters.html?highlight=pretty_print#lmfit.parameter.Parameters.pretty_print).

**Comment by newville** [comment]
@tritemio   yeah, that's a good point about `Parameters.pretty_print`. 

I think this issue  must not have been a very high priority ;).  It really wouldn't be too hard to add `precision` to `fit_report`, but I don't think after switch to ".g" formatting that we haven't heard an actual complaint about the formatting.

Maybe fix? Maybe close? Maybe document?

**Comment by tritemio** [comment]
Given we now mention pretty_print in the documentation (see #371) it would close this. Can be reopened if/when somebody complains.
