### ISSUE TITLE
should report if errorbars is False

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#521]
The fit reports should probably be explicit about whether or not uncertainties were calculated, and even why they may not have been calculated.

**Comment by reneeotten** [comment]
I don't have big objections to add this, but also no real interest in doing so ;) I would say it's quite obvious: if there are no uncertainties reported it means that they were not calculated. For the reasons **why** this could be the case, I think referring to the description in [the manual](https://lmfit.github.io/lmfit-py/fitting.html#goodness-of-fit-statistics) would suffice.

**Comment by newville** [comment]
@reneeotten I'm willing to try to add this.  I don't think it's a high priority, but I can see the benefit of having better reporting about error bars.

**Comment by reneeotten** [comment]
addressed by merging of PR #543
