### ISSUE TITLE
new algorithms in SciPy v1.2

### ISSUE THREAD

**Issue by reneeotten** [lmfit/lmfit-py#527]
Two new optimization algorithms (```dual_annealing``` and ```shgo```) are introduced in SciPy v1.2. I think these should be supported in lmfit as well - opinions?

The algorithms are described as follows in the SciPy release notes:

```dual_annealing``` (and ```shgo``` below) is a powerful new general purpose global optizimation (GO) algorithm. ```dual_annealing``` uses two annealing processes to accelerate the convergence towards the global minimum of an objective mathematical function. The first annealing process controls the stochastic Markov chain searching and the second annealing process controls the deterministic minimization. So, dual annealing is a hybrid method that takes advantage of stochastic and local deterministic searching in an efficient way.

```shgo``` (simplicial homology global optimization) is a similar algorithm appropriate for solving black box and derivative free optimization (DFO) problems. The algorithm generally converges to the global solution in finite time. The convergence holds for non-linear inequality and equality constraints. In addition to returning a global minimum, the algorithm also returns any other global and local minima found after every iteration. This makes it useful for exploring the solutions in a domain.

**Comment by newville** [comment]
@reneeotten  I agree!

**Comment by reneeotten** [comment]
I have not forgotten about this... Some of it works already, but there are some issues left with handling of the bounds and calculating uncertainties with numdifftools. Hopefully a PR that adds these algorithms soon-ish!

**Comment by newville** [comment]
@reneeotten OK, that's fine with me 

I was just noticing how many things have changed in the last few months.  Should we plan on tagging/releasing 0.9.13 soon, maybe once the current round of PRs and issues are worked out? FWIW, I'm not 100% sure of what to do for #534.

Maybe we could aim for releasing 0.9.13 by April 1?  Or are we ready to just call this 1.0?  Maybe call this '0.9.13' and then release '1.0' that drops support for Python 2?   I do not have a strong preference, but it does seem like the API has been stable for several releases so that we really are at 1.0.

**Comment by reneeotten** [comment]
@newville we can certainly push a new release - beginning of April seems reasonable. If possible we include ```shgo``` and ```dual_annealing```, otherwise that can be released when ready. I'll take a closer look at the issue you mentioned, I haven't really followed what's going on closely...

Regarding a final release for Python 2: I would be in favor of releasing a version that requires the 1.2.x LTS series of ```scipy``` and is feature-complete with respect to the algorithms present there (i.e., ```shgo``` and ```dual_annealing``` should be there). That would be a bit of a jump in requirements, but I think that's worth it as we probably can clean-up the code a bit. Ideally we should also increase our test-coverage (and update it fully to ```pytest```); we would then have an excellent starting point to move forward with PY3-only releases. Perhaps that would be a good moment to call it  "1.0" and move on with "1.1" with clean-up for PY3-only and new features? BTW, do you intend to backport potential bug fixes to the PY2-release or not? Just a few thoughts, perhaps you want to bring this up on the mailinglist as well?

**Comment by reneeotten** [comment]
both the ```shgo``` and ```dual_annealing``` algorithms are now supported in ```lmfit```. Please give them a try and let us know if you find any issues with the implementation.
