### ISSUE TITLE
should delay import of matplotlib.pyplot

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#528]
OK, this is admittedly something of a corner case, and I am not certain of the right approach.   I am going to try to describe the problem in full below, but suggest a simple solution first.   That is, I propose that we delay `import matplotlib.pyplot as plt` in `model.py` until as late as possible.  That is `import model` should try to `import matplotlib` but not `pyplot`, and the import of `pyplot` should happen explicitly in the routines that use `plt`.  I know that "imports inside functions" are generally frowned upon, but importing `pyplot` can impact how an application behaves, and it should not matter the order in which one a) imports lmfit  and b) sets the matplotlib backend.   Currently, it does.

I believe the problem is limited to Anaconda Python on MacOS and related to their lack of a framework build.  

If a library (let's call it LmFitWrapper) that imports lmfit is used in an app that wants to use the matplotlib `WXAgg` backend (or, I believe `MacOSX`), the app must a) use `pythonw`, and b) ensure the mpl backend is set *before* import lmfit.    But, setting the backend to "WXAgg" within the LmFitWrapper library would then mean that library *cannot* be used in a Jupyter qtconsole -- it will crash the Jupyter kernel as that (understandably, but weirdly) does not run with `pythonw`.   

This is entirely a problem with Anaconda Python not supporting MacOS framework builds, and secondly a very weird behavior of Python Qt *not* requiring `pythonw`.   Anyway, the result is that having `import matplotlib.pyplot` in a library like lmfit means that it more or less *has* to choose a matplotlib backend.

**Comment by reneeotten** [comment]
I personally don't use Anaconda on macOS, but have heard about issues with Framework builds when doing so. If PR #529 fixes the problem, I seen no harm in doing that (fix seems easy enough and not worthwhile to explore other approaches).

**Comment by reneeotten** [comment]
addressed by merging PR #529.
