### ISSUE TITLE
Parameters do not get passed properly when performing a re-fit with the ModelResult.fit() method.

### ISSUE THREAD

**Issue by wholden** [lmfit/lmfit-py#530]
#### Description
Parameters do not get passed properly when performing a re-fit with the ModelResult.fit() method.

After performing a fit and getting a ModelResult output, if the parameters are changed and `ModelResult.fit(params=changedparams)` is called, the ModelResult is unaffected.

###### Version information
Python: 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]

lmfit: py, scipy: 1.0.0, numpy: 1.15.4, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0

###### A Minimal, Complete, and Verifiable example
Can't attach jupyter notebooks, so instead attached PDF of jupyter notebook with the below example:
[LMFIT_RefitBugExample.pdf](https://github.com/lmfit/lmfit-py/files/2757032/LMFIT_RefitBugExample.pdf)

```
import lmfit
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np

## Take a single gaussian
gaussian = norm(loc=0, scale=1)
x = np.arange(-10, 10, 0.1)

plt.plot(x, gaussian.pdf(x))
plt.show()

## Fit with unconstrained parameters
gaussianmodel = lmfit.models.GaussianModel()
gaussianpars = gaussianmodel.make_params()
out = gaussianmodel.fit(gaussian.pdf(x), params=gaussianpars, x=x)

plt.plot(x, gaussian.pdf(x), label='data')
plt.plot(x, out.eval(x=x), label='fit')
plt.legend()
plt.title('Initial Fit')
plt.show()

## Try constraining a parameter and re-fitting with same fit output
gaussianpars['sigma'].set(value=2, vary=False)

# I expect that this should re-fit with the changed parameters and 
# update the ModelResult in the 'out' variable
out.fit(params=gaussianpars) 

##Plotting, we see there was no change in the fit
plt.plot(x, gaussian.pdf(x), label='data')
plt.plot(x, out.eval(x=x), label='fit')
plt.legend()
plt.title('No change in fit despite changing params')
plt.show()

##We get what we expect if we regenerate the fit output from the original model
out = gaussianmodel.fit(gaussian.pdf(x), params=gaussianpars, x=x)

plt.plot(x, gaussian.pdf(x), label='data')
plt.plot(x, out.eval(x=x), label='fit')
plt.legend()
plt.title('Works as expected\nchange in fit after changing params')
plt.show()

##Though I realize that perhaps the expected way for a user to change
##parameters and re-fit would be like this:
out.params['sigma'].set(value=2, vary=False)
out.fit()
```

###### A possible fix:

If I understand the intended functionality properly, I think this is a simple fix.  It looks like in the ModelResult.fit definition, the supplied params don't get passed to the minimize call.  
I think one fix would be to modify line 1355 of model.py as follows:
current:
` _ret = self.minimize(method=self.method)`
possible fix:
` _ret = self.minimize(method=self.method, params=params)`

I tested this with my simple example and it displayed my expected behavior.

**Comment by newville** [comment]
@wholden  It is intentional that the input `Parameters` (your `gaussianpars`) are not updated by the fit.  The updated, best-fit Parameters are held in `out.params`.   That allows you to have both input and output parameters (and any intermediate Parameters as you make changes to the fit).

**Comment by wholden** [comment]
@newville Yes the original `gaussianpars` variable is unaffected.  In this case, after the first fit, I modified `gaussianpars` and passed it to `ModelResult.fit(params=gaussianpars)` expecting that by passing the modified version, it would update the fit, but it did not.

**Comment by newville** [comment]
@wholden   Sorry, but huh?  Why are you using `ModelResult.fit()` at all? 

As you must have read when submitting this Issue, we strongly encourage starting with questions on the mailing list instead of raising Issues.

**Comment by newville** [comment]
@wholden   

> @newville I was using ModelResult.fit() because I wanted to re-perform a fit from the output of a previous fit after making a tweak in the parameters. The docstring seemed to indicate that was the intended purpose: ModelResult.fit """Re-perform fit for a Model, given data and params.

The recommended way would be

     start_params = model.make_params()
     ...
     result1 = model.fit(ydata, start_params, x=x)
     # now tweak those.... 
     result1.params['sigma'].value = 2
     result1.params['sigma'].vary = False
     result2 = model.fit(ydata, result1.params, x=x)

Now you have `start_params`, `result1.params`, and `result2.params`.

**Comment by wholden** [comment]
@newville Thank you, yes perhaps that's the best way.  I realize now this is not the type of issue that should be posted to the Github.  Apologies for the false alarm.

The layout of the code and the docstring for ModelResult.fit made me think that it was natural to do it the way that I was describing, but perhaps it's better to stick to a consistent usage.  I'll post to the mailing list, and perhaps the only change required so that someone doesn't do it the way I tried would be a change in the docstring.

**Comment by newville** [comment]
@wholden FWIW, I do think that `ModelResult.fit()` usage ought to work...  Does it not?

**Comment by wholden** [comment]
@newville 
It does not work if you try to manually supply the parameters, for instance by manually changing the start_params:

The following would not match the behavior of the recommended way:
```
 start_params = model.make_params()
 ...
 result1 = model.fit(ydata, start_params, x=x)
 # now tweak those in the start_params
 start_params .params['sigma'].value = 2
 start_params .params['sigma'].vary = False
#now pass tweaked start_params to do the refit
result1.fit(params=start_params)
#no change result1
```
