### ISSUE TITLE
(Voigt)Model.guess() does not correctly update all parameter values

### ISSUE THREAD

**Issue by reneeotten** [lmfit/lmfit-py#539]
#### Description

It appears that some parameters with an expression are not updated correctly after ```<Model>.guess()```, at least for ```fwhm``` in the VoigtModel using the peak data in ```examples/test_peak.dat```.  The first time one tries to use parameter values it is ```nan```; it gets updated after the first call to ```pretty_print()``` (see example below); this should not be the case.

I am not sure if this is an issue for other models, I tried ```GaussianModel``` and ```LorentzianModel``` with the same data and that seems to work. I only looked briefly at the  code in model(s).py and am not too familiar with it... perhaps @newville has an immediate idea where this comes from? Otherwise I can investigate a bit more.

###### A Minimal, Complete, and Verifiable example

```
from numpy import loadtxt, sqrt
from lmfit.models import VoigtModel

data = loadtxt('test_peak.dat')
x = data[:, 0]
y = data[:, 1]

mod = VoigtModel()
pars = mod.guess(y, x=x)

pars.pretty_print()
print("\npars['fwhm'] = {}".format(pars['fwhm'].value))
```

Output:
```
Name          Value      Min      Max   Stderr     Vary     Expr Brute_Step
amplitude     65.43     -inf      inf     None     True     None     None
center         9.25     -inf      inf     None     True     None     None
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/asteval/astutils.py:193: RuntimeWarning: invalid value encountered in double_scalars
  return a + b
fwhm            nan     -inf      inf     None    False 1.0692*gamma+sqrt(0.8664*gamma**2+5.545083*sigma**2)     None
gamma        0.8775     -inf      inf     None    False    sigma     None
height        15.56     -inf      inf     None    False (amplitude/(sigma*sqrt(2*pi)))*wofz((1j*gamma)/(sigma*sqrt(2))).real     None
sigma        0.8775        0      inf     None     True     None     None

pars['fwhm'] = 3.160132535010088
```

Inverting the order gives:
```
pars = mod.guess(y, x=x)
print("\npars['fwhm'] = {}\n".format(pars['fwhm'].value))
pars.pretty_print()
print("\n** second call to pars.pretty_print(): **")
pars.pretty_print()
```

```
pars['fwhm'] = nan

Name          Value      Min      Max   Stderr     Vary     Expr Brute_Step
amplitude     65.43     -inf      inf     None     True     None     None
center         9.25     -inf      inf     None     True     None     None
fwhm            nan     -inf      inf     None    False 1.0692*gamma+sqrt(0.8664*gamma**2+5.545083*sigma**2)     None
gamma        0.8775     -inf      inf     None    False    sigma     None
height        15.56     -inf      inf     None    False (amplitude/(sigma*sqrt(2*pi)))*wofz((1j*gamma)/(sigma*sqrt(2))).real     None
sigma        0.8775        0      inf     None     True     None     None

** second call to pars.pretty_print(): **
Name          Value      Min      Max   Stderr     Vary     Expr Brute_Step
amplitude     65.43     -inf      inf     None     True     None     None
center         9.25     -inf      inf     None     True     None     None
fwhm           3.16     -inf      inf     None    False 1.0692*gamma+sqrt(0.8664*gamma**2+5.545083*sigma**2)     None
gamma        0.8775     -inf      inf     None    False    sigma     None
height        15.56     -inf      inf     None    False (amplitude/(sigma*sqrt(2*pi)))*wofz((1j*gamma)/(sigma*sqrt(2))).real     None
sigma        0.8775        0      inf     None     True     None     None
```

###### Version information

Python: 3.7.2 (default, Jan  6 2019, 12:34:03)
[Clang 10.0.0 (clang-1000.11.45.5)]

lmfit: 0.9.12 (and current master), scipy: 1.2.1, numpy: 1.16.2, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0

**Comment by newville** [comment]
@reneeotten Hm, it looks like that must be common to lots of models with a `guess()` method.
I think that adding a call to `pars.update_constraints()` will probably do the trick.  I'll look into that....

**Comment by chabanr** [comment]
I apologize if this is the wrong place. This is my first time commenting on a project. 

Hey @newville I think that by adding the call to pars.update_constraints() it created a case that creates an error if you are only using y-data. 

from lmfit.models.GaussianModel.guess()

line 52 in lmfit.models.py -> guess_from_peak() will return (1.0, 0.0, 1.0) if no x-data is provided. This causes an error because a tuple object has no attribute 'update_constraints'. 

I believe instead of returning a tuple it can be fixed by returning a parameters object. 
replace line 52 with: "return model.make_params(amplitude=1.0, center=0.0, sigma=1.0)"

But I guess I am little confused why it doesn't try to guess the parameters a little better if only y-data is provided? 

Thank you!

**Comment by newville** [comment]
Well, you *could* read the docs about where to ask for help.  Certainly, commenting on closed issues is an odd way to start.  We do have a mailing list.

I do not what `Model.guess()` supposed to do with "only y data".  That doesn't make much sense to me, but I may not understand what you are trying to do.
