### ISSUE TITLE
pre-commit weirdness

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#541]
@reneeotten  I'm working on #537, and getting odd messages from pre-commit:

```
rabbit:lmfit-py>rm -rf ~/.cache/pre-commit/
rabbit:lmfit-py>git commit -m "add message about numdifftools not being installed when uncertainties have not been calculated"  lmfit/printfuncs.py
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for local:rstcheck,sphinx.
[INFO] Initializing environment for https://github.com/pre-commit/pygrep-hooks.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/newville/.cache/pre-commit/repoomr555ce/py_env-python3.6/bin/python3.6', '/home/newville/.       cache/pre-commit/repoomr555ce/py_env-python3.6/bin/pip', 'install', '.')
Return code: -11
Expected return code: 0
Output: (none)
Errors: (none)

Check the log at /home/newville/.cache/pre-commit/pre-commit.log
rabbit:lmfit-py>cat /home/newville/.cache/pre-commit/pre-commit.log
An unexpected error has occurred: CalledProcessError: Command: ('/home/newville/.cache/pre-commit/repoomr555ce/py_env-python3.6/bin/python3.6', '/home/newville/.cache/pre-commit/repoomr555ce/py_env-python3.6/bin/pip', 'install', '.')
Return code: -11
Expected return code: 0
Output: (none)
Errors: (none)

Traceback (most recent call last):
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/main.py", line 291, in main
    return run(args.config, store, args)
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/commands/run.py", line 271, in run
    install_hook_envs(hooks, store)
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/languages/python.py", line 163, in install_environment
    prefix, ('pip', 'install', '.') + additional_dependencies,
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/languages/helpers.py", line 18, in run_setup_cmd
    cmd_output(*cmd, cwd=prefix.prefix_dir, encoding=None)
  File "/home/newville/anaconda36/lib/python3.6/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/home/newville/.cache/pre-commit/repoomr555ce/py_env-python3.6/bin/python3.6', '/home/newville/.cache/pre-commit/repoomr555ce/py_env-python3.6/bin/pip', 'install', '.')
Return code: -11
Expected return code: 0
Output: (none)
Errors: (none)

```

I can't see where the problem is coming from.   FWIW,  `pip install .` works for me.

If I try to alter `.pre-commit-config.yaml` to try to figure that out, it complains that this file is 'unstaged' and (incorrectly) says it should be added to the repo.   That leaves me kind of stuck without being able to commit to development branches.  It seems silly to have to mess around with the pre-commit config, but any ideas what might be going wrong here?

**Comment by reneeotten** [comment]
@newville I don't know, haven't seen that before... it's possible that your configuration is in an weird state.

Perhaps try ```pre-commit gc```, ```pre-commit clean``` , and then try ```pre-commit install```. That should, hopefully, get you back in a correct state.

**Comment by newville** [comment]
@reneeotten Yeah, I tried all those.   `pre-commit install-hooks` is what is generating the error for me. I can do `pre-commit autoupdate`, which moved `mirrors-isort` to version 4.3.10, but I can't commit that change...

FWIW, I'm also seeing similar problems on MacOS with `pre-commit install-hooks` and its attempt to use `pip install`.  This complains about

```
Errors: 
    pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
      Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/isort/
      Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/isort/
      Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/isort/
      Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/isort/
      Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/isort/
      Could not find a version that satisfies the requirement isort==4.3.10 (from pre-commit-dummy-package==0.0.0) (from versions: )
    No matching distribution found for isort==4.3.10 (from pre-commit-dummy-package==0.0.0)
    pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
```

Something definitely seems wrong with `pre-commit`. I don't understand it well enough to diagnose it, but I'll keep playing around with it.

**Comment by reneeotten** [comment]
@newville weird indeed.... ```pre-commit``` (version 1.14.4) with Python 3.7 from conda isn't giving any of these issues. The TLS/SSL error shows up all Google; I assume that conda is kind-of self-contained and wouldn't rely on the system its ssl stuff, but am not sure... this seems however a clear issue with ```pip``` and not necessarily with ```pre-commit```.  Did you upgrade to the latest version of pre-commit and is that still giving the same error?

**Comment by reneeotten** [comment]
also do installs work when you use ```pip``` from the virtualenv that pre-commit uses (i.e., /home/newville/.cache/pre-commit/repoomr555ce/py_env-python3.6/bin/pip)?

**Comment by newville** [comment]
@reneeotten Yeah, on MacOS, I was using an Anaconda Python 3.6.8 environment, but packages were up-to-date. including `pre-commit autoupdate`, and that was version 1.14.4.  

I did install a brand new install of Python.org 3.7.2  for MacOS and then `pip install`ed the scipy + more stack onto that, and `pre-commit` worked.    Then switching back to the Anaconda environment seemed to work too.  No idea why.....  I'll try again on Linux tomorrow. 

This is pretty weird and a little discouraging.   I don't really understand why a spell-checker is running `pip install` in the first place, but it appears to be kind of buggy.

**Comment by reneeotten** [comment]
```pre-commit``` will install its commit-hooks in ```~/.cache/pre-commit``` and uses a virtualenv for that so that after the first install of the hooks its not dependent anymore on a specific (system) Python installation. So it makes sense to me that when updating a specific hook to a newer version it will need pip to install that package.

I *think* the issue is with ```pip``` in that virtualenv and, therefore, just happens to show up when you're trying to use ```pre-commit```; but since I cannot reproduce the problem I don't have any "proof". If it doesn't work on your Linux system, can you check what version of pip its using from ```~/.cache/pre-commit/*/```?

**Comment by newville** [comment]
@reneeotten  Yeah, it seems like it is working at the moment on MacOSX and will break as soon as it is able to try to update one of its hooks.

On Linux, using Anaconda Python 3.6.8 that is completely up-to-date, I have `pre-commit` v 1.14.4 that is pip installed. FWIW `venv` is included, `virtualenv` version 16.4.1 is installed, and so is `pipenv` (I don't think I've ever used that one....)   Anyway, if I do
   
```
    cd Codes/lmfit-py
    rm -rf ~/.cache/pre-commit
    pre-commit install
    pre-commit autoupdate
    pre-commit install-hooks
```

the installation of the hooks fails with

```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/newville/.cache/pre-commit/repozf_lnjqm/py_env-python3.6/bin/python3.6', '/home/newville/.cache/pre-commit/repozf_lnjqm/py_env-python3.6/bin/pip', 'install', '.')
Return code: -11
Expected return code: 0
Output: (none)
Errors: (none)

Check the log at /home/newville/.cache/pre-commit/pre-commit.log
```

That `.cache/pre-commit/repozf_lnjqm` folder (for some virtualenv, I presume) has a README.md and setup.py file and nothing else.   And that `pre-commit.log` file says

```
pre_commit.util.CalledProcessError: Command: ('/home/newville/.cache/pre-commit/repozf_lnjqm/py_env-python3.6/bin/python3.6', '/home/newville/.cache/pre-commit/repozf_lnjqm/py_env-python3.6/bin/pip', 'install', '.')
```

So something appears broken in its creation of a virtual environment.  Again, the fact that a linter is creating virtual environments seems odd to me, but if `pre-commit` is going to do that it appears to need a lot more testing.  I was able to get it to be broken on 2 different systems in a way that it has not been able to recover from without dramatic steps.

**Comment by reneeotten** [comment]
@newville I haven't observed any issues yet with ```pre-commit```, is it stable now for you as well? One thing I see now upon reading your last comment again is that I have never done is ```pre-commit install-hooks```, I always just commit and then if it needs to update/install a hook that happens automatically first. I am not sure what command is run in that case, but looking at ```pre-commit --help```, it says
```
   install-hooks       Install hook environments for all environments in the config file. You may find `pre-commit install  --install-hooks` more useful.
```
perhaps it's using the ```pre-commit install --install-hooks``` and that's somehow causing a difference? 

Anyway, if it works for you now then we can probably just close this issue and consider it indeed as weirdness that hopefully never appears again...

**Comment by newville** [comment]
@reneeotten For me, a clean install and update of Anaconda2018, Python 3.7 followed by `pip install pre-commit` does allow `pre-commit` to work for me on Linux.  I'm not entirely sure what was wrong with Python 3.6.8 + `pre-commit`, but it was definitely failing at trying to install hooks.

I definitely like the idea of running linters on commits, but I have to admit that I am somewhat wary of  `pre-commit`, having been burned twice by it.  I am also a little unsure of some of its practices.  I would rather be told what should be changed (and maybe allow it to be skipped) rather than having the code silently edited on my behalf.    I can easily imagine confusion of the "that's not what I wrote" kind.  But, let's stick with it, I'll try to learn to love it ;)
