### ISSUE TITLE
Support for complex signatures

### ISSUE THREAD

**Issue by agoose77** [lmfit/lmfit-py#570]
Currently we use `inspect.getfullargspec` which disallows following wrappers
https://github.com/lmfit/lmfit-py/blob/2ae2fc9e3dd6137d16cfa05474a34f33433e11ec/lmfit/model.py#L478

Would it be possible to use inspect.signature directly (and use the [backport](https://funcsigs.readthedocs.io/) for python2) which would permit the use of wrapped callables e.g. using `numba`.

**Comment by newville** [comment]
@agoose77  Oh, I wasn't aware of the Funcsigs project to backport `inspect.signature` to Python2.  That would definitely be useful.  Using `inspect.signature` would have real advantages.  For example, we could then make decorators that check for and possibly act on invalid inputs/outputs (nans, infs, etc), and use these in all the examples.  That might better document and show users how to deal with such problems.

But I think (and hope) we're close to dropping support for Python2 soon (not for 0.9.14, but perhaps after that).   We could consider adding the dependency on Funcsigs for 0.9.14 and then drop for 1.0.
See #544 for more on this (will update proposal there soon).

**Comment by agoose77** [comment]
Great news! I'm currently patching `getfullargspec` to follow wrappers, so it would be nice to drop that :)

**Comment by reneeotten** [comment]
Is anyone working on this? If not, I will take a look and see whether we can add this before releasing 0.9.15.

@agoose77 could you share a minimal, self-contained example that does not work with ```getfullargspec```, but should work when we switch to ```inspect.signature```?

**Comment by newville** [comment]
@reneeotten I have not done anything about this yet.  If you have the time and will, don't hold back.   

We could put this in 0.9.14 if it is ready, but either way is fine with me.

**Comment by reneeotten** [comment]
> We could put this in 0.9.14 if it is ready, but either way is fine with me.

right, that's what I meant to say... ;)

**Comment by agoose77** [comment]
This is a bit of an obscure test case, but it's used because the Numba `njit` decorator is a `methoddescriptor`, which getfullargspec doesn't support unless it defines a `__text_signature__` method (whilst signature does)

```python
import lmfit
import numba

@numba.njit
def linear(x, a, b):
    return a*x + b

model = lmfit.Model(linear)
```

**Comment by reneeotten** [comment]
@newville I looked a little, but to be honest am a bit stuck about what we would need from the ```inspect.signature``` output. I have not really looked much at this part of the code... and if the plan is still to release a new version in about a week from now, I don't think this is going to happen from my side. I will try to finish the "examples PR", but if you want to take over this issues feel free ;)

**Comment by newville** [comment]
@agoose77 @reneeotten I'll look at this and see if I can get it done soon.  I suppose it could wait until 0.9.15.

**Comment by Tillsten** [comment]
@agoose77 Maybe you could post your wrapper? Even it is not a full fledged PR, it could reduce the time to built one.

**Comment by Tillsten** [comment]
IRC only the following part of `model.py` needs to be adapted:
```python
    def _parse_params(self):
        """Build parameters from function arguments."""
        if self.func is None:
            return
        if hasattr(self.func, 'argnames') and hasattr(self.func, 'kwargs'):
            pos_args = self.func.argnames[:]
            kw_args = {}
            for name, defval in self.func.kwargs:
                kw_args[name] = defval
            keywords_ = list(kw_args.keys())
        else:
            try:  # PY3
                argspec = inspect.getfullargspec(self.func)
                keywords_ = argspec.varkw
            except AttributeError:  # PY2
                argspec = inspect.getargspec(self.func)
                keywords_ = argspec.keywords


            pos_args = argspec.args
            kw_args = {}
            if argspec.defaults is not None:
                for val in reversed(argspec.defaults):
                    kw_args[pos_args.pop()] = val

**Comment by agoose77** [comment]
I have just been intrusively patching atm, e.g '''python 
def _patch_lmfit_inspect():
    """Patch `inspect.getfullargspec` to support wrapped callables"""
    import inspect
    from functools import wraps

    _getfullargspec = inspect.getfullargspec

    @wraps(_getfullargspec)
    def getfullargspec(func):
        if hasattr(func, "__wrapped__"):
            return getfullargspec(func.__wrapped__)
        return _getfullargspec(func)

    inspect.getfullargspec = getfullargspec


_patch_lmfit_inspect()
'''

**Comment by reneeotten** [comment]
> IRC only the following part of `model.py` needs to be adapted:

@Tillsten sure... of course the question is not *which part* of the code needs to be adapted it's *how* to adapt it. We don't want to patch ```getfullargspec```,  instead we should go for the long-term solution and switch to ```inspect.signature``` as suggested by the OP. I tried to do that and failed given the amount of time I've been able to spend on it; if you have ideas on how to do it great - please submit a PR.

**Comment by newville** [comment]
@agoose77 @Tillsten @reneeotten  I'm working on a PR to use `inspect.signature`, modifying exactly the part of the code Till points to.   And, I think the example of using a `numba.jit` decorator is a good test, though I'm not 100% sure we want to add `numba` as a dependency just for testing.  

Anyway, I think I'm close....

**Comment by Tillsten** [comment]
@reneeotten Sorry for my misjudgement. From my very brief look at both the inspect documentation and the lmfit code I wrongly concluded it was the lmfit side where the problem was and wanted to give a pointer.

**Comment by newville** [comment]
@Tillsten Oh, you were completely right -- we are currently using `getargspec` when we should be using `signature`.  That change is sort-of Py3 only (there is a backport, as the the OP pointed out), so we've been slow to make the change.  But also we're close to dropping all support for Py2 anyway, so it's time.   Anyway, I think #576 will do that (though it might need a tweak or two).

**Comment by reneeotten** [comment]
> @reneeotten Sorry for my misjudgement. From my very brief look at both the inspect documentation and the lmfit code I wrongly concluded it was the lmfit side where the problem was and wanted to give a pointer.

no worries @Tillsten and I didn't intend to sound ungrateful for suggestions/pointers, always much appreciated! In this case, I already knew what to change, just not how ;)

**Comment by newville** [comment]
@agoose77 @reneeotten @Tillsten  this should now be fixed in master.  We have one simple test of a wrapper that does not use numba.jit, but did I test it with a simple numba.jit function like the original message here too.  

I'll close this, but feel free to reopen if there is something not working.
