### ISSUE TITLE
`iter_cb` not called with `emcee`

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#590]
A colleague asked why `iter_cb` wasn't called with `emcee`.    

Here's a simple script to reproduce:

    import numpy as np
    import lmfit
    x = np.linspace(1, 10, 250)
    np.random.seed(0)
    y = 3.0 * np.exp(-x / 2) - 5.0 * np.exp(-(x - 0.1) / 10.) + 0.1 * np.random.randn(x.size)

    p = lmfit.Parameters()
    p.add_many(('a1', 4.), ('a2', 4.), ('t1', 3.), ('t2', 3., True))

    def residual(p):
        v = p.valuesdict()
        return v['a1'] * np.exp(-x / v['t1']) + v['a2'] * np.exp(-(x - 0.1) / v['t2']) - y

    def cb_func(params, iter, residue):
        print('Step ', iter, np.sum(residue**2))

    p.add('__lnsigma', value=np.log(0.1), min=np.log(0.001), max=np.log(2))
    res = lmfit.minimize(residual, method='emcee', nan_policy='omit', 
                                      burn=300, steps=1000, thin=20,
                                      params=p, is_weighted=False, iter_cb=cb_func)
    lmfit.report_fit(res.params)

It looks like `emcee` calls `self.userfcn()` but does not check for and call `iter_cb`.  
Why isn't it just calling `self.__residual()`?

**Comment by reneeotten** [comment]
Yes, that is a good point. I don’t see an obvious reason why it wouldn’t be able to call self._residual, but perhaps @andyfaff remembers why it was done in this way? 

We’ll need to take a closer look at this method anyway as with the latest emcee release (v3.0.0) it doesn't work anymore. The PTSampler was removed and put into a separate project; I haven’t looked in detail if we can move away from using that specific sampler or alternatively use the fork.

**Comment by newville** [comment]
@reneeotten Hm, yeah I'm not 100% sure why `emcee` dropped `PTSampler`. I would say we follow suit and just drop  `ntemps >  1` case: support the keyword argument for back-compatible API but warn if the user sets `ntemps>1` and use EnsembleSampler.   

It is also weird that `_lnprior` (which I believe we can drop if dropping `PTSampler`) and `_lnpost` are functions, not methods.  That would allow calling `self.__residual`, and so use callbacks and count function evaluations.

Anyway, I feel like we sort of need to own the use of `emcee` a little better.  So, I think I'd like to try to fix this for the next release.  And for that, simplifying the use of `emcee` is probably a good idea.

**Comment by andyfaff** [comment]
If there are N walkers then the log probability needs to be calculated N times per step. If one uses `__residuals` instead of userfcn directly then `iter_cb` will be called N times per iteration rather than once. Plus, what does `iter_cb` mean for a MCMC run? One would have to process the chain statistics to get the 'current' parameter values. I think that would mean a lot of processing - it's straightforward to do if there are no constraints, but as soon as there are constraints it takes a while to calculate chain statistics. It's possible  to do callbacks with `emcee`, (e.g. write out sampler state), but it would require a little bit of code rewrite in lmfit-py and a rethink on what a callback should look like.
Plus, one doesn't want to `apply_bounds_transformation` at any point during the sampling. There may also be issues parallelising with `__residuals` (see next comment)

`_lnprior` and `_lnpost were separate functions to permit parallelisation using `multiprocessing.Pool.map`. In Python2.7 it used to be impossible to pickle an instance method, so separate functions had to be used. With non parallel tempered `emcee` then only a log-post function needs to be supplied (in which log-prior and log-like are combined). parallel tempering used to require separate log-prior and log-like functions. I think it probably makes sense to retain log-prior, log-like and log-post functions, in whatever form (function or method) is chosen. Remember that if the log-prior is impossible (-np.inf), then there's no need to calculate the log-like. At which point there's no need to increment the number of function evaluations.

**Comment by newville** [comment]
@andyfaff 

> If there are N walkers then the log probability needs to be calculated N times per step. If one uses __residuals instead of userfcn directly then iter_cb will be called N times per iteration rather than once. Plus, what does iter_cb mean for a MCMC run?

"Iteration" and "Step" are sort of poorly defined terms, or at least "algorithm-dependent". In `lmfit`, the iteration callback is called for every evaluation of the user-supplied objective function.  That's why it is in `self.__residual`.


> One would have to process the chain statistics to get the 'current' parameter values. I think that would mean a lot of processing - it's straightforward to do if there are no constraints, but as soon as there are constraints it takes a while to calculate chain statistics. It's possible to do callbacks with emcee, (e.g. write out sampler state), but it would require a little bit of code rewrite in lmfit-py and a rethink on what a callback should look like.

Nah, what is important is how many times the objective function is called.  Anything else is method-dependent and probably expects too much understanding of the algorithm by the user, 

> Plus, one doesn't want to apply_bounds_transformation at any point during the sampling. 

I don't really agree.  Currently `Minimize.emcee` stores and removes user-defined bounds on Parameters and then uses those stored values to tell the Sample that values sent in outside of those bounds are impossible (log-prop is -Inf).  Using bounds transformations would mean that values outside the bounds would never get sent to the objective function. 

>There may also be issues parallelizing with __residuals (see next comment)
>
> _lnprior and _lnpost were separate functions to permit parallelisation using multiprocessing.Pool.map. In Python2.7 it used to be impossible to pickle an instance method, so separate functions had to be used. 

Pickle will break with anything remotely complicated.   This is a problem with multiprocessing, not a problem with lmfit.   If using a class method as a residual function breaks `Minimizer.emcee`, then we should just deprecate it -- it will not be useful to us. 

> With non parallel tempered emcee` then only a log-post function needs to be supplied (in which log-prior and log-like are combined). parallel tempering used to require separate log-prior and log-like functions. I think it probably makes sense to retain log-prior, log-like and log-post functions, in whatever form (function or method) is chosen. Remember that if the log-prior is impossible (-np.inf), then there's no need to calculate the log-like. At which point there's no need to increment the number of function evaluations.

Hm, maybe.   Using `Minimizer.__residual` and `Minimizer.penalty` would greatly simplify the emcee wrapping and make it work consistently with the rest of `lmfit`.   Since `emcee` has dropped `PTSampler`, I think we will have to follow suit.

**Comment by reneeotten** [comment]
@andyfaff thank you for your insights, I’m not all that familiar with the emcee code and will need to take a closer look at it. 

What is your opinion/experience regarding the (removal of the) PTSampler - would you just drop this as well in lmfit or is there a significant benefit of keeping that sampler around?

**Comment by andyfaff** [comment]
In my project I use both a lot. Usage of them both is very similar to the existing lmfit-py interface, but a little bit of hoop jumping is needed (e.g. the MCMC chain shapes are different in ptemcee and emcee3).
PTSampler is useful in model selection (thermodynamic_log_evidence), and for examining strongly multimodal systems. It typically also has a smaller autocorrelation time when sampling.
I would try to keep both.

**Comment by newville** [comment]
@andyfaff  How would you propose that we keep `PTSampler`?  I thought it was no longer supported in `emcee`.  I don't know the details of why they dropped this, but I imagine they had a reasons.  I would not want to require an older version of `emcee`, or maintain that code ourselves.

I don't know how ptemcee might be different from emcee (had not heard of ptemcee actually), but if "hoop jumping" is needed, I'm not sure how we would support this.  Maybe that is possible, but I don't know what those steps would be.  Does `ptemcee` have a drop in replacement for `emcee.PTSampler`?  Do we want to allow that we use that if `ptemcee` is installed?   How well supported is `ptemcee`?

For me, the question here is not "what an expert user might do" to use MCMC methods, but what can we support in lmfit.  I would be comfortable saying that we support `emcee.EnsembleSample` if `emcee` is installed, but also saying that we may not easily support all possible options.

**Comment by newville** [comment]
fixed with #600.
