### ISSUE TITLE
BUG: lmfit.conf_interval does not work with len(p_names) = 1

### ISSUE THREAD

**Issue by Tillsten** [lmfit/lmfit-py#597]
#### Description
The lmfit confidence calculation fails when len(p_names) < 2. This is due to bug in the counting of the free variables: Instead counting all parameters where vary is True, it counts only the one which are in p_names.

**Comment by newville** [comment]
@Tillsten Oh, thanks.  We should fix that. And maybe add a test of `conf_intervals` with 1 variable.

**Comment by Tillsten** [comment]
Yeah, it almost a one-liner. I am just on a machine where I don't have a good dev environment.
