### ISSUE TITLE
Git Hickup

### ISSUE THREAD

**Issue by Tillsten** [lmfit/lmfit-py#603]
Sorry for that, I mistakenly did some master merge on origin. Can somebody fix that for me?

**Comment by Tillsten** [comment]
Wrong Commit: b77e781d43eccad18ff5d4a55eeb868085cfbc96

**Comment by reneeotten** [comment]
> Sorry for that, I mistakenly did some master merge on origin. Can somebody fix that for me?

there is nothing to fix; once you've pushed to ```master``` it's done... But, in reality nothing has (or should have) changed since you just pushed change again that are already in ```master```.  But this is why you should always work on a branch and do stuff like ```git rebase master/upstream``` to avoid ugly-looking merge commits.

**Comment by reneeotten** [comment]
so you did actually add one example file ```example_detect_outliers.py```, that looks fine except for a few style and ```flake8``` issues. Can you please address those in the PR that you opened?

**Comment by newville** [comment]
@Tillsten @reneeotten No worries from me. We could always reset the HEAD if we need to, or go back and rewrite the history.   But I'm not sure we actually need to do anything here.

**Comment by Tillsten** [comment]
I think a correction is still possible, see [Link](http://christoph.ruegg.name/blog/git-howto-revert-a-commit-already-pushed-to-a-remote-reposit.html). Basically just force push into the origin/master. But again, the evidence is against my git knowledge... 

I am not really sure if the example is necessary. It is basically the prestep to add bootstrapping to lmfit, at least as an example.

**Comment by reneeotten** [comment]
no re-writing on the ```master``` branch please! There is also no reason to do that as the only effect was the addition of an example. Just fix the style errors in the example file (or remove it again in the PR you have opened already). It would be really useful if you'd install the `pre-commit` hooks and/or follow [this](https://github.com/lmfit/lmfit-py/blob/master/.github/CONTRIBUTING.md), that would avoid some of the potential pitfalls.

**Comment by Tillsten** [comment]
Sadly I have bad experenices with pre-commit under windows, but I can try again.
