### ISSUE TITLE
Typo in documentation: "Advanced usage of Expressions in lmfit"

### ISSUE THREAD

**Issue by jkrogager** [lmfit/lmfit-py#615]
Hi,

First of all, thanks for this awesome package! I really love using it.

I was trying to define my own function to use as a constraint for the fit parameters, so I looked at the documentation and found the following:
fitter = Minimizer()
fitter.asteval.symtable['lorentzian'] = mylorentzian

But this gives an error: AttributeError: 'Minimizer' object has no attribute 'asteval'.

After digging around a bit in the source code, I think I found the problem. I believe the user-defined function should be added to the symtable of the Parameters, as follows:
pars = Parameters()
pars._asteval.symtable['lorentzian'] = mylorentzian

I hope this makes sense, if so, could you please update the documentation?

Best regards,
JK

###### Version information
Python: 2.7.17 (default, Dec 23 2019, 21:25:34) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)]

lmfit: 0.9.13, scipy: 1.1.0, numpy: 1.15.1, asteval: 0.9.12, uncertainties: 3.0.2

**Comment by newville** [comment]
@jkrogager  Thanks for catching that!  Will fix.

**Comment by reneeotten** [comment]
fixed in commit 046ebc4

**Comment by reneeotten** [comment]
@newville I am doing some work on the documentation and just noticed that this issue is actually not fixed... You did add an underscore as in `_asteval.symtable` but the Minimizer class does not contain that attribute, it's only present in the Parameters class. 

So either we'll need to update this so that the symbols should be added to `Parameters._asteval.symtable` or you prefer to have it available in the Minimizer class we probably should add `self._asteval = params._asteval`.

**Comment by newville** [comment]
@reneeotten Oh, right.... Yes, I guess that the original doc was "pre v0.9" and is just now totally wrong.  The change has to be made to the Parameters instance. 

I think we should change the doc and not revive the old behavior. There is a test of adding and using a user-defined function in `test_algebraic_constraints.py`, though I guess one can always have more tests!

**Comment by reneeotten** [comment]
> @reneeotten Oh, right.... Yes, I guess that the original doc was "pre v0.9" and is just now totally wrong. The change has to be made to the Parameters instance.
> 
> I think we should change the doc and not revive the old behavior. There is a test of adding and using a user-defined function in `test_algebraic_constraints.py`, though I guess one can always have more tests!

I agree with that. I'll change the documentation and add that to the PR I'm working on now; you can take a look once I've submitted it and see what you think.
