### ISSUE TITLE
optimize with bounded parameters while fit_kws values specified in the external parameter space.

### ISSUE THREAD

**Issue by r-xue** [lmfit/lmfit-py#618]
#### Description

If one sets `initial_simplex` for the minimizer `method='nelder'`, the value will be handed over to `scipy.optimize`, without any transformation, unlike a bounded parameter value. This poses a confusing condition for the underline algorithm when `min`/`max` are set in `Parameters`.

In this specific case, It might be good just ignoring the parameter bounds in `lmfit` (since it's already implicitly defined by `initial_simplex`), or let `lmfit` also transform `initial_simplex` into the internal parameter space?

I have to say this is more like a user problem, but it takes me a while to catch this issue.

**Comment by newville** [comment]
@r-xue re-read the instructions.
