### ISSUE TITLE
confidence interval example in docs is wrong

### ISSUE THREAD

**Issue by jsalsman** [lmfit/lmfit-py#624]
Regarding the example and graphic at https://lmfit.github.io/lmfit-py/model.html#calculating-uncertainties-in-the-model-function

Shouldn't 95% of the observations be inside the shaded area?

Also, why use +/- 3 sigma for a 95% confidence interval? 
https://stats.stackexchange.com/a/377634 says it should be +/- 2 sigma.

P.S. I tried to post this to the mailing list, but Google Groups would only tell me, "There was an error posting the message to the group. Please try again later."

**Comment by newville** [comment]
@jsalsman Well, yes 2-sigma is the ~95% confidence interval.  Is there a place that we say that 3-sigma is 95% instead of ~97.5%?   I'm not seeing that, but perhaps I am not understanding your point.

As for why 97.5 (or 95% or even 68%) of the observations are not within the estimated confidence band,   I would say:  good point.  I'm not 100%sure why that is, but I would guess that it is related to the very low value for chi-square for this fit. 

Did you try posting to the google group more than once?

**Comment by jsalsman** [comment]
Thanks, Mark. 

Sorry, it's not in the docs, but you did write, "for 95% confidence level, you'd want to use sigma=3 here" at https://stackoverflow.com/a/59905810

I think you're right about chi-square. I will get back to you on this. I did try to post to the mailing list several times, each with that same error message, but have not tried today.

**Comment by newville** [comment]
@jsalsman Oh, OK.  I fixed the code comment in the stackoverflow post.

Actually, thinking about this more and the example in the docs:  I'm not sure that enclosing any fraction of the data points should actually be expected here.   That is, what is being shown is the uncertainty in the model function, not in the ability of that model to account for all the variation in the data.

Here, the model is a plain Gaussian function that will always go basically to zero at (hey, what a coincidence!) 3 sigma.   So, the model is never going to encompass even half of the data below x=3 or above x=8 (which is half the data here).

That's not to say that I am certain that the uncertainties calculated by `Model.eval_uncertainty()` is definitely scaled correctly.  Tests or suggestions welcome!

**Comment by jsalsman** [comment]
@newville Matt, that makes perfect sense. I am closing this but please have a look at my work at https://repl.it/@jsalsman/COVID19USgrowthExtrapolation which I'm discussing at https://www.reddit.com/r/CoronavirusUS/comments/fqx8fn/ive_been_working_on_this_extrapolation_for_the/ and https://repl.it/@jsalsman/COVID19USlognormals which I am working on and will be unstable while I try to fix the unstable deaths extrapolation with the Nelder-Mead method. Thank you for your kind help above. Best regards, -Jim

**Comment by newville** [comment]
@jsalsman Ok, thanks -- To be clear, I'd be very grateful to a real statistician checking these confidence bands. 

And thanks for doing and posting the work on COVID-19.   Very nice work and the extrapolations are both enlightening and terrifying -- I'll go wash my hands.

The correlations between your parameters for the log-normal distribution are very high (like > 0.98).  The uncertainties in the fitted parameters - and so the confidence bands in the extrapolation - should reflect that, but they assume that the distribution of parameter values around their best values are "normal", and not highly skewed.  So, it might be interesting to 
  a)  try those fits with a wider range of starting values just 
  b)  run `conf_interval` or use `emcee` to better explore the reasonable values of the log-normal parameters.

I sort of doubt any of this would have a large impact on your results.  If anything, the current trends still look exponential and the log-normal-ness is expected but not yet obvious in the data.   So, yes, 10e6 infected and 0.1e6 deaths both look very believable.  And the uncertainty on your 90-day extrapolation is only 50% ;).

**Comment by jsalsman** [comment]
@newville Matt, I just had an aha/duh moment. Please have a look at https://www.graphpad.com/guides/prism/7/statistics/stat_confidence_interval_of_a_stand.htm in particular:
```Lower limit: =SD*SQRT((n-1)/CHIINV((alpha/2), n-1))
Upper limit: =SD*SQRT((n-1)/CHIINV(1-(alpha/2), n-1))```

and https://support.microsoft.com/en-gb/office/description-of-the-confidence-statistical-functions-in-excel-97f5bf0e-5d56-4f8e-8345-2ec1dada8cd5 
```NORMSINV(1 – alpha/2) * sigma / SQRT(n)```

and let me know what you think. Best regards, -Jim
