### ISSUE TITLE
version 1.0.1

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#632]
We should consider releasing a version 1.0.1 .   We're more than 4 months and a few dozen commits past 1.0.0.   I don't think we have any firm milestones or timelines in mind.  We could just tag current master as 1.0.1 and release it.

I think we could drop support and testing of Py3.5.  I don't think that would mean we *have* to convert to f-strings or drop OrderedDict for dict, but it does mean that we could start using those.

I think we should make a decision on #610 or figure out what is needed for it.  If we don't merge this or something like it for 1.0.1, we should close it and #332.

Any other thoughts or suggestions?

**Comment by reneeotten** [comment]
> We should consider releasing a version 1.0.1 . We're more than 4 months and a few dozen commits past 1.0.0. I don't think we have any firm milestones or timelines in mind. We could just tag current master as 1.0.1 and release it.

@newville yes, we can definitely do a minor release (I'll open a PR in a minute with some additional clean-ups, but don't think that will be controversial).

> I think we could drop support and testing of Py3.5. I don't think that would mean we _have_ to convert to f-strings or drop OrderedDict for dict, but it does mean that we could start using those.

Let's state in the (to-be-written) "what's new" notes that this will be the last release compatible with PY3.5 and then we can indeed stop testing for it afterwards, and start using some 3.6+ features. Related to that, when moving towards `f-strings`, what is the preference here: `'single'` quoted or `"double"` quoted strings (currently we use both). I personally don't have a strong preference, but would like to be consistent and just pick one now and stick to it.

> I think we should make a decision on #610 or figure out what is needed for it. If we don't merge this or something like it for 1.0.1, we should close it and #332.

I don't think we should close the issue/PR without merging something. My main point was (and is),  that we should come up with a solution that will eventually work in the same way for all (local/global) minimizers. So if you think that the current PR can either now, or in the future, be extended to global solvers without changing the API, then it's fine with me. As I said earlier, I would prefer a "final" solution to be merged, but understand your point-of-view as well. 

> Any other thoughts or suggestions?

My intention is to continue extending the test-coverage of Model, Models, and Minimizer classes, but there is no need to wait for that and I cannot promise a timeframe either.

**Comment by newville** [comment]
>> We should consider releasing a version 1.0.1 . We're more than 4 months and a few dozen commits past 1.0.0. I don't think we have any firm milestones or timelines in mind. We could just tag current master as 1.0.1 and release it.

> @newville yes, we can definitely do a minor release (I'll open a PR in a minute with some additional clean-ups, but don't think that will be controversial).

OK.

>> I think we could drop support and testing of Py3.5. I don't think that would mean we have to convert to f-strings or drop OrderedDict for dict, but it does mean that we could start using those.

> Let's state in the (to-be-written) "what's new" notes that this will be the last release compatible with PY3.5 and then we can indeed stop testing for it afterwards, and start using some 3.6+ features.

OK.

>  Related to that, when moving towards f-strings, what is the preference here: 'single' quoted or "double" quoted strings (currently we use both). I personally don't have a strong preference, but would like to be consistent and just pick one now and stick to it.

No preference.  I don't find inconsistent quote styles to be a problem.  Both single and double quotes are valid Python for a reason.  If I had to choose one, I would probably choose single quotes for no other reason than to be invalid to Black.

>> I think we should make a decision on #610 or figure out what is needed for it. If we don't merge this or something like it for 1.0.1, we should close it and #332.  

> I don't think we should close the issue/PR without merging something. My main point was (and is), that we should come up with a solution that will eventually work in the same way for all (local/global) minimizers. So if you think that the current PR can either now, or in the future, be extended to global solvers without changing the API, then it's fine with me. As I said earlier, I would prefer a "final" solution to be merged, but understand your point-of-view as well.

I don't understand.   #610 does work the same for all solvers.  `Minimize._residual()` will raise `AbortFitException` when the number of function evaluations exceeds the user-supplied `max_nfev`.  Solvers that use multiprocessing might make that counting ambiguous (is that total or per process?). I don't know what would fix that ambiguity.   I also don't know how it is worse than the present situation where one must change the "max number of calls" or "max number of iterations" (no definition given) for every solver.  

I don't know what a "final" solution would look like. 


>> Any other thoughts or suggestions?

> My intention is to continue extending the test-coverage of Model, Models, and Minimizer classes, but there is no need to wait for that and I cannot promise a timeframe either.

OK.

**Comment by reneeotten** [comment]
> I don't understand. #610 does work the same for all solvers. `Minimize._residual()` will raise `AbortFitException` when the number of function evaluations exceeds the user-supplied `max_nfev`. Solvers that use multiprocessing might make that counting ambiguous (is that total or per process?). I don't know what would fix that ambiguity. I also don't know how it is worse than the present situation where one must change the "max number of calls" or "max number of iterations" (no definition given) for every solver.
> 
> I don't know what a "final" solution would look like.

Let me take a look at that PR again then, perhaps I am not remembering correctly. I *think* that last time I checked, it didn't work for several methods (e.g., `brute`, `basinhopping`, ...) and there was something different when using the `Model` interface compared to a direct `Minimizer`. But sure, if that has all been resolved I'd be happy to get that merged.

I'll go through the code again in the coming week and follow-up in that PR and we can continue the discussion there.

**Comment by newville** [comment]
@reneeotten Nothing has changed with #610 in 4 months.

**Comment by newville** [comment]
@reneeotten hope you're doing well.  Have you had a chance to look at this yet?   

My inclination is to merge #610, #633, and #635 and call this 1.0.1, and I'd like to get some of these fixes released.   Any objections to that?

**Comment by reneeotten** [comment]
> @reneeotten hope you're doing well. Have you had a chance to look at this yet?

hi @newville, yeah everyone healthy here and we can work from home - so cannot complain. I hope you're also doing well - I guess the beamlines are still operational and require people to be present?

> My inclination is to merge #610, #633, and #635 and call this 1.0.1, and I'd like to get some of these fixes released. Any objections to that?

Still busy though, so haven't had too much time to look at it, but I did browse through the code and discussion in the PR again last week. I am still of the opinion that this feature is not worth breaking backwards-compatibility for. As an end-user or software developer using `lmfit`, I would certainly expect that, for example, specifying `maxfev` as an argument to `leastsq` as documented in `SciPy` in my scripts/program will continue to work as-is. With PR #610 it will just ignore the argument, print a warning to use `max_nfev` instead (which a user might or might not see), and continue the fit... 

Having said that, I also realize that I said ~6 months ago that I would work on it, which hasn't happened either... I don't specify the number of iterations that often, am happy to read over the `SciPy` documentation to find out which variable to change, and would personally prefer the  status quo. But it's your call; it's very well possible that I'm in the minority here and people actually prefer one variable and are happy update their scripts to accommodate this change. If you want to merge it, I do have some corrections to docstrings and a few other details, and a few more tests that I could push to the PR (I've also squashed the commits a bit to get a slightly more readable history). 

I am fine with merging the other PRs.

**Comment by newville** [comment]
@reneeotten Oh, the machines are running but the labs are only letting people working on COVID-19 onto the site or with special permission.  We're all working from home and no outside users are coming in.  No clear idea when that will be back to normal.

Yes, #610 is not backward compatible.  But the current process of getting to the optional arguments of the `scipy.optimize` solvers are pretty arcane -- you have to know what `lmfit` is going to call and hijack the call to that function.   And, for the case  `max number of function evaluations` the `scipy.optimize` solvers do not even try to be consistent.  We try to make it easy to switch solvers.  Having inconsistent ways of spelling (essentially, if not precisely) the same concept makes that harder.  That is the issue of #332.   Like, I'd be in favor of adding a "tolerance" option (and maybe others: 'derivative'?), but I'd like to get this one in first.

So my intention is now to merge all of these.  I'll wait for #636 to be resolved for 1.0.1, but aim for "before May 1".

**Comment by newville** [comment]
merged code.  yep, it was kind of mess.

**Comment by reneeotten** [comment]
version 1.0.1 was [tagged and released ](https://github.com/lmfit/lmfit-py/releases/tag/1.0.1), closing this issue.
