### ISSUE TITLE
Spelling of Doniach lineshape and model

### ISSUE THREAD

**Issue by rayosborn** [lmfit/lmfit-py#634]
#### Description
In `lineshapes.py` and `models.py`, the names defining the Doniach Sunjic asymmetric lineshape are misspelled as `donaich` and `DonaichModel`, respectively. I would suggest that the function and class be renamed with the correct spelling, with the old names being equated to them for backward compatibility. I am happy to submit a PR doing this, but I wanted to check first that there wasn't a valid reason for this mistake.

###### Version information
This is true of v1.0.0 and the latest development version on Github.

**Comment by newville** [comment]
@rayosborn Thanks, that's sort of embarrassing. I saw him give a talk at an SSRL workshop many years ago.

**Comment by rayosborn** [comment]
He was good friends with my supervisor, so I met him a couple of times, which is probably why I noticed. I'll submit a PR shortly.

**Comment by rayosborn** [comment]
I see you've already made the changes. Thanks for saving me the effort.

**Comment by reneeotten** [comment]
fixed in commit f3af0d4c052ca8ae4a4927581ba485c659f18d3c
