### ISSUE TITLE
parameter.set doesn't set value as expected

### ISSUE THREAD

**Issue by arunpersaud** [lmfit/lmfit-py#636]
#### Description
Changing/updating the value for a fit parameter at the same time as min and max values, seems to enforce the old min/max values instead of the new ones for the value. The example hopefully makes this clearer ;)

###### A Minimal, Complete, and Verifiable example
import lmfit

p = lmfit.Parameters()
p.add('test', value=5, min=4, max=10)
print(p)
p['test'].set(value=22, min=20, max=30)
print(p)

results in

Parameters([('test', <Parameter 'test', value=5, bounds=[4:10]>)])
Parameters([('test', <Parameter 'test', value=10, bounds=[20:30]>)])

Whereas I would have expected a value of 22 in the second print statement.
A workaround seems to be to set min and max first to -inf/inf, but I was wondering, if this is intended behavior or a bug.

###### Version information

Python: 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

lmfit: 1.0.0, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.0.3

Thanks for providing lmfit! Very useful and very nice user interface for fitting.

**Comment by newville** [comment]
@arunpersaud yes, that should be fixed.   Are you up for making a Pull Request?

**Comment by arunpersaud** [comment]
I'll give it a try, but I'm not sure if I understand lmfit internals enough at the moment... guess this might be a good opportunity to look into it a bit more. I'll let you know here in case I'm not able to fix it (will know in 1-2 days).

**Comment by arunpersaud** [comment]
hope this works... seem to work locally over here, but I'm not sure if this is the way you want this fixed ;)
