### ISSUE TITLE
No way to add title to model.plot()

### ISSUE THREAD

**Issue by WernerFS** [lmfit/lmfit-py#641]
#### Description

The .plot() will automatically generate a figure on its own if none is provided. I am aware that I could create my figure, set the title and then pass it as an argument, but does not looks as clean as having the option to send the title directly to the set_title you left empty at the end of the definition.

**Comment by newville** [comment]
@WernerFS   

When raising an issue, one must be clear about what is not working as you expect.   You were not. 
When raising an issue, one must provide a complete, and verifiable example that shows the problem.
You provided no code at all.

`model.plot`.  It is good for quick views of a fit.  It will not ever do everything that one could do to graphically represent a model or its fit.  

So, you pretty much ignored every instruction about how to ask for help or raise an issue, including those that clearly say DO NOT IGNORE.   At this point, I do not care about what you think the problem with `mode.plot` might be.   Start over, following the instructions.
