### ISSUE TITLE
Erroneous factor of 2 in covariance calculation from numdifftools?

### ISSUE THREAD

**Issue by cosama** [lmfit/lmfit-py#648]
#### Description
I was looking into the the theory behind calculating covariance through the Fisher information (Hessian of a log-likelihood function evaluated at the minimum) and stumbled over the following line: https://github.com/lmfit/lmfit-py/blob/master/lmfit/minimizer.py#L772

It is not apparent to me why there would be a factor of 2 there. Furthermore, it might be good to mention that this solution is limited to the case where the function to be minimized is a log-likelihood of some sort and that this in general is only a lower limit through the Cramer-Rao bound, where the equality only is true in certain cases: https://en.wikipedia.org/wiki/Cram%C3%A9r%E2%80%93Rao_bound.

**Comment by newville** [comment]
@cosama Hm, it's clear that you know something about data analysis and the mathematical theory of data modeling, and we would normally be happy to discuss this sort of topic.  Though clearly literate, you blew right through the instructions on how to create an issue.  You didn't post any code that might demonstrate that the factor of 2 is erroneous.  Can you give an example that demonstrates a problem with the current calculation?   That would be helpful.  

I don't think we ever go deep into the theoretical underpinnings of data analysis in any of the docs.  If you would like to add that to the documentation and help support that, please consider doing so.

But most importantly, please read and follow the instructions.
