### ISSUE TITLE
implementation of leastsq method for cost function 

### ISSUE THREAD

**Issue by pinkfloydisch** [lmfit/lmfit-py#652]
Hi,

Recently I am using lmfit, and it is very useful and I am very satisfied with it. I have a problem to implement 'leastsq' method to minimize my cost function. I read a lot in the documentation, here and StackOverflow about it but I couldn't find a solution. my cost function hast two parts, one is the main cost function part an another is a regularization part(constant):
ret[3], ret[4], ret[5] are the results of my ODE,
First part is in integrate form:
my data set has 2 columns and each one 64 points:

part_1 = integrate.trapz((delta*(ret[3] + ret[4]) + ret[5] - data[:, 0])**2, t)
part_2 = integrate.trapz((ret[5] - data[:, 2])**2, t)
norm_1 = integrate.trapz(data[:,0]**2, t)
norm_2 = integrate.trapz(data[:,2]**2, t)

then I will add regularization part, 'u' is array of my parameters which I am doing estimation:
u = np.array([u1,u2,u3,u4,u5,u6,u7,u8,u9]) 

weights = 0 , 1e-9 , 1e-8, 1e-7
part_3 = weight * np.linalg.norm(u**2, ord=2)

model2=part_1/norm_1+ part_2/norm_2+ part_3

and I want to minimize it. but since in 'leastsq' I have to give an array, I don't know what should I do, because part_3 is just a regularization part, and acting like a constant. during the minimization, I will add it to the main part. and part_3 itself it is produced by parameter estimation. 
I used the concatenate in several forms: 

np.concatenate(part_1/norm_1, part2/norm_2, part_3)

but it produces an array of (64,64,9) which means lmfit considers the part_3 as a function.

with other methods, which don't need to give them an array, it is working, like least_squares or nelder ... I have results. but I have to work with Levenberg method (least).

I hope that you can help me.

Best regards,
Nik

**Comment by reneeotten** [comment]
we do not use GitHub Issues as a user-support platform, that's what the mailing-list is for (as clearly stated when you opened this issue). It's not at all clear what you think the problem is with lmfit and you do not supply any actual code, requested version information, etcetera. So please do that when you direct your question the mailinglist instead.
