### ISSUE TITLE
source-contains-prebuilt-python-object

### ISSUE THREAD

**Issue by picca** [lmfit/lmfit-py#661]
Hello

the sources available from pypi containes a pre-build file

P: lmfit-py source: source-contains-prebuilt-python-object doc/__pycache__/extensions.cpython-37.pyc

It seems to me that this file should be removed from the source.

thanks for considering

Frederic

**Comment by newville** [comment]
@picca Yep, random `__pycache__` folders happen with Python3.   PR welcome.
