### ISSUE TITLE
leastsq is not working with low max_nfev 

### ISSUE THREAD

**Issue by odstrcilt** [lmfit/lmfit-py#665]
I'm using the latest version of lmfit 1.0.1

When is _leastsq_ method interrupted due to exceeding _max_nfev_, and boundaries are used, the results are completely wrong.

 Problem is in the function _leastsq_ in minimizer.py script

```
        _best = np.array([self.result.params[p].value
                              for p in self.result.var_names])

```
needs to be replaced by 
```
        _best = np.array([self.result.params[p].setup_bounds()
                              for p in self.result.var_names]) 

```
because _best needs to be parameters **before** the transformation. 
The same issue have also    _scalar_minimize_ methods and maybe the others as well.

**Comment by newville** [comment]
@odstrcilt I believe this is now fixed and will close
