### ISSUE TITLE
using my own pool in emcee method

### ISSUE THREAD

**Issue by odstrcilt** [lmfit/lmfit-py#666]
I'm using lmfit 1.0.1.

When emcee method is called with _workers_ argument other than a number, and  with _reuse_sampler=False_,   it will be always overwritten by _auto_pool_

this part of code
```
            p0 = 1 + rng.randn(nwalkers, self.nvarys) * 1.e-4
            p0 *= var_arr
            sampler_kwargs['pool'] = auto_pool
            self.sampler = emcee.EnsembleSampler(nwalkers, self.nvarys,
                                                 self._lnprob, **sampler_kwargs)
```
needs to be replaced by 

```
            p0 = 1 + rng.randn(nwalkers, self.nvarys) * 1.e-4
            p0 *= var_arr
            sampler_kwargs.setdefault('pool',auto_pool)
            self.sampler = emcee.EnsembleSampler(nwalkers, self.nvarys,
                                                 self._lnprob, **sampler_kwargs)

```

The second issue is that emcee is not working with multiprocessing from lmfit. This is probably an issue on the EMCEE side and I was able to repair it. But when I run a standalone version of EMCEE, multiprocessing works.

**Comment by newville** [comment]
@odstrcilt fixed with #667, so closing
