### ISSUE TITLE
Minimize function error rising using initial parameters defined in an other python script

### ISSUE THREAD

**Issue by jdrevon** [lmfit/lmfit-py#671]
#### Description

I work with the minimize function with the COBYLA method and I use a list of initial parameters located in another python script than the one where I use the minimize function and which regroup all the constant parameters. The simple waiy of using a list which is not directly in the python script rise an error which does not appear when I write explictly in the python script the initial parameters : 

```
capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed. 
```

Example (not directly reproducable) : 

This works ==>

```
    x0 = [3.4, 0.08,4.97E-11,1.11]
    resultat_G1 = []
    params = Parameters()
    params.add('central_value', value=x0[0],min=2.9, max=3.5, vary=True)
    params.add('sigma', value=x0[1],min=0.005, max=1, vary=True)
    params.add('A', value=x0[2],min=0, max=1E-8, vary=True)
    params.add('alpha', value=x0[3],min=0.75, max=1.25, vary=True)
    res1 = minim(gaussian_chi2, params, args=(comarcs_x_F,comarcs_y_F,ISO_y),method='cobyla')
    resultat_G1=np.append(resultat_G1,res1)

```
This doesn't ==>

```
    from file1 import x0
    resultat_G1 = []
    params = Parameters()
    params.add('central_value', value=x0[0],min=2.9, max=3.5, vary=True)
    params.add('sigma', value=x0[1],min=0.005, max=1, vary=True)
    params.add('A', value=x0[2],min=0, max=1E-8, vary=True)
    params.add('alpha', value=x0[3],min=0.75, max=1.25, vary=True)
    res1 = minim(gaussian_chi2, params, args=(comarcs_x_F,comarcs_y_F,ISO_y),method='cobyla')
    resultat_G1=np.append(resultat_G1,res1)

```
The x0 is the same than the one in the python script file1 and is simply a copy and paste.

###### Version information
Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]

lmfit: 1.0.1, scipy: 1.5.0, numpy: 1.18.5, asteval: 0.9.18, uncertainties: 3.1.4

**Comment by newville** [comment]
@jdrevon That is not enough to go on.  Go back and read the instructions: start by asking how to do something.  Include a complete,minimal example and full output and traceback.  Do not ignore clear instructions.

**Comment by jdrevon** [comment]
@newville The problem and there is no traceback available here I don't know why.

I've edit the post with an example to reproduce the error

**Comment by jdrevon** [comment]
@newville Should I repost a new thread or when the topic is checked it will be reopen?

**Comment by newville** [comment]
@jdrevon you should read the very clear instructions on how to get help for lmfit, including the instructions for how and when to raise an issue here on github.  You should not ignore these instructions again. This issue will remain closed because it does not actually raise an issue about the code, it asks a question about how to use it.

**Comment by jdrevon** [comment]
@newville Ok sorry, I didn't want to waste your time on github. I've rode the instructions but was persuaded that it was an issue with the code. I will ask then, the question, to the mailing list. Thank you.
