### ISSUE TITLE
During Triple Gaussian fitting, huge devise from initial guess value and high chi-square value

### ISSUE THREAD

**Issue by sundar3492** [lmfit/lmfit-py#683]
I am tried Triple Gaussian fitting, there huge diverse from initial guess value and high chi-square value

How to resolve this problem.   

**##  Warning: uncertainties could not be estimated:**

and it has huge diverse from initial guess values and also very high chis-square value. I attached the output value below.

`[[Model]]
        ((Model(gaussian1) + Model(gaussian2)) + Model(gaussian3))
    [[Fit Statistics]]
        # fitting method   = leastsq
        # function evals   = 751
        # data points      = 89
        # variables        = 9
        chi-square         = 3715.94994
        reduced chi-square = 46.4493743
        Akaike info crit   = 350.126040
        Bayesian info crit = 372.523767
    ##  Warning: uncertainties could not be estimated:
    [[Variables]]
        amp1: -7174.13129 (init = 23)
        cen1: -853.048883 (init = -1.5)
        wid1: -84.6651961 (init = 3.5)
        amp2: -189.857626 (init = 17)
        cen2:  3.47343596 (init = 1)
        wid2: -1.02072899 (init = 1.5)
        amp3:  111.911023 (init = 80)
        cen3: -0.65585443 (init = 3.5)
        wid3:  2.37279022 (init = 3)
`

**Comment by newville** [comment]
@sundar3492  have a hard time understanding how you could raise this issue and not only completely ignore but also erase the instructions for how to ask for help.  At this point, I think your only hope is thoroughly reading all of the guides and documentation about asking for help and as a complete, well-formed question on the lmfit mailing list or sme other forum and hope that someone will be kind enough to help you.
