### ISSUE TITLE
migrate CI to Azure or Github Actions

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#698]
#### Description

(conversation started in #696)  With Travis-CI changing terms of service, we should test moving the CI system to Azure Pipelines or Github Actions..  I've played with Azure a little bit and am still sort of trying to figure it out.  I have not tried Actions - my initial reading of it was that it wasn't designed for CI, but I could certainly be wrong about that! 

I think we do want these features (please add more if any are missing):
   a) using pre-commit.  I think that is not Travis-specific (please correct if wrong!)
   b) be able to test building of the docs and gallery, though maybe not on all versions and library combinations.
   c) build/test with multiple python versions and some selection of numpy/scipy/numdifftools versions.
   d) run some variation of "coverage", though really I would prefer that as part of the report but not triggering failures.

**Comment by reneeotten** [comment]
I agree that we want to do the same things as we run now with Travis, so that list looks good. I am not sure which service would work better, but GitHub Actions appears to be able to do what we want from my reading [here](https://docs.github.com/en/actions/guides/building-and-testing-python).

**Comment by reneeotten** [comment]
for now we'll go with Azure Pipelines (haven't checked GitHub Actions). Closed with 5c4e7ba90efb43d92db59ff66127a7c157800b2f.
