### ISSUE TITLE
Significantly different results of fitting of LognormalModel on different machines

### ISSUE THREAD

**Issue by minaeann** [lmfit/lmfit-py#715]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
While fitting LognormalModel, the resulting parameters (amplitude, center, sigma, chisqr, redchi, aic, bic) are different (up to 27%) with different versions of systems.

###### A Minimal, Complete, and Verifiable example
To shorten the example, only the input with the largest difference is shown here. The files with more inputs are attached:

[lmfit_fitting_results.txt](https://github.com/lmfit/lmfit-py/files/6062161/lmfit_fitting_results.txt)
[out-machine#1.txt](https://github.com/lmfit/lmfit-py/files/6062154/out-machine.1.txt)
[out-machine#2.txt](https://github.com/lmfit/lmfit-py/files/6062153/out-machine.2.txt)
[out-machine#3.txt](https://github.com/lmfit/lmfit-py/files/6062149/out-machine.3.txt)
[out-machine#4.txt](https://github.com/lmfit/lmfit-py/files/6062151/out-machine.4.txt)
[out-machine#5.txt](https://github.com/lmfit/lmfit-py/files/6062152/out-machine.5.txt)

```import json
import sys

import numpy as np
from lmfit.models import LognormalModel


def lmfit_fit(speeds, ts):
    # https://lmfit.github.io/lmfit-py/builtin_models.html#lognormalmodel
    model = LognormalModel(prefix=f'lg_')
    pars = model.make_params()
    pars['lg_center'].set(np.log(ts.mean()), min=np.log(ts.min()), max=np.log(ts.max()))
    pars['lg_amplitude'].set(speeds.mean() * 100, min=1)

    # init = model.eval(pars, x=ts)
    out = model.fit(speeds, pars, x=ts)

    # Get estimated parameters
    amplitude = out.params[f'lg_amplitude'].value
    center = out.params[f'lg_center'].value
    sigma = out.params[f'lg_sigma'].value

    return {
        'amplitude': amplitude,
        'center': center,
        'sigma': sigma,
        'chi_sqr': out.chisqr,
        'red_chi_sqr': out.redchi,
        'aic': out.aic,
        'bic': out.bic
    }


INPUTS = [
    (
        '2_3',
        np.array([0.0, 0.0, 0.0, 32249.030993194196, 0.0, 454.21897680825, 686.1495955998765, 488.6216817150636, 475.5259038325823, 453.78229069338823, 640.5042786316415, 488.6216817150636, 474.2504557822676, 447.6360930863913, 503.8911092686593, 0.0]),
        np.array([1, 2, 609, 610, 865, 933, 980, 1046, 1112, 1182, 1231, 1297, 1365, 1434, 1498, 1600])
    )
]

result = []
for i, inp in enumerate(INPUTS):
    res_lmfit = lmfit_fit(inp[1], inp[2])
    result.append({
        'key': inp[0],
        'i': i,
        'speed_len': len(inp[1]),
        'speed_min': float(inp[1].min()),
        'speed_mean': float(inp[1].mean()),
        'speed_max': float(inp[1].max()),
        'ts_len': len(inp[2]),
        'ts_min': float(inp[2].min()),
        'ts_mean': float(inp[2].mean()),
        'ts_max': float(inp[2].max()),
        'lmfit': res_lmfit,
    })

print(json.dumps(result, indent=4))
```

###### Error message:
We run this program on five different machines and here are the results (`amplitude` is the differing one):

Machine#1:
```
    {
        "key": "2_3",
        "i": 8,
        "speed_len": 16,
        "speed_min": 0.0,
        "speed_mean": 2335.1395662704613,
        "speed_max": 32249.030993194196,
        "ts_len": 16,
        "ts_min": 1.0,
        "ts_mean": 985.3125,
        "ts_max": 1600.0,
        "lmfit": {
            "amplitude": 18624447.002578545,
            "center": 6.416209041958359,
            "sigma": 0.0007822552577236852,
            "chi_sqr": 2676110.326917056,
            "red_chi_sqr": 205854.64053208122,
            "aic": 198.43657928696763,
            "bic": 200.75434545368697
        }
    },
```
Machine#2:
```
    {
        "key": "2_3",
        "i": 8,
        "speed_len": 16,
        "speed_min": 0.0,
        "speed_mean": 2335.1395662704613,
        "speed_max": 32249.030993194196,
        "ts_len": 16,
        "ts_min": 1.0,
        "ts_mean": 985.3125,
        "ts_max": 1600.0,
        "lmfit": {
            "amplitude": 18624447.002578545,
            "center": 6.416209041958359,
            "sigma": 0.0007822552577236852,
            "chi_sqr": 2676110.326917056,
            "red_chi_sqr": 205854.64053208122,
            "aic": 198.43657928696763,
            "bic": 200.75434545368697
        }
    },
```
Machine#3:
```
	{
        "key": "2_3",
        "i": 8,
        "speed_len": 16,
        "speed_min": 0.0,
        "speed_mean": 2335.1395662704613,
        "speed_max": 32249.030993194196,
        "ts_len": 16,
        "ts_min": 1.0,
        "ts_mean": 985.3125,
        "ts_max": 1600.0,
        "lmfit": {
            "amplitude": 14606874.801522193,
            "center": 6.41604807591262,
            "sigma": 0.0007486234727507313,
            "chi_sqr": 2676107.498453425,
            "red_chi_sqr": 205854.42295795574,
            "aic": 198.43656237606467,
            "bic": 200.754328542784
        }
    },
```
Machine#4:
```
    {
        "key": "2_3",
        "i": 8,
        "speed_len": 16,
        "speed_min": 0.0,
        "speed_mean": 2335.1395662704613,
        "speed_max": 32249.030993194196,
        "ts_len": 16,
        "ts_min": 1.0,
        "ts_mean": 985.3125,
        "ts_max": 1600.0,
        "lmfit": {
            "amplitude": 14606874.801522193,
            "center": 6.41604807591262,
            "sigma": 0.0007486234727507313,
            "chi_sqr": 2676107.498453425,
            "red_chi_sqr": 205854.42295795574,
            "aic": 198.43656237606467,
            "bic": 200.754328542784
        }
    },
```
Machine#5:
```
    {
        "key": "2_3",
        "i": 8,
        "speed_len": 16,
        "speed_min": 0.0,
        "speed_mean": 2335.1395662704613,
        "speed_max": 32249.030993194196,
        "ts_len": 16,
        "ts_min": 1.0,
        "ts_mean": 985.3125,
        "ts_max": 1600.0,
        "lmfit": {
            "amplitude": 14606874.801522193,
            "center": 6.41604807591262,
            "sigma": 0.0007486234727507313,
            "chi_sqr": 2676107.498453425,
            "red_chi_sqr": 205854.42295795574,
            "aic": 198.43656237606467,
            "bic": 200.754328542784
        }
    },
```
Generally, on the two MacOS machines the results are identical, while for other machines they differ.

###### Version information
 
Machine#1 (MacOS):
```
Python: 3.8.6 (default, Nov 20 2020, 18:29:40)
[Clang 12.0.0 (clang-1200.0.32.27)]
```

Machine#2 (MacOS):
```
Python: 3.9.1 
[Clang 12.0.0 (clang-1200.0.32.29)]
```

Machine#3 (WLS (Xenie)):
```
Python: 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 18:01:20)
[GCC 7.5.0]
```

Machine#4 (Debian):
```
Python: 3.8.6 (default, Dec 18 2020, 05:24:40) 
[GCC 8.3.0]
```

Machine#5 (Ubuntu):
```
Python: 3.8.6 (default, Oct 15 2020, 16:28:12) 
[GCC 9.3.0]
```

For all machines, `lmfit: 1.0.1, scipy: 1.6.1, numpy: 1.19.4, asteval: 0.9.22, uncertainties: 3.1.5`,

###### Link(s)
 No discussion started

**Comment by reneeotten** [comment]
@minaeann I tried out the example you posted here and do get the same results as on your macOS machines. However, the fit is certainly not perfect I would say. The final values for the fitted parameters on the different computers are are all a bit different (it's not only `amplitude` as you said) - what do you consider the "correct" fit (i.e., on which machine do you think it's correct)?

The fitting statistics appear to be (almost) identical for the different runs, so that likely means that the fits converge to a "similarly" correct result. I can certainly imagine that machine precision and such is different depending on OS and computer.

I am not convinced yet that there is an issue here with `lmfit` and not just that there are similar solutions that give pretty much the same fitting statistics, and it could depend on the OS and/or computer where it ends up. Are you really convinced that this is a bug?

**Comment by reneeotten** [comment]
please take a look at the `fit_report` as well, in my case it shows this:
```
[[Model]]
    Model(lognormal, prefix='lg_')
[[Fit Statistics]]
    # fitting method   = leastsq
    # function evals   = 345
    # data points      = 16
    # variables        = 3
    chi-square         = 2676110.33
    reduced chi-square = 205854.641
    Akaike info crit   = 198.436579
    Bayesian info crit = 200.754345
[[Variables]]
    lg_amplitude:  18624447.0 +/- 1.9167e+13 (102912674.83%) (init = 233514)
    lg_center:     6.41620904 +/- 355.278619 (5537.20%) (init = 6.892959)
    lg_sigma:      7.8226e-04 +/- 38.9010728 (4972938.49%) (init = 1)
    lg_height:     15528192.7 +/- 1.5203e+13 (97904212.01%) == 'lg_amplitude/max(1e-15, (lg_sigma*sqrt(2*pi)))*exp(lg_sigma**2/2-lg_center)'
    lg_fwhm:       1.12675681 +/- 56433.7029 (5008507.81%) == 'exp(lg_center-lg_sigma**2+lg_sigma*sqrt(2*log(2)))-exp(lg_center-lg_sigma**2-lg_sigma*sqrt(2*log(2)))'
[[Correlations]] (unreported correlations are < 0.100)
    C(lg_amplitude, lg_center) =  1.000
    C(lg_center, lg_sigma)     =  1.000
    C(lg_amplitude, lg_sigma)  =  1.000
```

which tells you that the parameters are completely correlated and all have huge uncertainties. I just don't think the fit (or model) is good here and by looking at this I am not surprised that you'll get different results.

@newville what do you think - real issue and something we need to investigate or no?

**Comment by minaeann** [comment]
Thank you very much for the quick answer. We have discovered a bug in our code that has resulted in the model being not good at these data. So we assume it is a closed issue.

**Comment by newville** [comment]
@reneeotten  I continue to be utterly stumped when people use Github Issues for questions about lmfit when we tell them about 20 times exactly to not do that.   No one submitting an issue here is a newbie - they know python, they know about numerical/scientific data processing, and fitting data.  They know enough about github to think to submit an issue.  And yet it is as if they simply cannot read or believe that their poor fit may not be a bug in the underlying library.  

It is completely demoralizing.

**Comment by martin-majlis** [comment]
@reneeotten, @newville : Thanks for you work on this project, sorry for wasting your time on this issue, and let me add more context to the response from @minaeann. 

Thanks for pointing to the documentation that it is worth reading also documentation for [ModelResult](https://lmfit.github.io/lmfit-py/model.html?highlight=fit#lmfit.model.ModelResult).

We have some source of data and based on literature they should have LogNormal distribution, therefore we have decided to use your library. Apparently these data are not always following the literature. This was red herring.

Now we believe that the difference is not caused by your library but by library, that is your library using - https://stackoverflow.com/questions/30065437/floating-point-math-in-python-numpy-not-reproducible-across-machines - there are indeed different `libblas` and `liblapack` on those different machines -  `python3 -c 'import numpy; numpy.show_config();'`

Have a nice weekend. :)

**Comment by newville** [comment]
@martin-majlis  When one completely ignores the really very clear instructions for asking questions, they are being rude. We are under no obligation to pay attention to rude people, and it is unlikely that any attention paid to any technical issues they might be seeing.   For all future communications about lmfit, you will need to use the mailing list.
