### ISSUE TITLE
.make_params() results in different changes to the value of .param_names for Model vs CompositeModel

### ISSUE THREAD

**Issue by stuart-cls** [lmfit/lmfit-py#716]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description

`.make_params()` results in different changes to the value of `.param_names` for `Model` vs `CompositeModel`. 
* For `Model`, the param_hints are added to `._param_names` which is returned by `.param_names`. 
* For `CompositeModel`, the param_hints are added to `._param_names` but `.param_names` returns `self.left.param_names + self.right.param_names` which is unchanged.

My preference is actually for `.param_names`  to remain unchanged after `.make_params()` call as in `CompositeModel`, i.e. to remove https://github.com/lmfit/lmfit-py/blob/ddf7d40e8eae540a0c6ff7387064ac800b94cc2a/lmfit/model.py#L697
so that `.param_names` always returns only the parameters from the function signature (and isn't changed).

###### A Minimal, Complete, and Verifiable example

````
import lmfit

# Model
m = lmfit.models.GaussianModel(prefix="g0_")
pn_before = m.param_names.copy()  # ['g0_amplitude', 'g0_center', 'g0_sigma']
m.make_params()
pn_after = m.param_names.copy()  # ['g0_amplitude', 'g0_center', 'g0_sigma', 'g0_fwhm', 'g0_height']
assert pn_before != pn_after

# CompositeModel
g1 = lmfit.models.GaussianModel(prefix="g1_")
g2 = lmfit.models.GaussianModel(prefix="g2_")
cm = g1 + g2
pn_before = cm.param_names.copy()  # ['g1_amplitude', 'g1_center', 'g1_sigma', 'g2_amplitude', 'g2_center', 'g2_sigma']
cm.make_params()
pn_after = cm.param_names.copy()  # ['g1_amplitude', 'g1_center', 'g1_sigma', 'g2_amplitude', 'g2_center', 'g2_sigma']
assert pn_before == pn_after
````
###### Error message:

None.

###### Version information

Python: 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:30:06) [MSC v.1916 64 bit (AMD64)]
lmfit: 1.0.1, scipy: 1.6.0, numpy: 1.19.5, asteval: 0.9.16, uncertainties: 3.1.5

**Comment by newville** [comment]
@stuart-cls   We really want people to use the mailing list for questions about lmfit.  When you say

```My preference is actually for ...```

that sort of demonstrates that you know that it is open for interpretation and discussion.

I'm not sure I actually understand the complaint.  Perhaps it is that sometimes parameters that are constrained by equations in `param_hints` show up in `param_names` and sometimes don't? 

I think it might be worth asking whether a Model needs a public-facing `param_names`  attribute at all.  

Anyway, I'm going to close this.
