### ISSUE TITLE
Intuitive lmfit.minimize behaviour - minimize function value vs it's square

### ISSUE THREAD

**Issue by oldrichsmejkal** [lmfit/lmfit-py#735]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
lmfit.minimize function by default minimze function in leastsquare manner.
This is really confusing for new users, because you call minimze funcion without additional arguments and you get back unexpected results. 

Then you try to change to other 'method' (which is supposed to be just different optimization procedure, like in scipy, not something which actually changes what is optimization goal..) and get seemingly right answer.

It would be great to have more clear function name, which will state if there is actual function mimimze or of it is doing least squares which are in my opinion different goals..

###### A Minimal, Complete, and Verifiable example

```
# lmfit.minimze without any additional parameters - doing least square.. Seemingly strange result
import numpy as np
import matplotlib.pyplot as plt

def fn(x):
    return x ** 2 - 10

x = np.linspace(-5,5)
y = fn(x)
plt.plot(x, y)
plt.show()

import lmfit
def fn_lmfit(params):
    return fn(params['x'])


params = lmfit.Parameters()
params.add('x', value = 0, min = -5, max = 5, vary = True) 

out = lmfit.minimize(fn_lmfit, params,
               #method = 'nelder'
              )

print(f"Minimal value: {fn_lmfit(out.params.valuesdict())}, for x = {out.params.valuesdict()}")

# Minimal value: 0.05236229210787258, for x = OrderedDict([('x', -3.1705460558250644)])
```

```
# Actual function minimization, most of other 'method' options, e.g.: 'nelder'
params = lmfit.Parameters()
params.add('x', value = 0, min = -5, max = 5, vary = True) 

out = lmfit.minimize(fn_lmfit, params,
               #method = 'nelder'
              )

# Minimal value: -10.0, for x = OrderedDict([('x', 0.0)])

```

###### Version information
Python: 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]

lmfit: 1.0.2, scipy: 1.5.2, numpy: 1.19.1, asteval: 0.9.25, uncertainties: 3.1.6

**Comment by newville** [comment]
> First Time Issue Code
> Yes, I read the instructions and I am sure this is a GitHub Issue.

Nope, it's not. 

`lmfit.Minimize()` requires the user to supply an objective function.  Go read the docs and examples, and use the mailing list if you have any questions.

**Comment by oldrichsmejkal** [comment]
Did you read my code sample?
Do you see completelly different results of same objective function minimization?
Should result pf same objective function minimization be complettely different depending on selected 'method'?

I still don't think so and I find it really strange from package interface user perspective..

**Comment by newville** [comment]
@oldrichsmejkal For sure, different fitting algorithms can give different results.  If you have questions about how lmfit works or why you might not be getting results that you do not understand, please use the mailing list or perhaps StackOverflow.    Don't use Github issues for support questions.
