### ISSUE TITLE
the wrong confidence band

### ISSUE THREAD

**Issue by yangshenbang** [lmfit/lmfit-py#736]
Hi,
I used the function **eval_uncertainty** to calculate the confidence band for the fitting, but I found that the band was much smaller than I thought.
I have checked on the code, and there's kind of a problem here:
https://github.com/lmfit/lmfit-py/blob/21d3e6b008a74a4aaa9e97eae32f76a316f18671/lmfit/model.py#L1536

Is there missing a **reduced chisqr** in the calculation?
The term `np.sqrt(df2)` should be `np.sqrt(self.redchi * df2)` according to [ https://www.astro.rug.nl/software/kapteyn/kmpfittutorial.html#confidence-and-prediction-intervals](url) noted under the function.

**Comment by newville** [comment]
@yangshenbang I'm confused about why you completely ignored and deleted all of the information about how to submit an Issue which is marked as DO NOT IGNORE.    If you cannot respect our process, I don't see why it would do us any good to try to help you better understand this issue.   Can you explain your reasoning?
