### ISSUE TITLE
JSON representations of Parameters from other sources may fail to be loaded

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#739]
#### Description

A JSON representation of `Parameters` that gets modified by Javascript (and maybe other tools) may have Inf and NaN represented differently, for example replacing "Infinity" with "null".  This prevents the JSON from be loaded properly back into a `Parameters` object.

###### A Minimal, Complete, and Verifiable example
```
from lmfit import Parameters

pars = Parameters()
pars.add('a', 3.0, min=0)
pars.add('b', 10.0, max=1000)
pars.add('c', 20.0)
pars.add('d', expr='c - b/a')

# mangle JSON as Javascript or other might:
json_rep = pars.dumps().replace('-Infinity', 'null').replace('Infinity', 'null')

new = Parameters()
new.loads(json_rep)
for vname in ('a', 'b', 'c', 'd'):
    assert new[vname].value == pars[vname].value
    assert new[vname].min == pars[vname].min
    assert new[vname].max == pars[vname].max
```

###### Error message:

```
    new.loads(json_rep)
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 489, in loads
    _par.__setstate__(parstate)
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 727, in __setstate__
    self.value = _value
  File "/Users/Newville/Codes/lmfit-py/lmfit/parameter.py", line 836, in value
    if self._val > self.max:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

###### Version information

Python: 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
[Clang 11.1.0 ]

lmfit: 1.0.2.post78+g15a952b, scipy: 1.7.0, numpy: 1.21.0, asteval: 0.9.25, uncertainties: 3.1.5

###### Link(s)

See  https://groups.google.com/g/lmfit-py/c/_LNLb-fV8Ak

**Comment by reneeotten** [comment]
Fixed in f0707cccec057e0e922b105f6ca809ff7e59b524
