### ISSUE TITLE
Support scipy's new solvers as local solvers in AMPGO

### ISSUE THREAD

**Issue by dschmitz89** [lmfit/lmfit-py#744]
**Description**

Hey lmfit,

the AMPGO code is from 2013, a time when many of the new local solvers (CG, trust-krylov etc.) were not yet available in scipy. 
Currently, AMPGO does not work with them as it checks for
    - `'L-BFGS-B'` (default)
    - `'Nelder-Mead'`
    - `'Powell'`
    - `'TNC'`
    - `'SLSQP'`
   
I think simply adding the new solvers to the list in the AMPGO solver code should make them available. Would you be interested in this?

**Comment by newville** [comment]
@dschmitz89   You ignored all of the text saying DO NOT IGNORE, including special instructions for first-time users.

Those instructions for how to submit an issue are kind of a test of whether someone submitting an issue can read and follow instructions, respect our processes, and be someone whom we might want to work with. The available data suggests that you did not read the instructions.   Not sure if that was your goal, but if you would like us to engage in an actual discussion, you will need to try again.
