### ISSUE TITLE
add optional multiprocessing for leastsq()

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#76]
When using finite-diff Jacobian (ie, most of the time), it would be useful to add an option (normally off)  to use multiprocessing with leastsq().   That is, following the
simple example at
  http://stackoverflow.com/a/19679060

one could use multiple processes for the calls to the objective function in order to calculate the Jacobian -- basically write an internal Dfun that farmed out the work of fdjac2() to a multiprocess Pool.

This could be exposed by adding a
     use_multicores=4

argument to leastsq() to indicate the size of the multiprocessing pool.  
The default value of None would not use multiprocessing at all.

**Comment by yw5aj** [comment]
+1 for this hilarious idea.

**Comment by newville** [comment]
@yw5aj  hilarious?  Work is this area would be interesting and potentially beneficial, but I don't think it would be easy.  iThe main issue is that multiprocessing requires Pickle, which simply cannot handle complex objects such as functions.   Using the dill package is probably necessary. 

Anyway, if you're interested in working on this, please do.

**Comment by yw5aj** [comment]
@newville Thank you for the input - I am relatively new to multiprocessing and did not realize that it requires pickling in the process. And the pointer to dill is very interesting - thanks!

**Comment by andyfaff** [comment]
The emcee method is already working with multiprocessing, and working
well.  There is an overhead to multiprocessing that means you only win if
your objective function is expensive.
The objective function does need to be pickleable. But that's doable, just
can't use lambda functions or bound methods.

**Comment by newville** [comment]
This never really gave consistent improvement.  I think it's really an issue to be solved upstream anyway.
