### ISSUE TITLE
1.0.3 breaks fitting for ndarray subclasses

### ISSUE THREAD

**Issue by bennyrowland** [lmfit/lmfit-py#767]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
I have a data processing library that uses a numpy ndarray subclass to attach various
metadata to the bare ndarray. I use this subclass with lmfit where the metadata is
essential to generating the model (the metadata provides the time axis spacing used to
calculate the decay). This worked correctly up until 1.0.3 where PR #728 now coerces
all data into bare ndarrays with `np.asarray()`/`np.asfarray()`. This means that the
metadata is no longer available for generating the model.

PR #728 is designed to make sure that data that is not in a float64/complex128 ndarray
is coerced into that form. But in my case the data does already match that criteria, but
is being stripped of its extra detail to no advantage.

###### A Minimal, Complete, and Verifiable example
The code below works correctly on 1.0.2 but not on 1.0.3.
<details>

```
import lmfit
import numpy as np


class Example(np.ndarray):
    def __new__(cls, input_array, dt=None):
        # input_array is an already formed ndarray
        # we want to make it our class type
        obj = np.asarray(input_array).view(cls)
        if dt is not None:
            obj.dt = dt
        return obj

    def __array_finalize__(self, obj):
        dt = getattr(obj, 'dt', None)


def linear_growth(in_data, growth_per_second):
    time_axis = np.arange(len(in_data)) * in_data.dt
    return growth_per_second * time_axis


if __name__ == "__main__":
    growth_model = lmfit.model.Model(linear_growth)
    measured_times = np.arange(10)
    synthetic_data = Example(measured_times * 1, dt=1)

    params = lmfit.Parameters()
    params.add("growth_per_second", value=0.5)

    result = (growth_model.fit(synthetic_data, params, in_data=synthetic_data))
    print(result.best_values)

```

</details>

###### Error message:

```
Traceback (most recent call last):
  File "/Users/ben/Library/Application Support/JetBrains/PyCharm2021.2/scratches/scratch.py", line 31, in <module>
    result = (growth_model.fit(synthetic_data, params, in_data=synthetic_data))
  File "/Users/ben/anaconda3/lib/python3.6/site-packages/lmfit/model.py", line 1050, in fit
    output.fit(data=data, weights=weights)
  File "/Users/ben/anaconda3/lib/python3.6/site-packages/lmfit/model.py", line 1404, in fit
    self.init_fit = self.model.eval(params=self.params, **self.userkws)
  File "/Users/ben/anaconda3/lib/python3.6/site-packages/lmfit/model.py", line 868, in eval
    return self.func(**self.make_funcargs(params, kwargs))
  File "/Users/ben/Library/Application Support/JetBrains/PyCharm2021.2/scratches/scratch.py", line 19, in linear_growth
    time_axis = np.arange(len(in_data)) * in_data.dt
AttributeError: 'numpy.ndarray' object has no attribute 'dt'```

###### Version information
Python: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
lmfit: 1.0.3, scipy: 1.4.1, numpy: 1.18.1,asteval: 0.9.25, uncertainties: 3.1.2

**Comment by newville** [comment]
@bennyrowland  Supporting that well could actually be challenging.  It might be reasonable to change line 1027:

https://github.com/lmfit/lmfit-py/blob/1acdeeca2182566aeec7d7a53d660b346f5f5829/lmfit/model.py#L1027

to 
```python
    if np.isrealobj(data) and data.dtype != np.float64: 
        data = np.asfarray(data)
```

The challenge is that if the data is not Float64 (and your subclass does not guarantee this), then the data really does need to be coerced to Float64, and this will lose your added attributes.  So, using subclasses of `ndarray` is going to be somewhat fragile.

**Comment by reneeotten** [comment]
@bennyrowland @newville Yeah, I guess this is an unintended consequence of the coercion, which was added there for a good reason. I don't think we want/should attempt to fix-up every possible use-case someone might have and would prefer to leave it as is. It's also not the one-line fix as Matt suggests above, there are more places where we would need to adjust the code (also for the use-case of complex data). 

@bennyrowland for the code you're showing this can easily be circumvented by supplying the `time_axis` as an argument to the "residual" function instead of adding it as an attribute to a new class that is otherwise identical to a `numpy.ndarray`.

**Comment by newville** [comment]
@bennyrowland @reneeotten Yeah, it may be that the `Example` example here is deliberately simplified, but we never promised that such a derived type was supported.  That it ever accidentally did work is kind of surprising.  Like, any slice or multiplication with an `Example`instance would lose the `dt` attribute.

**Comment by bennyrowland** [comment]
@newville @reneeotten thanks for your quick and sympathetic responses. I think that @reneeotten's approach of supplying the arguments independently to the residual function is probably workable in my case. `Example` is highly simplified to demonstrate the error rather than the actual use case, but the properties are all constant during a fit so can be passed in separately - it was just easier to pass the subclass that had all the properties I needed, rather than splitting them up.

To be honest, I kind of regret going down the subclass route altogether, ndarray subclasses are terribly fragile, mostly because of the plentiful `asarray()` calls sprinkled throughout the code base. It is possible to solve things like slicing and multiplication to preserve the subclass (and keep `dt`) but every new function you use has the potential to break it all again. Next time I will use something like xarray which wraps the ndarray instead of subclassing it - it wouldn't solve this issue, but it would make it more obvious that it wouldn't work ;-).

Closing this issue as there is a reasonable workaround and I agree that a proper fix is an unreasonable amount of work.
