### ISSUE TITLE
No attribute "COMMON_DOC"

### ISSUE THREAD

**Issue by Emily-Linden** [lmfit/lmfit-py#782]
I tried installing lmfit and I keep getting an error saying 'lmfit.models' has no attribute 'COMMON_DOC'. I tried downloading it on two different computers and I keep getting the same thing. Here's the error message:

Input In [9], in <cell line: 1>()
----> 1 import scraps

File ~\Downloads\scraps-master\scraps\__init__.py:1, in <module>
----> 1 from scraps.fitsS21 import (
      2     cmplxIQ_fit,
      3     cmplxIQ_params,
      4     hanger_fit,
      5     hanger_params,
      6     inline_fit,
      7     inline_params,
      8 )
      9 from scraps.fitsSweep import f0_tlsAndMBT, qi_tlsAndMBT
     10 from scraps.plot_tools import (
     11     plotResListData,
     12     plotResSweep3D,
   (...)
     15     plotResSweepParamsVsX,
     16 )

File ~\Downloads\scraps-master\scraps\fitsS21\__init__.py:3, in <module>
      1 from scraps.fitsS21.cmplxIQ import cmplxIQ_fit, cmplxIQ_params
      2 from scraps.fitsS21.hanger_resonator import hanger_fit, hanger_params
----> 3 from scraps.fitsS21.inline_ground_terminated_resonator_s11 import (
      4     inline_ground_terminated_fit,
      5     inline_ground_terminated_params,
      6 )
      7 from scraps.fitsS21.inline_resonator import inline_fit, inline_params

File ~\Downloads\scraps-master\scraps\fitsS21\inline_ground_terminated_resonator_s11.py:11, in <module>
      9 import lmfit
     10 import numpy as np
---> 11 from scraps.fitsS21 import baselines, utils
     14 def cmplx_grounded_inline_s11(freqs, f0, df, qc, q0):
     15     """An asymmetric lineshape vs frequency.
     16
     17     Pass df = 0 to recover the standard complex Lorentzian shape."""

File ~\Downloads\scraps-master\scraps\fitsS21\baselines.py:32, in <module>
     28     phi = p0 + p1 * x + p2 * x ** 2
     29     return np.exp(1j * phi)
---> 32 class ModelMagBaseline(lmfit.Model):
     33     __doc__ = (
     34         "lmfit model that fits a 2nd order polynomial as a function of reduced frequency."
     35                 + lmfit.models.COMMON_DOC
     36     )
     38     def __init__(self, *args, **kwargs):

File ~\Downloads\scraps-master\scraps\fitsS21\baselines.py:35, in ModelMagBaseline()
     32 class ModelMagBaseline(lmfit.Model):
     33     __doc__ = (
     34         "lmfit model that fits a 2nd order polynomial as a function of reduced frequency."
---> 35                 + lmfit.models.COMMON_DOC
     36     )
     38     def __init__(self, *args, **kwargs):
     39         super().__init__(mag, *args, **kwargs)

AttributeError: module 'lmfit.models' has no attribute 'COMMON_DOC'

**Comment by newville** [comment]
@Emily-Linden  `lmfit.models.COMMON_DOC` got changed to `lmfit.models.COMMON_INIT_DOC` sometime around the release of version 0.9.6.  As it happens, that was almost exactly 5 years ago ;).   
That said, I'm all in favor of superconducting resonators, TES,  and any work that UChicago/ANL does on these ;).  Would a PR at scraps help?

**Comment by FaustinCarter** [comment]
@reneeotten Thanks for bringing this to my awareness. I'll push a patch to scraps this weekend.

Although `lmfit.models.COMMON_DOC` was deprecated 5 years ago, it was only recently removed in https://github.com/lmfit/lmfit-py/commit/aa0e22873ab24b6e7085f625d9c7f88c1979b8a8 (i.e. about 5 months ago). In other words, 1.0.3 is the first version of lmfit to not have it. There was also never a deprecation warning, and the release notes for 1.0.3 don't mention it as a breaking change. 

That being said, it's still on me for not carefully reading the `models.py` code before pushing the last scraps update. If I had I'd have noticed that it had been removed in the master branch a month before I released my last update!

**Comment by newville** [comment]
@FaustinCarter Oh, sorry for that, you are correct that though we stopped using it, COMMON_DOC was still in the code until 1.0.3. And, yeah, it is always sort of hard to know what counts as "used API" that should be clearly deprecated.   

FWIW, I often get stung by such changes in "hidden API" myself.  It is somewhat more frustrating when you do it to yourself ;).
Cheers.
