### ISSUE TITLE
Extending the fit statistic by including the R2-Statistic

### ISSUE THREAD

**Issue by Anselmoo** [lmfit/lmfit-py#803]
#### First Time Issue Code

Extending the fit statistic by including the [R2-Statistic](https://en.wikipedia.org/wiki/Coefficient_of_determination)

###### A Minimal, Complete, and Verifiable example

Could be implemented here:

https://github.com/lmfit/lmfit-py/blob/e54a44c68f9cb40836b9aca5398436f4f2b20b15/lmfit/minimizer.py#L358-L380

###### Version information

`lmfit 1.0.3`

###### Link(s)
Discussed in https://github.com/lmfit/lmfit-py/discussions/801

**Comment by newville** [comment]
closing.
