### ISSUE TITLE
version 1.0.4 release

### ISSUE THREAD

**Issue by newville** [lmfit/lmfit-py#809]
Version 1.0.3 is now a year old, and there have been several bug fixes and minor improvements since then.  

I suggest we plan to release 1.0.4 soon (say, within a month or so) and start identifying what existing or unspoken issues should be resolved for that.   Any suggestions for 1.0.4 milestones or improvements?

**Comment by reneeotten** [comment]
Let's wait at least until the official release of Python 3.11 and make sure that everything works as intended. 

There were a few discussion on the mailing list / Discussion page that potentially could be fixed for a new release, I just don't know how much time I will have to do anything about it.... I don't think they were major things and something that I would consider worthwhile delaying a new release for though.

**Comment by newville** [comment]
@reneeotten OK that sounds like a good plan.  I may try to address #761 but am not sure that will get done.

**Comment by newville** [comment]
@reneeotten I would like to release 1.0.4 soon - before mid-December, and ideally next week.  I want downstream packages to be able to rely on new features.  

Is there anything you would like to change for that release?

**Comment by reneeotten** [comment]
@newville are you okay with bumping the minimum requirements for SciPy to 1.6 (released on December 30, 2020) and NumPy 1.19.0 (released on June 20, 2020)? I haven't checked whether that will help us to clean-up some code and/or update defaults for the optimizers, but can do so this weekend.

**Comment by newville** [comment]
Yes to bumping scipy and numpy to about 2-years old. Thanks!

**Comment by newville** [comment]
1.0.4rc1 tagged

**Comment by reneeotten** [comment]
perhaps this should be a 1.1.0 release given the changes amongst dropping PY36 and adding PY311? Then we could do plan on more frequent 1.1.x updates when there are smaller fixes/enhancements? But if you want to call this 1.0.4 that's also fine with me - I think we should just release more often.

**Comment by newville** [comment]
Ah, good point. I'm agree with calling it 1.1.

**Comment by newville** [comment]
@reneeotten @Tillsten OK, I'll release the current version as 1.1!
