### ISSUE TITLE
HTML Static doc missing

### ISSUE THREAD

**Issue by TheSkyentist** [lmfit/lmfit-py#817]
Yes, I read the instructions and I am sure this is a GitHub Issue.

On the documentation site (https://lmfit.github.io/lmfit-py/index.html), the HTML static doc download is missing: https://lmfit.github.io/lmfit-py/lmfit_doc.zip

**Comment by reneeotten** [comment]
@newville there is a shell script "publish_docs.sh" that will take care of all of this and makes all the linked files available on GitHub Pages. Or at least it's supposed to do that - I will check tonight.

**Comment by reneeotten** [comment]
> @reneeotten right -- we could certainly revise a script or workflow to push docs to gh-pages. 

the point is that we do not need to revise anything - it's there already and when used it does take care of it. 

> The first question is: should we provide a zip file of static docs? I am definitely OK with saying yes, but I think we have data showing that it is not used _that_ much ;)

Perhaps it isn't used that much but also there it is (close to) zero work to do it, so why not ;)

**Comment by reneeotten** [comment]
I just ran the script and committed the changes to the `gh-pages` branch (also the other static documentation wasn't up-to-date). This should be fixed for the current release - I would be in favor to just continue to provide the PDF, EPUB file and the ZIPped HTML documentation going forward.

**Comment by newville** [comment]
@reneeotten Thanks!  I agree with "why not" have the docs in any and all formats.  And I am glad the script is still working! I think we can remember to run that script to publish all the forms of the docs.

**Comment by reneeotten** [comment]
fixed in 76d711f949fd0d4c05cf288778eff34b6777bc4a
