### ISSUE TITLE
Issues with build-in DoniachModel documentation

### ISSUE THREAD

**Issue by joeyE99** [lmfit/lmfit-py#819]
The python code for DoniachModel and the online documentation does not match.  The formula for the DoniachModel should be something like

$$
\frac{A}{\sigma^{1-\gamma}} \frac{\cos [\pi \gamma / 2+(1-\gamma) \arctan ((x-\mu) / \sigma)]}{[1+(x-\mu)^2 / \sigma^2]^{(1-\gamma) / 2}}
$$

**Comment by newville** [comment]
@joeyE99 You raised an issue without demonstrating that you read the instructions and respected our processes.  As promised there, I am closing this issue.  You can use the mailing list or Github Discussions, but there will be no follow-up discussion here.   If you are unhappy with the definition of a function you will be required to provide a citation and convince us that the current definition (and its citation) are worth changing.  You have an uphill battle.
