### ISSUE TITLE
Redundant calls to objective from minimize

### ISSUE THREAD

**Issue by earthshrink** [lmfit/lmfit-py#829]
#### First Time Issue Code

Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Minimize invokes the objective function two more times than useful 

As I understand from the documentation, the objective function is invoked iteratively until a best fit is found or the callback `iter_cb` returns `True`. The callback is passed the iteration count `iter` as argument, which I am also using to track the progress of the fit.
Turns out the objective function and the callback get called with `iter` set to -1 and then again with value 0, with the same parameters. The last iteration is also repeated, whether the minimization succeeded or the callback returned `True`.
This repetition does not break routine applications like engineering design, but adds to computational time. It also wastes programmer time examining the initial values and iterations when investigating convergence and satisfiability.

#### A Minimal, Complete, and Verifiable example

Please see [gist](https://gist.github.com/earthshrink/2a5d6ded7988164f75f0dbf1a2ed9def). When run, it produces the output
```
$ python fancy_fitter.py
compute_residual
-1. 10 {'a': 0.5}
compute_residual
0. 9 {'a': 0.5}
compute_residual
1. 10 {'a': 0.5}
Terminating iterations
compute_residual
1. 11 {'a': 0.5}
Terminating iterations
```
The first call of the objective function with `iter = -1` is redundant. This looks like an off-by-one bug from `iter` being initialized to -1 instead of 0, as appropriate for a counter. The last call appears a duplicate call with the same `iter` and `params` passed to the objective function. Both behaviours are seen when the minimization succeeds instead of being terminated by the callback returning `True`. See [example in Jupyter notebook](https://github.com/earthshrink/anomaly-sim/blob/master/near/near_sim_postencounter_doppler.ipynb).

#### Error message:

None- issue is inefficiency rather than incorrectness. 

#### Version information

Python: 3.10.6 (main, Sep 30 2022, 09:55:37) [GCC 11.3.0]
lmfit: 1.0.3, scipy: 1.9.0, numpy: 1.22.4,asteval: 0.9.27, uncertainties: 3.1.7

**Comment by newville** [comment]
@earthshrink 

> A Minimal, Complete, and Verifiable example
> Please see [gist](https://gist.github.com/earthshrink/2a5d6ded7988164f75f0dbf1a2ed9def). 

That is not minimal.  No links. 

Where is the evidence that there are redundant calls?

Are redundant calls a problem?  

You did not read and understand the instructions. Use the mailing list or Github Discussions.
