### ISSUE TITLE
Cannot deserialize ModelResult saved before 1.1.0

### ISSUE THREAD

**Issue by jcjaskula-aws** [lmfit/lmfit-py#845]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
A ModelResult loaded from a file saved with a version older than 1.1.0 will error when users try to print an HTML report. This is due to the fact that old serialized models do not contain the rsquared attribute, which is then set to `None` at loading. Printing an HTML report calls `gformat` (that accepts only `float`) on result.rsquared will result in a crash. 

More precisely, rsquared is set to `None` by default [here](https://github.com/lmfit/lmfit-py/blob/d2ba8e9aaefa99cf144c65aaaf13671989f2d681/lmfit/model.py#L1784) but its type is not checked [there](https://github.com/lmfit/lmfit-py/blob/d2ba8e9aaefa99cf144c65aaaf13671989f2d681/lmfit/printfuncs.py#L248).

###### A Minimal, Complete, and Verifiable example
https://gist.github.com/jcjaskula-aws/81f78f5b712b5a87d574bb7dd3cc46f6

###### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/lmfit/model.py", line 1651, in _repr_html_
    report = fitreport_html_table(self, show_correl=show_correl,
  File "/usr/lib/python3.10/site-packages/lmfit/printfuncs.py", line 249, in fitreport_html_table
    stat_row('R-squared', gformat(result.rsquared))
  File "/usr/lib/python3.10/site-packages/lmfit/printfuncs.py", line 62, in gformat
    expon = int(log10(abs(val)))
TypeError: bad operand type for abs(): 'NoneType'
```

###### Version information
Python: 3.10.10 (main, Feb  8 2023, 05:34:50) [Clang 14.0.0 (clang-1400.0.29.202)]

lmfit: 1.1.0, scipy: 1.9.3, numpy: 1.23.5,asteval: 0.9.29, uncertainties: 3.1.6

**Comment by newville** [comment]
@jcjaskula-aws OK, yes, we should check for a valid value of `rsquared` there.  I'll fold that into #844

**Comment by newville** [comment]
1.2 will not have intentional breaking changes, and I believe no significant modifications to existing tests. It will add new and enhanced features, which makes it more than only bug fixes.  

One thing we are not testing is reading models saved with older versions.  I  think we should add tests for that, exactly to avoid this sort of problem in the future.
