### ISSUE TITLE
19 tests fail

### ISSUE THREAD

**Issue by yurivict** [lmfit/lmfit-py#861]
See [log](https://people.freebsd.org/~yuri/py-lmfit-1.2.0.txt) here.

Version: 1.2.0
Python-3.9
FreeBSD 13.1

**Comment by newville** [comment]
@yurivict Hm, our tests all pass with Python 3.9 (and have for a long time).  See [these results](https://github.com/lmfit/lmfit-py/runs/12584267344).


Your log suggests that a great many (perhaps all - I may not have read the entire log closely) of the failures you see are associated with the error message:

```
  AttributeError: module 'dill' has no attribute 'dumps'
```

which means that a) there is an importable `dill` module, and b) it does not have a `dumps` function.    Our code does assume that if `dill` imports, then calling `dill.dumps()` should work.  The "basic usage" section of the [dill documentation](https://dill.readthedocs.io/en/latest/index.html#basic-usage) describes using `dill.dumps()` in its first use of `dill`,  so I doubt we will change that assumption.  

It seems more likely to me that there is something wrong with the installation of `dill` in your Python environment.   
I don't know why that would be the case.

**Comment by yurivict** [comment]
Please note that ```pyproject.toml``` doesn't list dill in ```requires```.

**Comment by yurivict** [comment]
The ```dill`` module was in fact broken. Updating it corrected all errors, except for this one:
```
=============================================================================================== FAILURES ================================================================================================
_________________________________________________________________________________________ test_Model_get_state __________________________________________________________________________________________

gmodel = <lmfit.Model: Model(gaussian)>

    def test_Model_get_state(gmodel):
        """Test for Model class function _get_state."""
        out = gmodel._get_state()
    
        assert isinstance(out, tuple)
        assert out[1] == out[2] is None
>       assert (out[0][1] is not None) == lmfit.jsonutils.HAS_DILL
E       AssertionError: assert (<function gaussian at 0x969ea8a60> is not None) == False
E        +  where False = <module 'lmfit.jsonutils' from '/usr/ports/math/py-lmfit/work-py39/lmfit-1.2.0/lmfit/jsonutils.py'>.HAS_DILL
E        +    where <module 'lmfit.jsonutils' from '/usr/ports/math/py-lmfit/work-py39/lmfit-1.2.0/lmfit/jsonutils.py'> = lmfit.jsonutils

tests/test_model.py:206: AssertionError
```

**Comment by newville** [comment]
@yurivict  That error still seems related to dill.  That test passes all our CI on all versions and platforms we test on.  
Yes, `dill` is not listed in `requirements.txt`, because it is not required by `lmfit`.  If it is installed, it might be used (and be expected to work correctly). 

We really can not guarantee that our unit tests pass for everyone on every system and environment.  That is not actually the purpose of our tests (nor is it really the purpose or promise of any test framework).   We try to be helpful to anyone using our code, but we also are going to have a default view that tests that pass in our test environments but fail on some particular system or environment mean that environment is faulty.    

Please use the results from running our tests on your environment as a test your environment.

**Comment by yurivict** [comment]
```lmfit.jsonutils.HAS_DILL``` is False, while the latest version of dill (py39-dill-0.3.6_1) is installed.
This seems to be wrong.

**Comment by newville** [comment]
@yurivict    Well, the code there (see https://github.com/lmfit/lmfit-py/blob/a03ac0f586540271010d2c5ca566679ca26cf7ad/lmfit/jsonutils.py#L9) reads:

```
try:
    import dill
    HAS_DILL = True
except ImportError:
    HAS_DILL = False
```

if `HAS_DILL` is `False`, then there was an `ImportError` with `import dill`.  

Again, all of our tests pass on all the systems and all of the test environments.    A failure on a different environment strongly suggests a problem **with that environment**.   

This really is not an issue with lmfit.  You ignored all of our requests and actual requirements for how to submit an issue and continue to suggest there is a problem here.   We have been exceedingly polite even in the face of your inability to follow our request or reason about debugging your system.
