### ISSUE TITLE
Cannot select method of scipy least_squares function

### ISSUE THREAD

**Issue by Spectre5** [lmfit/lmfit-py#890]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
Users cannot change the "method" when using `method='least_squares'` in the `Model.fit` method.  This is because `method` is a keyword both to `Model.fit` itself as well as a `fit_kws` to pass to the scipy `least_squares` method.

###### A Minimal, Complete, and Verifiable example
```python
from numpy import exp, linspace, random
from lmfit import Model

def gaussian(x, amp, cen, wid):
    return amp * exp(-(x-cen)**2 / wid)

x = linspace(-10, 10, 101)
y = gaussian(x, 2.33, 0.21, 1.51) + random.normal(0, 0.2, x.size)

gmodel = Model(gaussian)
params = gmodel.make_params(cen=0.3, amp=3, wid=1.25)
result = gmodel.fit(y, params, x=x, method='least_squares', fit_kws={'method': 'dogbox'})
print(result)
```

Specifically, the issue is with [these lines](https://github.com/lmfit/lmfit-py/blob/502cc9ba448eb90aec832c94063a07c47c92bcf5/lmfit/model.py#LL1086C1-L1089C59), where `method='least_squares'` is passed to `Model.fit` and is also in `fit_kws`.  Thus, we cannot change between the three methods of trf, dogbox, lm with the scipy `least_squares` function.
```python
        output = ModelResult(self, params, method=method, iter_cb=iter_cb,
                             scale_covar=scale_covar, fcn_kws=kwargs,
                             nan_policy=self.nan_policy, calc_covar=calc_covar,
                             max_nfev=max_nfev, **fit_kws)
```

###### Fit report:
N/A

###### Error message:
```python
Traceback (most recent call last):
  File "/home/dummy/lmfit/example.py", line 12, in <module>
    result = gmodel.fit(y, params, x=x, method='least_squares', fit_kws={'method': 'dogbox'})
  File "/home/dummy/lmfit/.venv/lib/python3.9/site-packages/lmfit/model.py", line 1086, in fit
    output = ModelResult(self, params, method=method, iter_cb=iter_cb,
TypeError: lmfit.model.ModelResult() got multiple values for keyword argument 'method'

```

###### Version information
```python
Python: 3.9.12 (main, Aug  6 2022, 20:04:53) 
[GCC 11.2.0]

lmfit: 1.2.1, scipy: 1.10.1, numpy: 1.24.3,asteval: 0.9.29, uncertainties: 3.1.7
```

###### Link(s)
N/A

**Comment by newville** [comment]
@Spectre5 I don't see an issue to solve here.   I would be perfectly willing to say that `lmfit.Model` with the `least_squares` method uses `trf`.  We are simply. unable to try to support the horrible, convoluted API of `scipy.optimize.least_squares`, and really cannot promise to support every option or method from `scipy.optimize`.   

It might be reasonable for us to support `method='trf'` and `method='dogbox'` in lmfit, and deprecate `method='least_squares'` completely.  That might more clearly signal that we are not even trying to support every convoluted option from `scipy`.   

As it turns out, this is a different library from `scipy.optimize` ;)

**Comment by Spectre5** [comment]
Thanks for the response @newville.  It is perfectly understandable to not desire supporting everything within scipy.optimize.

I specifically choose `method='dogbox'` in my example since I don't see any other way to use the dogbox solver with lmfit and it simplified my example.  In my actual application, I was trying to use `method='lmfit'` and use my custom loss function.  I know that the default method is `leastsq` and that it also uses L-M, but I don't think it can handle a custom loss function.

So if you choose to remove `least_squares` and instead support `method='dogbox'` and `method='trf'`, I would still appreciate a way to use `least_squares` with `method='lm'`.  Perhaps these three could be called `least_squares_lm`, `least_squares_trf`, and `least_squares_dogbox`.  Although that is admittedly fairly ugly, it does make it clear that they ultimately use the `least_squares` method in scipy and thus make it clear which method the `fit_kws` would be for.  Another possibility would be to keep `least_squares` and then support a secondary key to `Model.fit` to select the method, maybe a new keyword, e.g. `_method`, that would only be used with `least_squares`.

**Comment by newville** [comment]
@Spectre5  Yes, we already support `leastsq`.   It always uses a linear loss function ("Least Squares").  

One of the most bizarre (maybe hilarious, maybe utterly contemptible)  features of scipy adding a method called "least_squares" when one named "leastsq" already existed is that the newly added "least_squares" supported loss functions THAT ARE NOT LEAST SQUARES.   Well, unless you use the "lm" method of "least_squares", which really calls "leastsq" and so is always Least Squares - it does not support other "loss" types.  Similarly, bounds on variables are supported... well, unless using the "lm" method.  It is difficult to describe "least_squares" in a way that is not obviously critical.  It hurts just to read the documentation.  It is hopelessly awful.  There is just no way we could ever write a wrapper over such a ... thing.

What's more, "least_squares" just flat-out lies to the user about how many function evaluations it makes.  This is documented.  It documents that it uses a different meaning of "nfev: Number of function evaluations done."  from the actual number of times the function is evaluated.   Well, unless you use method="lm", in which case it is correct.   No kidding.

There is nothing from "least_squares" with method="lm" that we would need.  If scipy.optimize was sane, there would be a "trf" method and a "dogbox" method that were very, very similar in API.   Instead, they have "least_squares" to clearly remind the world that their review process and API design skills are sorely lacking.

**Comment by Spectre5** [comment]
The original scipy `least_squares` with `method='lm'` did just call `leastsq`, but that is not true anymore.  None the less, it is still true that it only accepts `loss='linear'` when the method is lm anyway.  The bounds do not matter much since lmfit can handle bounds outside of scipy - I'd even prefer for lmfit to handle bounds with the current least_squares the same way it does for most other methods and then just pass no bounds to scipy's least_squares.

I agree that the naming of the least_squares function is odd considering that it doesn't generally do classical least squares.

Please feel free to close this issue.

**Comment by newville** [comment]
@Spectre5 I will close this... but I am also willing to deprecate "least_squares" in favor of separate "trf" and "dogbox" methods.   

You say that `method='lm'` no longer calls `leastsq`, which I think needs some clarification for someone reading this later.   The `scipy.optimize.leastsq` function, and the `lm` option for `least_squares` both really do call the compiled code from MINPACK: `lmder` if a function to calculate the Jacobian is provided, and `lmdif` if not.   These are compiled code, some of the most beautiful F66-compliant Fortran ever written,  and basically the gold standard for non-linear least-squares implementations.    The wrapping of these functions is `scipy.optimize` is very old.

**Comment by Spectre5** [comment]
Yes, that's correct.  The earlier implementations of `scipy.optimize.least_squares` literally called `scipy.optimize.leastsq` when `method='lm'`, but now it directly calls the Fortran routines.

I think it is worthwhile to add a trf and dogbox method.
