### ISSUE TITLE
OS systems where multithreading.Pool is not allowed

### ISSUE THREAD

**Issue by CasperKristiansson** [lmfit/lmfit-py#929]
#### Description
Environments / OS systems like AWS lambda doesn't allow multithreading.Pool (https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda). Allow user to set an os.environ to turn of multithreading. Or implement other multithreading using concurrent.futures etc.

https://github.com/lmfit/lmfit-py/blob/e21a6aa9e8a0ac031a7440c3f682eeb2740ca33c/lmfit/minimizer.py#L1344-L1346

The error you get when running on AWS lambda:

```
OMP: Error #179: Function Can't open SHM2 failed:
OMP: System error #38: Function not implemented
```

**Comment by newville** [comment]
@CasperKristiansson Were the instructions for posting an issue unclear, or are you under the impression that they do not apply to you?
