### ISSUE TITLE
Default `method="leastsq"` in `Model().fit()` when `Parameters` have bounds

### ISSUE THREAD

**Issue by GuillermoAbadLopez** [lmfit/lmfit-py#944]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
Default [`method="leastsq"` in `Model().fit()` doesn't work correctly with bounds or constraints](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html#:~:text=With%20method%3D%27lm,for%20more%20information.), and therefore I think, it should not be the default method in those cases.  Instead `method="least_squares"` should be used. 

What I think happens, from experience, is that whenever the `"leastsq"` method fit collides with a bound, it stops the optimization, or stays there "colliding" against the wall, and instead the `"least_squares"`, is able to surround it, and keep optimizing, making it the good default choice for such cases.

###### A Minimal, Complete, and Verifiable example:

To show this I'll try to do a fit for an sinusoidal with amplitude=10, that collides first with another parameter (making the initial amplitude guess quite bad):
```
import numpy as np
import lmfit

sweep_interval = np.arange(0.0, 20.0, 0.1)

def sinus(x, a, b, c, d):
    return abs(a) * np.sin(b * np.array(x) - c) + d

data = sinus(sweep_interval, 10.0, 1.0, 0.0, 0.0) + np.random.normal(0, 0.1, len(sweep_interval))

mod = lmfit.Model(sinus)

mod.set_param_hint("a", value=1.0, min=0.0, max=11.0)  # add bounds to amplitude
mod.set_param_hint("b", value=0.8, min=0.0, max=2 * np.pi)
mod.set_param_hint("c", value=0.1)
mod.set_param_hint("d", value=0.08, min=0.05, max=0.2)

params = mod.make_params()
fit = mod.fit(data=data, params=params, x=sweep_interval)  # <<< Here default `method = "leastsq"` used

print(fit.params.valuesdict())
```
This means that the code above is not really using the bounds I set, in a correct way (stops the optimization). And if I want that, I have to change the last line to:
```
  fit = mod.fit(data=data, params=params, method="least_squares")
```
which until I realised was quite a pain 😅 .

Here I run two sinus with amplitude 10, and try to find its fit, and the first one, with the default method, most likely stoped when touching the bound (red square) at amplitude 2:
<img width="494" alt="Screenshot 2024-03-01 at 21 18 04" src="https://github.com/lmfit/lmfit-py/assets/109400222/320d2381-7625-4f9b-b0eb-23a62a51c461">
 and instead the other method="least_squares" did continue optimizing around the bound (most likely), until finding the good amplitude:
<img width="503" alt="Screenshot 2024-03-01 at 21 18 50" src="https://github.com/lmfit/lmfit-py/assets/109400222/d7ff7dd1-55a2-455d-87c7-0f159ba93bb4">

#### Possible solutions

Two following possible solutions come to mind:
- Check if the `Parameters` provided contain bounds, and in such case, use `method="least_squares"` as default.
- Use always `method="least_squares"` as default. (not my favorite approach)

If any of these ideas seem appealing to the maintainers of `lmfit` I could create a PR trying to improve this, with their feedback!

###### Fit report:
No need for the report

###### Error message:
No Error is raised, since its behaviour related

###### Version information
```
Python: 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]
lmfit: 1.1.0, scipy: 1.11.3, numpy: 1.24.1,asteval: 0.9.31, uncertainties: 3.1.7
```

###### Link(s)
Comment about this topic, from `scipy.optimize` documentation:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html#:~:text=With%20method%3D%27lm,for%20more%20information.

**Comment by newville** [comment]
@GuillermoAbadLopez 

> Default method="leastsq" in Model().fit() doesn't work correctly with bounds or constraints.

Yes, it does.   You may want to check the examples and documentation for lmfit before making false statements about how it works. 

I see no reference in Constraints

> . Instead method="least_squares" should be used.

Well, you can choose to use "least_squares" if you want to.  Heck, you can use another library, say `scipy.optimize` if that is what you want to do. 

> What I think happens, from experience, is that whenever the "leastsq" method fit collides with a bound, it stops the optimization, or stays there "colliding" against the wall, and instead the "least_squares", is able to surround it, and keep optimizing, making it the good default choice for such cases.
 
Well, as you say,  "leastsq" does not exceed the boundary.  Which is to say, it works correctly.    

In general, links to the scipy docs to explain how lmfit should work are not likely to be persuasive.   Again, if you want to use `scipy.optimize`, no one here is going to stop you.


> Possible solutions
> Two following possible solutions come to mind:
>
> 1. Check if the Parameters provided contain bounds, and in such case, use method="least_squares" as default.

Nope.

> 2. Use always method="least_squares" as default. (not my favorite approach)

Nope.

I am a hard "Nope" on using "least_squares" as a default for anything.  For one thing, it knowingly lies (yes, I mean deliberately and knowingly tell an untruth to mislead or deceive) about the number of function evaluations.   That is a disservice to the community.  We allow it to be used if you want, but it will not be the default method while I am involved in this project.
