### ISSUE TITLE
Additional keyword arguments to `Model` not passed to model function

### ISSUE THREAD

**Issue by pheuer** [lmfit/lmfit-py#947]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
After the update to version 1.3.0, additional keywords to `Model` appear to no longer be passed to the model function. The documentation says they should be (and this is a useful function)
https://lmfit.github.io/lmfit-py/model.html#lmfit.model.Model 

###### A Minimal, Complete, and Verifiable example
```python
import numpy as np
from lmfit import Model, Parameters

# Define some data
x = np.linspace(0,1,num=10)
data = 10*x+2

# Parameters list with one parameter
params = Parameters()
params.add("b", value=5, vary=True, min=0.5, max=25)


# Dictionary of constants to be passed to model function through **kws
# of `Model`
settings = {'a':2}


# Define a model function that takes the parameters and the settings keyword
def _model(x, settings=None, **params):
    
    # TypeError is raised here because `settings` keyword is not being 
    # passed through to `_model`, so `settings=None`
    a = settings['a']
    b = params['b']
    
    return x*b + a


model = Model(
     _model,
     independent_vars=["x"],
     settings=settings,
 )


# Try to fit
# This raises an exception
result = model.fit(
    data,
    params=params,
    x=x,
    method="leastsq",
)

print(result.best_values)
```
On `lmfit` version 1.3.0, this code produces the error message below. On version 1.2.0, it runs without error and prints the best fit results with the correct value for b (10).

```python
{'settings': {'a': 2}, 'b': 10.0}
```

###### Error message:
```
Traceback (most recent call last):

  File ~\anaconda3\envs\dev311\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\pvheu\desktop\model_minimal_example.py:38
    result = model.fit(

  File ~\anaconda3\envs\dev311\Lib\site-packages\lmfit\model.py:1174 in fit
    output.fit(data=data, weights=weights)

  File ~\anaconda3\envs\dev311\Lib\site-packages\lmfit\model.py:1559 in fit
    self.init_fit = self.model.eval(params=self.params, **self.userkws)

  File ~\anaconda3\envs\dev311\Lib\site-packages\lmfit\model.py:997 in eval
    return coerce_arraylike(self.func(**self.make_funcargs(params, kwargs)))

  File c:\users\pvheu\desktop\model_minimal_example.py:24 in _model
    a = settings['a']

TypeError: 'NoneType' object is not subscriptable
```

###### Version information
Python: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
lmfit: 1.3.0, scipy: 1.12.0, numpy: 1.26.4,asteval: 0.9.31, uncertainties: 3.1.7

###### Link(s)
Issue on the PlasmaPy repository: https://github.com/PlasmaPy/PlasmaPy/issues/2620

**Comment by newville** [comment]
@pheuer Hm, turning that into a complete example (ahem) and passing the `settings` in at runtime works for me:

```
import numpy as np
from lmfit import Model, Parameters

x = np.linspace(-10, 10, 501)
ydata = 1.78 + x * 4.6 + np.random.normal(scale=0.2, size=len(x))

params = Parameters()
params.add("b", value=5, vary=True, min=0.5, max=25)

settings = {'a':2}

def _model(x, settings=None, **params):
    print(settings, params)
    a = settings['a']
    b = params['b']
    return x*b + a

model = Model(_model)

result = model.fit(ydata, params=params, x=x, method="leastsq", settings=settings)

print(result.fit_report())
```

Passing in independent variables such as `settings` at run time rather than when constructing the Model seems sort of reasonable to me.  Is that insufficient for your needs?   


PS: It sure looks to me like this could have started as a discussion ;).

**Comment by pheuer** [comment]
@newville Yes, this works, but the function we have written in PlasmaPy is fitting quite a complex function (the optical Thomson scattering spectrum), so we have written a wrapper function to assemble the params and settings objects from user input (including a number of validation steps). Previously, I was able to provide the settings dictionary inside this wrapper function so the user didn't have to worry about passing it when calling `fit`. 

I can work around the issue using a lambda function to wrap `_model`, but since this is an unexpected breaking change in `lmfit` I wanted to make sure 1) whether it was intentional and 2) whether we should expect the behavior to stay the same in future releases. Thanks.

**Comment by newville** [comment]
@pheuer 

> I can work around the issue using a lambda function to wrap _model, but since this is an unexpected breaking change in lmfit I wanted to make sure 1) whether it was intentional and 2) whether we should expect the behavior to stay the same in future releases. Thanks.

Well, If you had wanted to make sure it was intentional or find out whether to expect this behavior will remain,  why did you not ask those questions?  (Do you even want answers? Yeah, I cannot tell.).  Instead, you very definitely said that you were sure that the code was broken, and that you were not at all asking questions about code behavior.  

It seems odd to me to use a lambda to pass your "settings" dictionary when you create a Model instead of passing it to `Model.fit()`.  Do the settings "belong to" the abstract Model, or are they needed for the fit the general Model to some particular data?

Pretty confusing all around.

**Comment by pheuer** [comment]
Ok, this is clearly unproductive: I already have my code fixed and I've alerted you to the breaking change in your package. I'll let you do what you will with that information.

**Comment by newville** [comment]
@pheuer Well, okay, I would not have called it unproductive, but you're free to feel that way.   
I think the usage of passing a default value at model creation time ought to work without needing to use a lambda function.  Your usage of having both a `settings` dictionary and a `params` dictionary for a model function is kind of confusing to me. 

I don't think we intentionally disallowed this when addressing other issues with passing in independent variables. I think restoring the earlier behavior that did allow setting an optional keyword when creating a Model is not a bad idea. 

Again, we vastly prefer starting with a discussion and statement of the issue and then finding a proposed solution.  You can consider that unproductive if you want.

**Comment by newville** [comment]
@pheuer Oh, wait, it *should* work, it's just that you are telling `Model` that `settings` is not an independent variable.  
Just create your model with:

```
model = Model(_model, settings=settings)  # leave out the independent_vars=['x']
```
and it will work.

And, yes that is intended behavior:  In version 1.3.0, your `settings` will now be identified as an independent variable.   Well, unless you explicitly say that is not ;).
