### ISSUE TITLE
`ModelResult.eval_uncertainty` returns a TypError with scalars

### ISSUE THREAD

**Issue by jcjaskula-aws** [lmfit/lmfit-py#951]
#### Description
`ModelResult.eval_uncertainty` returns a TypError when providing a singleton to the independent variables.  

###### A Minimal, Complete, and Verifiable example
```
from lmfit.models import LinearModel
import numpy as np
mr=LinearModel().fit(data=[1,2,4], x=[1,2,3])
mr.eval_uncertainty(x=1.2)  # error
mr.eval_uncertainty(x=np.array(1.2)) # error
```

`mr.eval_uncertainty(x=np.array([1.2]))` or `mr.eval_uncertainty(x=np.array([0, 1.2]))` do not throw any error.

###### Fit report:
N/A

###### Error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 mr.eval_uncertainty(x=1.2)

File ~/Documents/Devel/Quantum/External-repos/Misc/lmfit-py/lmfit/model.py:1689, in ModelResult.eval_uncertainty(self, params, sigma, dscale, **kwargs)
   1687 # ensure fjac and df2 are correct size if independent var updated by kwargs
   1688 feval = self.model.eval(params, **userkws)
-> 1689 ndata = len(feval.view('float64'))        # allows feval to be complex
   1690 covar = self.covar
   1691 if any(p.stderr is None for p in params.values()):

TypeError: len() of unsized object
```

###### Version information
Python: 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]

lmfit: 1.3.0.post2+gcf2626b7, scipy: 1.11.4, numpy: 1.26.3,asteval: 0.9.32, uncertainties: 3.1.6

**Comment by newville** [comment]
@jcjaskula-aws  length-1 arrays or scalars where arrays are expected are a perpetual font of errors.   

Probably replacing that. ```ndata = len(feval.view('float64')) ``` with ```ndata = feval.view('float64').size ``` would do the trick.
