### ISSUE TITLE
Numpy 2 support

### ISSUE THREAD

**Issue by paulmueller** [lmfit/lmfit-py#958]
#### First Time Issue Code
Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
For instance, with NumPy 2, the `Parameters.dumps` functionality (dumping parameters to JSON) does not work anymore.

###### A Minimal, Complete, and Verifiable example
```python
import numpy as np
from lmfit import Parameters

print("Numpy version", np.__version__)
params = Parameters()
params.add('amp', value=10, min=0)
params.dumps()
```

###### Error message:
```python
Numpy version 2.0.0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 7
      5 params = Parameters()
      6 params.add('amp', value=10, min=0)
----> 7 params.dumps()

File ~/repos/nanite/.env/lib/python3.10/site-packages/lmfit/parameter.py:573, in Parameters.dumps(self, **kws)
    570 sym_unique = self._asteval.user_defined_symbols()
    571 unique_symbols = {key: encode4js(deepcopy(self._asteval.symtable[key]))
    572                   for key in sym_unique}
--> 573 return json.dumps({'unique_symbols': unique_symbols,
    574                    'params': params}, **kws)

File /usr/lib/python3.10/json/__init__.py:231, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    226 # cached encoder
    227 if (not skipkeys and ensure_ascii and
    228     check_circular and allow_nan and
    229     cls is None and indent is None and separators is None and
    230     default is None and not sort_keys and not kw):
--> 231     return _default_encoder.encode(obj)
    232 if cls is None:
    233     cls = JSONEncoder

File /usr/lib/python3.10/json/encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File /usr/lib/python3.10/json/encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

File /usr/lib/python3.10/json/encoder.py:179, in JSONEncoder.default(self, o)
    160 def default(self, o):
    161     """Implement this method in a subclass such that it returns
    162     a serializable object for ``o``, or calls the base implementation
    163     (to raise a ``TypeError``).
   (...)
    177 
    178     """
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type OGridClass is not JSON serializable
```

###### Version information
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
lmfit: 1.3.1, scipy: 1.14.0, numpy: 2.0.0,asteval: 0.9.33, uncertainties: 3.2.1

**Comment by newville** [comment]
@paulmueller Thanks -- I guess we should not be too surprised by this, though I don't know where that "OGridClass" error is coming from.  I'll investigate, and work on setting up tests with Numpy 2.   We'll try to push out a fix for this soon.

**Comment by rsokolewicz** [comment]
I have similar problems for different fitters that we have implemented. Most of the errors we see are either that `IndexExpression` or `MGridClass` are not json serializable. These two and `OGridClass` are all classes that are defined in the `numpy` package. The strange thing is they were never json serializable, so not sure where the problem comes from 🤷 

e.g.

```
import numpy as np
import json

grid = np.ogrid
json.dumps(grid)
```

gives the same `TypeError: Object of type OGridClass is not JSON serializable` error on both numpy 1 and 2. 

The strange thing is that `np.ogrid` refers to a bare `OGridClass` instance and if you index it `grid[0:5,0:5]` it will return you an `np.ndarray`. We should never have a bare `OGridClass` instance. It looks like with numpy 1 lmfit produces ndarrays, while with numpy 2 lmfit fails to produce ndarrays and keeps the original `OGridClass` instances. 

maybe this helps in the investigation 😄

**Comment by newville** [comment]
@rsokolewicz Thanks -- yeah, I have not investigated fully, but "why are we creating an OGridClass?" was my first thought.  Anyway, hope to get this resolved soon.
