### ISSUE TITLE
Typo in create_uvars() method

### ISSUE THREAD

**Issue by AwkwardChessboard** [lmfit/lmfit-py#962]
#### First Time Issue Code

Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description
A pretty simple bug, short and sharp.
The "create_uvars" method in parameter.py always returns ufloats with an SD of zero.
Lines 519 and 521 of parameter.py try to access the _stderr_ attribute of a fitted Parameter, but have been incorrectly entered as _sdterr_, see below:

        uvars = {}
        has_expr = False
        vnames, vbest, vindex = [], [], -1
        savevals = self.valuesdict()
        for par in self.values():
            has_expr = has_expr or par.expr is not None
            if par.vary:
                vindex += 1
                vnames.append(par.name)
                vbest.append(par.value)
                if getattr(par, 'sdterr', None) is None and covar is not None:
                    par.stderr = sqrt(covar[vindex, vindex])
            uvars[par.name] = ufloat(par.value, getattr(par, 'sdterr', 0.0))

###### A Minimal, Complete, and Verifiable example
N/A

###### Fit report:
Not applicable, all fitting functionality proceeds as normal.

###### Error message:
No errors are raised during execution because you can always default to zero: `getattr(par, 'sdterr', 0.0)`

###### Version information
I'm currently using lmfit version 1.3.2

###### Link(s)

N/A

**Comment by newville** [comment]
@AwkwardChessboard Thanks.  Can you submit a PR?
